// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: agent_tryouts.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const appendAgentTryoutTurn = `-- name: AppendAgentTryoutTurn :one
WITH next_turn AS (
    SELECT COALESCE(MAX(turn_index), -1) + 1 AS turn_index
    FROM agent_tryout_turns
    WHERE agent_tryout_id = $1
)
INSERT INTO agent_tryout_turns (
    agent_tryout_id,
    turn_index,
    role,
    message,
    status
)
SELECT
    $1,
    next_turn.turn_index,
    $2,
    $3,
    'pending'
FROM next_turn
RETURNING id, agent_tryout_id, turn_index, role, message, status, created_at, processed_at
`

type AppendAgentTryoutTurnParams struct {
	AgentTryoutID uuid.UUID
	Role          string
	Message       string
}

func (q *Queries) AppendAgentTryoutTurn(ctx context.Context, arg AppendAgentTryoutTurnParams) (AgentTryoutTurn, error) {
	row := q.db.QueryRow(ctx, appendAgentTryoutTurn, arg.AgentTryoutID, arg.Role, arg.Message)
	var i AgentTryoutTurn
	err := row.Scan(
		&i.ID,
		&i.AgentTryoutID,
		&i.TurnIndex,
		&i.Role,
		&i.Message,
		&i.Status,
		&i.CreatedAt,
		&i.ProcessedAt,
	)
	return i, err
}

const claimAgentTryout = `-- name: ClaimAgentTryout :one
UPDATE agent_tryouts
SET
    organization_id = $1,
    workspace_id = $2,
    claimed_by_user_id = $3,
    claimed_at = $4,
    created_by_user_id = COALESCE(created_by_user_id, $3),
    expires_at = NULL
WHERE id = $5
  AND organization_id IS NULL
  AND workspace_id IS NULL
  AND claimed_by_user_id IS NULL
RETURNING id, organization_id, workspace_id, template_slug, status, input_snapshot, template_snapshot, tool_policy_snapshot, evaluation_spec_snapshot, selected_model_policy, summary, redaction_status, run_id, cost_limit_usd, actual_cost_usd, latency_ms, max_duration_seconds, anonymous_fingerprint_hash, created_by_user_id, claimed_by_user_id, claimed_at, expires_at, created_at, updated_at, parent_tryout_id, selected_harness_kind
`

type ClaimAgentTryoutParams struct {
	OrganizationID  *uuid.UUID
	WorkspaceID     *uuid.UUID
	ClaimedByUserID *uuid.UUID
	ClaimedAt       pgtype.Timestamptz
	ID              uuid.UUID
}

func (q *Queries) ClaimAgentTryout(ctx context.Context, arg ClaimAgentTryoutParams) (AgentTryout, error) {
	row := q.db.QueryRow(ctx, claimAgentTryout,
		arg.OrganizationID,
		arg.WorkspaceID,
		arg.ClaimedByUserID,
		arg.ClaimedAt,
		arg.ID,
	)
	var i AgentTryout
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.WorkspaceID,
		&i.TemplateSlug,
		&i.Status,
		&i.InputSnapshot,
		&i.TemplateSnapshot,
		&i.ToolPolicySnapshot,
		&i.EvaluationSpecSnapshot,
		&i.SelectedModelPolicy,
		&i.Summary,
		&i.RedactionStatus,
		&i.RunID,
		&i.CostLimitUsd,
		&i.ActualCostUsd,
		&i.LatencyMs,
		&i.MaxDurationSeconds,
		&i.AnonymousFingerprintHash,
		&i.CreatedByUserID,
		&i.ClaimedByUserID,
		&i.ClaimedAt,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ParentTryoutID,
		&i.SelectedHarnessKind,
	)
	return i, err
}

const claimNextPendingAgentTryoutTurn = `-- name: ClaimNextPendingAgentTryoutTurn :one
UPDATE agent_tryout_turns
SET status = 'processing'
WHERE id = (
    SELECT pending.id
    FROM agent_tryout_turns AS pending
    WHERE pending.agent_tryout_id = $1
      AND pending.status = 'pending'
    ORDER BY pending.id ASC
    LIMIT 1
    FOR UPDATE SKIP LOCKED
)
RETURNING id, agent_tryout_id, turn_index, role, message, status, created_at, processed_at
`

type ClaimNextPendingAgentTryoutTurnParams struct {
	AgentTryoutID uuid.UUID
}

func (q *Queries) ClaimNextPendingAgentTryoutTurn(ctx context.Context, arg ClaimNextPendingAgentTryoutTurnParams) (AgentTryoutTurn, error) {
	row := q.db.QueryRow(ctx, claimNextPendingAgentTryoutTurn, arg.AgentTryoutID)
	var i AgentTryoutTurn
	err := row.Scan(
		&i.ID,
		&i.AgentTryoutID,
		&i.TurnIndex,
		&i.Role,
		&i.Message,
		&i.Status,
		&i.CreatedAt,
		&i.ProcessedAt,
	)
	return i, err
}

const countPendingAgentTryoutTurns = `-- name: CountPendingAgentTryoutTurns :one
SELECT COUNT(*)
FROM agent_tryout_turns
WHERE agent_tryout_id = $1
  AND status = 'pending'
`

type CountPendingAgentTryoutTurnsParams struct {
	AgentTryoutID uuid.UUID
}

func (q *Queries) CountPendingAgentTryoutTurns(ctx context.Context, arg CountPendingAgentTryoutTurnsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countPendingAgentTryoutTurns, arg.AgentTryoutID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAgentTryout = `-- name: CreateAgentTryout :one
INSERT INTO agent_tryouts (
    organization_id,
    workspace_id,
    template_slug,
    status,
    input_snapshot,
    template_snapshot,
    tool_policy_snapshot,
    evaluation_spec_snapshot,
    selected_model_policy,
    selected_harness_kind,
    summary,
    redaction_status,
    run_id,
    cost_limit_usd,
    actual_cost_usd,
    latency_ms,
    max_duration_seconds,
    anonymous_fingerprint_hash,
    created_by_user_id,
    parent_tryout_id,
    expires_at
)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9,
    $10,
    $11,
    $12,
    $13,
    $14,
    $15,
    $16,
    $17,
    $18,
    $19,
    $20,
    $21
)
RETURNING id, organization_id, workspace_id, template_slug, status, input_snapshot, template_snapshot, tool_policy_snapshot, evaluation_spec_snapshot, selected_model_policy, summary, redaction_status, run_id, cost_limit_usd, actual_cost_usd, latency_ms, max_duration_seconds, anonymous_fingerprint_hash, created_by_user_id, claimed_by_user_id, claimed_at, expires_at, created_at, updated_at, parent_tryout_id, selected_harness_kind
`

type CreateAgentTryoutParams struct {
	OrganizationID           *uuid.UUID
	WorkspaceID              *uuid.UUID
	TemplateSlug             string
	Status                   string
	InputSnapshot            []byte
	TemplateSnapshot         []byte
	ToolPolicySnapshot       []byte
	EvaluationSpecSnapshot   []byte
	SelectedModelPolicy      []byte
	SelectedHarnessKind      *string
	Summary                  []byte
	RedactionStatus          string
	RunID                    *uuid.UUID
	CostLimitUsd             pgtype.Numeric
	ActualCostUsd            pgtype.Numeric
	LatencyMs                *int64
	MaxDurationSeconds       int32
	AnonymousFingerprintHash *string
	CreatedByUserID          *uuid.UUID
	ParentTryoutID           *uuid.UUID
	ExpiresAt                pgtype.Timestamptz
}

func (q *Queries) CreateAgentTryout(ctx context.Context, arg CreateAgentTryoutParams) (AgentTryout, error) {
	row := q.db.QueryRow(ctx, createAgentTryout,
		arg.OrganizationID,
		arg.WorkspaceID,
		arg.TemplateSlug,
		arg.Status,
		arg.InputSnapshot,
		arg.TemplateSnapshot,
		arg.ToolPolicySnapshot,
		arg.EvaluationSpecSnapshot,
		arg.SelectedModelPolicy,
		arg.SelectedHarnessKind,
		arg.Summary,
		arg.RedactionStatus,
		arg.RunID,
		arg.CostLimitUsd,
		arg.ActualCostUsd,
		arg.LatencyMs,
		arg.MaxDurationSeconds,
		arg.AnonymousFingerprintHash,
		arg.CreatedByUserID,
		arg.ParentTryoutID,
		arg.ExpiresAt,
	)
	var i AgentTryout
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.WorkspaceID,
		&i.TemplateSlug,
		&i.Status,
		&i.InputSnapshot,
		&i.TemplateSnapshot,
		&i.ToolPolicySnapshot,
		&i.EvaluationSpecSnapshot,
		&i.SelectedModelPolicy,
		&i.Summary,
		&i.RedactionStatus,
		&i.RunID,
		&i.CostLimitUsd,
		&i.ActualCostUsd,
		&i.LatencyMs,
		&i.MaxDurationSeconds,
		&i.AnonymousFingerprintHash,
		&i.CreatedByUserID,
		&i.ClaimedByUserID,
		&i.ClaimedAt,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ParentTryoutID,
		&i.SelectedHarnessKind,
	)
	return i, err
}

const getAgentTryoutByID = `-- name: GetAgentTryoutByID :one
SELECT id, organization_id, workspace_id, template_slug, status, input_snapshot, template_snapshot, tool_policy_snapshot, evaluation_spec_snapshot, selected_model_policy, summary, redaction_status, run_id, cost_limit_usd, actual_cost_usd, latency_ms, max_duration_seconds, anonymous_fingerprint_hash, created_by_user_id, claimed_by_user_id, claimed_at, expires_at, created_at, updated_at, parent_tryout_id, selected_harness_kind
FROM agent_tryouts
WHERE id = $1
LIMIT 1
`

type GetAgentTryoutByIDParams struct {
	ID uuid.UUID
}

func (q *Queries) GetAgentTryoutByID(ctx context.Context, arg GetAgentTryoutByIDParams) (AgentTryout, error) {
	row := q.db.QueryRow(ctx, getAgentTryoutByID, arg.ID)
	var i AgentTryout
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.WorkspaceID,
		&i.TemplateSlug,
		&i.Status,
		&i.InputSnapshot,
		&i.TemplateSnapshot,
		&i.ToolPolicySnapshot,
		&i.EvaluationSpecSnapshot,
		&i.SelectedModelPolicy,
		&i.Summary,
		&i.RedactionStatus,
		&i.RunID,
		&i.CostLimitUsd,
		&i.ActualCostUsd,
		&i.LatencyMs,
		&i.MaxDurationSeconds,
		&i.AnonymousFingerprintHash,
		&i.CreatedByUserID,
		&i.ClaimedByUserID,
		&i.ClaimedAt,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ParentTryoutID,
		&i.SelectedHarnessKind,
	)
	return i, err
}

const listAgentTryoutEventsAfter = `-- name: ListAgentTryoutEventsAfter :many
SELECT id, agent_tryout_id, sequence_number, event_type, actor_type, occurred_at, payload
FROM agent_tryout_events
WHERE agent_tryout_id = $1
  AND id > $2
ORDER BY id ASC
LIMIT $3
`

type ListAgentTryoutEventsAfterParams struct {
	AgentTryoutID uuid.UUID
	AfterID       int64
	LimitCount    int32
}

func (q *Queries) ListAgentTryoutEventsAfter(ctx context.Context, arg ListAgentTryoutEventsAfterParams) ([]AgentTryoutEvent, error) {
	rows, err := q.db.Query(ctx, listAgentTryoutEventsAfter, arg.AgentTryoutID, arg.AfterID, arg.LimitCount)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AgentTryoutEvent
	for rows.Next() {
		var i AgentTryoutEvent
		if err := rows.Scan(
			&i.ID,
			&i.AgentTryoutID,
			&i.SequenceNumber,
			&i.EventType,
			&i.ActorType,
			&i.OccurredAt,
			&i.Payload,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAgentTryoutsByWorkspaceID = `-- name: ListAgentTryoutsByWorkspaceID :many
SELECT id, organization_id, workspace_id, template_slug, status, input_snapshot, template_snapshot, tool_policy_snapshot, evaluation_spec_snapshot, selected_model_policy, summary, redaction_status, run_id, cost_limit_usd, actual_cost_usd, latency_ms, max_duration_seconds, anonymous_fingerprint_hash, created_by_user_id, claimed_by_user_id, claimed_at, expires_at, created_at, updated_at, parent_tryout_id, selected_harness_kind
FROM agent_tryouts
WHERE workspace_id = $1
ORDER BY created_at DESC
LIMIT $3 OFFSET $2
`

type ListAgentTryoutsByWorkspaceIDParams struct {
	WorkspaceID *uuid.UUID
	OffsetCount int32
	LimitCount  int32
}

func (q *Queries) ListAgentTryoutsByWorkspaceID(ctx context.Context, arg ListAgentTryoutsByWorkspaceIDParams) ([]AgentTryout, error) {
	rows, err := q.db.Query(ctx, listAgentTryoutsByWorkspaceID, arg.WorkspaceID, arg.OffsetCount, arg.LimitCount)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AgentTryout
	for rows.Next() {
		var i AgentTryout
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.WorkspaceID,
			&i.TemplateSlug,
			&i.Status,
			&i.InputSnapshot,
			&i.TemplateSnapshot,
			&i.ToolPolicySnapshot,
			&i.EvaluationSpecSnapshot,
			&i.SelectedModelPolicy,
			&i.Summary,
			&i.RedactionStatus,
			&i.RunID,
			&i.CostLimitUsd,
			&i.ActualCostUsd,
			&i.LatencyMs,
			&i.MaxDurationSeconds,
			&i.AnonymousFingerprintHash,
			&i.CreatedByUserID,
			&i.ClaimedByUserID,
			&i.ClaimedAt,
			&i.ExpiresAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ParentTryoutID,
			&i.SelectedHarnessKind,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markAgentTryoutTurnProcessed = `-- name: MarkAgentTryoutTurnProcessed :exec
UPDATE agent_tryout_turns
SET status = 'done', processed_at = now()
WHERE id = $1
`

type MarkAgentTryoutTurnProcessedParams struct {
	ID int64
}

func (q *Queries) MarkAgentTryoutTurnProcessed(ctx context.Context, arg MarkAgentTryoutTurnProcessedParams) error {
	_, err := q.db.Exec(ctx, markAgentTryoutTurnProcessed, arg.ID)
	return err
}

const recordAgentTryoutEvent = `-- name: RecordAgentTryoutEvent :one
WITH next_sequence AS (
    SELECT COALESCE(MAX(sequence_number), 0) + 1 AS sequence_number
    FROM agent_tryout_events
    WHERE agent_tryout_id = $1
)
INSERT INTO agent_tryout_events (
    agent_tryout_id,
    sequence_number,
    event_type,
    actor_type,
    payload
)
SELECT
    $1,
    next_sequence.sequence_number,
    $2,
    $3,
    $4
FROM next_sequence
RETURNING id, agent_tryout_id, sequence_number, event_type, actor_type, occurred_at, payload
`

type RecordAgentTryoutEventParams struct {
	AgentTryoutID uuid.UUID
	EventType     string
	ActorType     string
	Payload       []byte
}

func (q *Queries) RecordAgentTryoutEvent(ctx context.Context, arg RecordAgentTryoutEventParams) (AgentTryoutEvent, error) {
	row := q.db.QueryRow(ctx, recordAgentTryoutEvent,
		arg.AgentTryoutID,
		arg.EventType,
		arg.ActorType,
		arg.Payload,
	)
	var i AgentTryoutEvent
	err := row.Scan(
		&i.ID,
		&i.AgentTryoutID,
		&i.SequenceNumber,
		&i.EventType,
		&i.ActorType,
		&i.OccurredAt,
		&i.Payload,
	)
	return i, err
}

const setAgentTryoutRunID = `-- name: SetAgentTryoutRunID :one
UPDATE agent_tryouts
SET run_id = $1
WHERE id = $2
RETURNING id, organization_id, workspace_id, template_slug, status, input_snapshot, template_snapshot, tool_policy_snapshot, evaluation_spec_snapshot, selected_model_policy, summary, redaction_status, run_id, cost_limit_usd, actual_cost_usd, latency_ms, max_duration_seconds, anonymous_fingerprint_hash, created_by_user_id, claimed_by_user_id, claimed_at, expires_at, created_at, updated_at, parent_tryout_id, selected_harness_kind
`

type SetAgentTryoutRunIDParams struct {
	RunID *uuid.UUID
	ID    uuid.UUID
}

func (q *Queries) SetAgentTryoutRunID(ctx context.Context, arg SetAgentTryoutRunIDParams) (AgentTryout, error) {
	row := q.db.QueryRow(ctx, setAgentTryoutRunID, arg.RunID, arg.ID)
	var i AgentTryout
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.WorkspaceID,
		&i.TemplateSlug,
		&i.Status,
		&i.InputSnapshot,
		&i.TemplateSnapshot,
		&i.ToolPolicySnapshot,
		&i.EvaluationSpecSnapshot,
		&i.SelectedModelPolicy,
		&i.Summary,
		&i.RedactionStatus,
		&i.RunID,
		&i.CostLimitUsd,
		&i.ActualCostUsd,
		&i.LatencyMs,
		&i.MaxDurationSeconds,
		&i.AnonymousFingerprintHash,
		&i.CreatedByUserID,
		&i.ClaimedByUserID,
		&i.ClaimedAt,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ParentTryoutID,
		&i.SelectedHarnessKind,
	)
	return i, err
}

const updateAgentTryoutStatus = `-- name: UpdateAgentTryoutStatus :one
UPDATE agent_tryouts
SET
    status = $1,
    summary = COALESCE($2, summary),
    actual_cost_usd = COALESCE($3, actual_cost_usd),
    latency_ms = COALESCE($4, latency_ms),
    redaction_status = COALESCE($5, redaction_status)
WHERE id = $6
RETURNING id, organization_id, workspace_id, template_slug, status, input_snapshot, template_snapshot, tool_policy_snapshot, evaluation_spec_snapshot, selected_model_policy, summary, redaction_status, run_id, cost_limit_usd, actual_cost_usd, latency_ms, max_duration_seconds, anonymous_fingerprint_hash, created_by_user_id, claimed_by_user_id, claimed_at, expires_at, created_at, updated_at, parent_tryout_id, selected_harness_kind
`

type UpdateAgentTryoutStatusParams struct {
	Status          string
	Summary         []byte
	ActualCostUsd   pgtype.Numeric
	LatencyMs       *int64
	RedactionStatus *string
	ID              uuid.UUID
}

func (q *Queries) UpdateAgentTryoutStatus(ctx context.Context, arg UpdateAgentTryoutStatusParams) (AgentTryout, error) {
	row := q.db.QueryRow(ctx, updateAgentTryoutStatus,
		arg.Status,
		arg.Summary,
		arg.ActualCostUsd,
		arg.LatencyMs,
		arg.RedactionStatus,
		arg.ID,
	)
	var i AgentTryout
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.WorkspaceID,
		&i.TemplateSlug,
		&i.Status,
		&i.InputSnapshot,
		&i.TemplateSnapshot,
		&i.ToolPolicySnapshot,
		&i.EvaluationSpecSnapshot,
		&i.SelectedModelPolicy,
		&i.Summary,
		&i.RedactionStatus,
		&i.RunID,
		&i.CostLimitUsd,
		&i.ActualCostUsd,
		&i.LatencyMs,
		&i.MaxDurationSeconds,
		&i.AnonymousFingerprintHash,
		&i.CreatedByUserID,
		&i.ClaimedByUserID,
		&i.ClaimedAt,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ParentTryoutID,
		&i.SelectedHarnessKind,
	)
	return i, err
}
