// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: agent_builds.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const createAgentBuild = `-- name: CreateAgentBuild :one
INSERT INTO agent_builds (organization_id, workspace_id, name, slug, description, created_by_user_id)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, organization_id, workspace_id, name, slug, description, build_kind, lifecycle_status, created_by_user_id, created_at, updated_at, archived_at
`

type CreateAgentBuildParams struct {
	OrganizationID  uuid.UUID
	WorkspaceID     uuid.UUID
	Name            string
	Slug            string
	Description     *string
	CreatedByUserID *uuid.UUID
}

func (q *Queries) CreateAgentBuild(ctx context.Context, arg CreateAgentBuildParams) (AgentBuild, error) {
	row := q.db.QueryRow(ctx, createAgentBuild,
		arg.OrganizationID,
		arg.WorkspaceID,
		arg.Name,
		arg.Slug,
		arg.Description,
		arg.CreatedByUserID,
	)
	var i AgentBuild
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.WorkspaceID,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.BuildKind,
		&i.LifecycleStatus,
		&i.CreatedByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ArchivedAt,
	)
	return i, err
}

const createAgentBuildVersion = `-- name: CreateAgentBuildVersion :one
INSERT INTO agent_build_versions (
    agent_build_id, version_number, version_status,
    agent_kind, interface_spec, policy_spec, reasoning_spec,
    memory_spec, workflow_spec, guardrail_spec, model_spec,
    output_schema, trace_contract, publication_spec, created_by_user_id
) VALUES (
    $1, $2, 'draft',
    $3, $4, $5, $6,
    $7, $8, $9, $10,
    $11, $12, $13, $14
) RETURNING id, agent_build_id, version_number, version_status, build_definition, prompt_spec, output_schema, trace_contract, created_by_user_id, created_at, agent_kind, interface_spec, policy_spec, reasoning_spec, memory_spec, workflow_spec, guardrail_spec, model_spec, publication_spec
`

type CreateAgentBuildVersionParams struct {
	AgentBuildID    uuid.UUID
	VersionNumber   int32
	AgentKind       string
	InterfaceSpec   []byte
	PolicySpec      []byte
	ReasoningSpec   []byte
	MemorySpec      []byte
	WorkflowSpec    []byte
	GuardrailSpec   []byte
	ModelSpec       []byte
	OutputSchema    []byte
	TraceContract   []byte
	PublicationSpec []byte
	CreatedByUserID *uuid.UUID
}

func (q *Queries) CreateAgentBuildVersion(ctx context.Context, arg CreateAgentBuildVersionParams) (AgentBuildVersion, error) {
	row := q.db.QueryRow(ctx, createAgentBuildVersion,
		arg.AgentBuildID,
		arg.VersionNumber,
		arg.AgentKind,
		arg.InterfaceSpec,
		arg.PolicySpec,
		arg.ReasoningSpec,
		arg.MemorySpec,
		arg.WorkflowSpec,
		arg.GuardrailSpec,
		arg.ModelSpec,
		arg.OutputSchema,
		arg.TraceContract,
		arg.PublicationSpec,
		arg.CreatedByUserID,
	)
	var i AgentBuildVersion
	err := row.Scan(
		&i.ID,
		&i.AgentBuildID,
		&i.VersionNumber,
		&i.VersionStatus,
		&i.BuildDefinition,
		&i.PromptSpec,
		&i.OutputSchema,
		&i.TraceContract,
		&i.CreatedByUserID,
		&i.CreatedAt,
		&i.AgentKind,
		&i.InterfaceSpec,
		&i.PolicySpec,
		&i.ReasoningSpec,
		&i.MemorySpec,
		&i.WorkflowSpec,
		&i.GuardrailSpec,
		&i.ModelSpec,
		&i.PublicationSpec,
	)
	return i, err
}

const createAgentDeployment = `-- name: CreateAgentDeployment :one
INSERT INTO agent_deployments (
    organization_id, workspace_id, agent_build_id, current_build_version_id,
    runtime_profile_id, provider_account_id, model_alias_id,
    name, slug, deployment_type, deployment_config
) VALUES (
    $1, $2, $3, $4,
    $5, $6, $7,
    $8, $9, 'native', $10
) RETURNING id, organization_id, workspace_id, agent_build_id, current_build_version_id, runtime_profile_id, provider_account_id, model_alias_id, routing_policy_id, spend_policy_id, name, slug, deployment_type, endpoint_url, healthcheck_url, status, deployment_config, created_at, updated_at, archived_at
`

type CreateAgentDeploymentParams struct {
	OrganizationID        uuid.UUID
	WorkspaceID           uuid.UUID
	AgentBuildID          uuid.UUID
	CurrentBuildVersionID uuid.UUID
	RuntimeProfileID      uuid.UUID
	ProviderAccountID     *uuid.UUID
	ModelAliasID          *uuid.UUID
	Name                  string
	Slug                  string
	DeploymentConfig      []byte
}

func (q *Queries) CreateAgentDeployment(ctx context.Context, arg CreateAgentDeploymentParams) (AgentDeployment, error) {
	row := q.db.QueryRow(ctx, createAgentDeployment,
		arg.OrganizationID,
		arg.WorkspaceID,
		arg.AgentBuildID,
		arg.CurrentBuildVersionID,
		arg.RuntimeProfileID,
		arg.ProviderAccountID,
		arg.ModelAliasID,
		arg.Name,
		arg.Slug,
		arg.DeploymentConfig,
	)
	var i AgentDeployment
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.WorkspaceID,
		&i.AgentBuildID,
		&i.CurrentBuildVersionID,
		&i.RuntimeProfileID,
		&i.ProviderAccountID,
		&i.ModelAliasID,
		&i.RoutingPolicyID,
		&i.SpendPolicyID,
		&i.Name,
		&i.Slug,
		&i.DeploymentType,
		&i.EndpointUrl,
		&i.HealthcheckUrl,
		&i.Status,
		&i.DeploymentConfig,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ArchivedAt,
	)
	return i, err
}

const getAgentBuildByID = `-- name: GetAgentBuildByID :one
SELECT id, organization_id, workspace_id, name, slug, description, build_kind, lifecycle_status, created_by_user_id, created_at, updated_at, archived_at FROM agent_builds WHERE id = $1 AND archived_at IS NULL
`

type GetAgentBuildByIDParams struct {
	ID uuid.UUID
}

func (q *Queries) GetAgentBuildByID(ctx context.Context, arg GetAgentBuildByIDParams) (AgentBuild, error) {
	row := q.db.QueryRow(ctx, getAgentBuildByID, arg.ID)
	var i AgentBuild
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.WorkspaceID,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.BuildKind,
		&i.LifecycleStatus,
		&i.CreatedByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ArchivedAt,
	)
	return i, err
}

const getAgentBuildVersionByID = `-- name: GetAgentBuildVersionByID :one
SELECT id, agent_build_id, version_number, version_status, build_definition, prompt_spec, output_schema, trace_contract, created_by_user_id, created_at, agent_kind, interface_spec, policy_spec, reasoning_spec, memory_spec, workflow_spec, guardrail_spec, model_spec, publication_spec FROM agent_build_versions WHERE id = $1
`

type GetAgentBuildVersionByIDParams struct {
	ID uuid.UUID
}

func (q *Queries) GetAgentBuildVersionByID(ctx context.Context, arg GetAgentBuildVersionByIDParams) (AgentBuildVersion, error) {
	row := q.db.QueryRow(ctx, getAgentBuildVersionByID, arg.ID)
	var i AgentBuildVersion
	err := row.Scan(
		&i.ID,
		&i.AgentBuildID,
		&i.VersionNumber,
		&i.VersionStatus,
		&i.BuildDefinition,
		&i.PromptSpec,
		&i.OutputSchema,
		&i.TraceContract,
		&i.CreatedByUserID,
		&i.CreatedAt,
		&i.AgentKind,
		&i.InterfaceSpec,
		&i.PolicySpec,
		&i.ReasoningSpec,
		&i.MemorySpec,
		&i.WorkflowSpec,
		&i.GuardrailSpec,
		&i.ModelSpec,
		&i.PublicationSpec,
	)
	return i, err
}

const getLatestVersionNumberForBuild = `-- name: GetLatestVersionNumberForBuild :one
SELECT COALESCE(MAX(version_number), 0)::integer AS max_version
FROM agent_build_versions WHERE agent_build_id = $1
`

type GetLatestVersionNumberForBuildParams struct {
	AgentBuildID uuid.UUID
}

func (q *Queries) GetLatestVersionNumberForBuild(ctx context.Context, arg GetLatestVersionNumberForBuildParams) (int32, error) {
	row := q.db.QueryRow(ctx, getLatestVersionNumberForBuild, arg.AgentBuildID)
	var max_version int32
	err := row.Scan(&max_version)
	return max_version, err
}

const listAgentBuildVersionsByBuildID = `-- name: ListAgentBuildVersionsByBuildID :many
SELECT id, agent_build_id, version_number, version_status, build_definition, prompt_spec, output_schema, trace_contract, created_by_user_id, created_at, agent_kind, interface_spec, policy_spec, reasoning_spec, memory_spec, workflow_spec, guardrail_spec, model_spec, publication_spec FROM agent_build_versions
WHERE agent_build_id = $1
ORDER BY version_number DESC
`

type ListAgentBuildVersionsByBuildIDParams struct {
	AgentBuildID uuid.UUID
}

func (q *Queries) ListAgentBuildVersionsByBuildID(ctx context.Context, arg ListAgentBuildVersionsByBuildIDParams) ([]AgentBuildVersion, error) {
	rows, err := q.db.Query(ctx, listAgentBuildVersionsByBuildID, arg.AgentBuildID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AgentBuildVersion
	for rows.Next() {
		var i AgentBuildVersion
		if err := rows.Scan(
			&i.ID,
			&i.AgentBuildID,
			&i.VersionNumber,
			&i.VersionStatus,
			&i.BuildDefinition,
			&i.PromptSpec,
			&i.OutputSchema,
			&i.TraceContract,
			&i.CreatedByUserID,
			&i.CreatedAt,
			&i.AgentKind,
			&i.InterfaceSpec,
			&i.PolicySpec,
			&i.ReasoningSpec,
			&i.MemorySpec,
			&i.WorkflowSpec,
			&i.GuardrailSpec,
			&i.ModelSpec,
			&i.PublicationSpec,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAgentBuildsByWorkspaceID = `-- name: ListAgentBuildsByWorkspaceID :many
SELECT id, organization_id, workspace_id, name, slug, description, build_kind, lifecycle_status, created_by_user_id, created_at, updated_at, archived_at FROM agent_builds
WHERE workspace_id = $1 AND lifecycle_status = 'active' AND archived_at IS NULL
ORDER BY updated_at DESC
`

type ListAgentBuildsByWorkspaceIDParams struct {
	WorkspaceID uuid.UUID
}

func (q *Queries) ListAgentBuildsByWorkspaceID(ctx context.Context, arg ListAgentBuildsByWorkspaceIDParams) ([]AgentBuild, error) {
	rows, err := q.db.Query(ctx, listAgentBuildsByWorkspaceID, arg.WorkspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AgentBuild
	for rows.Next() {
		var i AgentBuild
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.WorkspaceID,
			&i.Name,
			&i.Slug,
			&i.Description,
			&i.BuildKind,
			&i.LifecycleStatus,
			&i.CreatedByUserID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ArchivedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markAgentBuildVersionReady = `-- name: MarkAgentBuildVersionReady :exec
UPDATE agent_build_versions SET version_status = 'ready'
WHERE id = $1 AND version_status = 'draft'
`

type MarkAgentBuildVersionReadyParams struct {
	ID uuid.UUID
}

func (q *Queries) MarkAgentBuildVersionReady(ctx context.Context, arg MarkAgentBuildVersionReadyParams) error {
	_, err := q.db.Exec(ctx, markAgentBuildVersionReady, arg.ID)
	return err
}

const updateAgentBuildVersionDraft = `-- name: UpdateAgentBuildVersionDraft :exec
UPDATE agent_build_versions SET
    agent_kind = $1,
    interface_spec = $2,
    policy_spec = $3,
    reasoning_spec = $4,
    memory_spec = $5,
    workflow_spec = $6,
    guardrail_spec = $7,
    model_spec = $8,
    output_schema = $9,
    trace_contract = $10,
    publication_spec = $11
WHERE id = $12 AND version_status = 'draft'
`

type UpdateAgentBuildVersionDraftParams struct {
	AgentKind       string
	InterfaceSpec   []byte
	PolicySpec      []byte
	ReasoningSpec   []byte
	MemorySpec      []byte
	WorkflowSpec    []byte
	GuardrailSpec   []byte
	ModelSpec       []byte
	OutputSchema    []byte
	TraceContract   []byte
	PublicationSpec []byte
	ID              uuid.UUID
}

func (q *Queries) UpdateAgentBuildVersionDraft(ctx context.Context, arg UpdateAgentBuildVersionDraftParams) error {
	_, err := q.db.Exec(ctx, updateAgentBuildVersionDraft,
		arg.AgentKind,
		arg.InterfaceSpec,
		arg.PolicySpec,
		arg.ReasoningSpec,
		arg.MemorySpec,
		arg.WorkflowSpec,
		arg.GuardrailSpec,
		arg.ModelSpec,
		arg.OutputSchema,
		arg.TraceContract,
		arg.PublicationSpec,
		arg.ID,
	)
	return err
}
