// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: agent_deployments.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const listActiveAgentDeploymentsByWorkspaceID = `-- name: ListActiveAgentDeploymentsByWorkspaceID :many
SELECT DISTINCT ON (ad.id)
    ad.id,
    ad.organization_id,
    ad.workspace_id,
    ad.current_build_version_id,
    ad.name,
    ad.status,
    ad.created_at,
    ad.updated_at,
    ads.id AS latest_snapshot_id
FROM agent_deployments ad
LEFT JOIN agent_deployment_snapshots ads
  ON ads.agent_deployment_id = ad.id
 AND ads.organization_id = ad.organization_id
 AND ads.workspace_id = ad.workspace_id
WHERE ad.workspace_id = $1
  AND ad.status = 'active'
  AND ad.archived_at IS NULL
ORDER BY ad.id, ads.created_at DESC, ads.id DESC
`

type ListActiveAgentDeploymentsByWorkspaceIDParams struct {
	WorkspaceID uuid.UUID
}

type ListActiveAgentDeploymentsByWorkspaceIDRow struct {
	ID                    uuid.UUID
	OrganizationID        uuid.UUID
	WorkspaceID           uuid.UUID
	CurrentBuildVersionID uuid.UUID
	Name                  string
	Status                string
	CreatedAt             pgtype.Timestamptz
	UpdatedAt             pgtype.Timestamptz
	LatestSnapshotID      *uuid.UUID
}

func (q *Queries) ListActiveAgentDeploymentsByWorkspaceID(ctx context.Context, arg ListActiveAgentDeploymentsByWorkspaceIDParams) ([]ListActiveAgentDeploymentsByWorkspaceIDRow, error) {
	rows, err := q.db.Query(ctx, listActiveAgentDeploymentsByWorkspaceID, arg.WorkspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListActiveAgentDeploymentsByWorkspaceIDRow
	for rows.Next() {
		var i ListActiveAgentDeploymentsByWorkspaceIDRow
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.WorkspaceID,
			&i.CurrentBuildVersionID,
			&i.Name,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.LatestSnapshotID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
