// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: billing.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const beginBillingWebhookEvent = `-- name: BeginBillingWebhookEvent :one
INSERT INTO billing_webhook_events (
    webhook_id,
    event_type,
    dodo_business_id,
    payload_type,
    event_timestamp,
    processed_at,
    payload_hash,
    status,
    error,
    payload
)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    NULL,
    $6,
    'failed',
    NULL,
    $7::jsonb
)
ON CONFLICT (webhook_id) DO UPDATE SET
    event_type = EXCLUDED.event_type,
    dodo_business_id = EXCLUDED.dodo_business_id,
    payload_type = EXCLUDED.payload_type,
    event_timestamp = EXCLUDED.event_timestamp,
    processed_at = NULL,
    payload_hash = EXCLUDED.payload_hash,
    status = 'failed',
    error = NULL,
    payload = EXCLUDED.payload
WHERE billing_webhook_events.status = 'failed'
RETURNING status
`

type BeginBillingWebhookEventParams struct {
	WebhookID      string
	EventType      string
	DodoBusinessID *string
	PayloadType    *string
	EventTimestamp pgtype.Timestamptz
	PayloadHash    string
	Payload        []byte
}

func (q *Queries) BeginBillingWebhookEvent(ctx context.Context, arg BeginBillingWebhookEventParams) (string, error) {
	row := q.db.QueryRow(ctx, beginBillingWebhookEvent,
		arg.WebhookID,
		arg.EventType,
		arg.DodoBusinessID,
		arg.PayloadType,
		arg.EventTimestamp,
		arg.PayloadHash,
		arg.Payload,
	)
	var status string
	err := row.Scan(&status)
	return status, err
}

const countActiveOrgMembers = `-- name: CountActiveOrgMembers :one
SELECT count(*)::integer
FROM organization_memberships
WHERE organization_id = $1
  AND membership_status = 'active'
`

type CountActiveOrgMembersParams struct {
	OrganizationID uuid.UUID
}

func (q *Queries) CountActiveOrgMembers(ctx context.Context, arg CountActiveOrgMembersParams) (int32, error) {
	row := q.db.QueryRow(ctx, countActiveOrgMembers, arg.OrganizationID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const countActiveWorkspaceRuns = `-- name: CountActiveWorkspaceRuns :one
SELECT count(*)::integer
FROM runs
WHERE workspace_id = $1
  AND status IN ('queued', 'provisioning', 'running', 'scoring')
`

type CountActiveWorkspaceRunsParams struct {
	WorkspaceID uuid.UUID
}

func (q *Queries) CountActiveWorkspaceRuns(ctx context.Context, arg CountActiveWorkspaceRunsParams) (int32, error) {
	row := q.db.QueryRow(ctx, countActiveWorkspaceRuns, arg.WorkspaceID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const countActiveWorkspaces = `-- name: CountActiveWorkspaces :one
SELECT count(*)::integer
FROM workspaces
WHERE organization_id = $1
  AND status = 'active'
`

type CountActiveWorkspacesParams struct {
	OrganizationID uuid.UUID
}

func (q *Queries) CountActiveWorkspaces(ctx context.Context, arg CountActiveWorkspacesParams) (int32, error) {
	row := q.db.QueryRow(ctx, countActiveWorkspaces, arg.OrganizationID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const createBillingCheckoutIntent = `-- name: CreateBillingCheckoutIntent :one
INSERT INTO billing_checkout_intents (
    id,
    organization_id,
    created_by_user_id,
    requested_plan_key,
    billing_period,
    seat_quantity,
    return_url,
    dodo_checkout_session_id,
    checkout_url,
    status,
    metadata
)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    NULLIF($8, ''),
    $9,
    'created',
    $10::jsonb
)
RETURNING
    id,
    organization_id,
    requested_plan_key,
    billing_period,
    seat_quantity,
    return_url,
    checkout_url,
    dodo_checkout_session_id,
    status,
    metadata,
    created_at,
    updated_at
`

type CreateBillingCheckoutIntentParams struct {
	ID                    uuid.UUID
	OrganizationID        uuid.UUID
	CreatedByUserID       *uuid.UUID
	RequestedPlanKey      string
	BillingPeriod         string
	SeatQuantity          int32
	ReturnUrl             string
	DodoCheckoutSessionID interface{}
	CheckoutUrl           string
	Metadata              []byte
}

type CreateBillingCheckoutIntentRow struct {
	ID                    uuid.UUID
	OrganizationID        uuid.UUID
	RequestedPlanKey      string
	BillingPeriod         string
	SeatQuantity          int32
	ReturnUrl             string
	CheckoutUrl           string
	DodoCheckoutSessionID *string
	Status                string
	Metadata              []byte
	CreatedAt             pgtype.Timestamptz
	UpdatedAt             pgtype.Timestamptz
}

func (q *Queries) CreateBillingCheckoutIntent(ctx context.Context, arg CreateBillingCheckoutIntentParams) (CreateBillingCheckoutIntentRow, error) {
	row := q.db.QueryRow(ctx, createBillingCheckoutIntent,
		arg.ID,
		arg.OrganizationID,
		arg.CreatedByUserID,
		arg.RequestedPlanKey,
		arg.BillingPeriod,
		arg.SeatQuantity,
		arg.ReturnUrl,
		arg.DodoCheckoutSessionID,
		arg.CheckoutUrl,
		arg.Metadata,
	)
	var i CreateBillingCheckoutIntentRow
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.RequestedPlanKey,
		&i.BillingPeriod,
		&i.SeatQuantity,
		&i.ReturnUrl,
		&i.CheckoutUrl,
		&i.DodoCheckoutSessionID,
		&i.Status,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createBillingTrialGrant = `-- name: CreateBillingTrialGrant :one
INSERT INTO billing_trial_grants (
    organization_id,
    plan_key,
    billing_period,
    started_by_user_id,
    started_at,
    expires_at
)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6
)
RETURNING
    id,
    organization_id,
    plan_key,
    billing_period,
    started_by_user_id,
    started_at,
    expires_at,
    created_at,
    updated_at
`

type CreateBillingTrialGrantParams struct {
	OrganizationID  uuid.UUID
	PlanKey         string
	BillingPeriod   string
	StartedByUserID *uuid.UUID
	StartedAt       pgtype.Timestamptz
	ExpiresAt       pgtype.Timestamptz
}

func (q *Queries) CreateBillingTrialGrant(ctx context.Context, arg CreateBillingTrialGrantParams) (BillingTrialGrant, error) {
	row := q.db.QueryRow(ctx, createBillingTrialGrant,
		arg.OrganizationID,
		arg.PlanKey,
		arg.BillingPeriod,
		arg.StartedByUserID,
		arg.StartedAt,
		arg.ExpiresAt,
	)
	var i BillingTrialGrant
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.PlanKey,
		&i.BillingPeriod,
		&i.StartedByUserID,
		&i.StartedAt,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const findOrganizationByDodoSubscriptionOrCustomer = `-- name: FindOrganizationByDodoSubscriptionOrCustomer :one
SELECT organization_id FROM (
    SELECT organization_id, 1 AS priority, latest_dodo_event_at AS event_at
    FROM billing_subscriptions
    WHERE dodo_subscription_id = $1
    UNION ALL
    SELECT organization_id, 2 AS priority, updated_at AS event_at
    FROM billing_accounts
    WHERE dodo_customer_id = NULLIF($2, '')
) candidates
ORDER BY priority, event_at DESC NULLS LAST
LIMIT 1
`

type FindOrganizationByDodoSubscriptionOrCustomerParams struct {
	DodoSubscriptionID string
	DodoCustomerID     interface{}
}

func (q *Queries) FindOrganizationByDodoSubscriptionOrCustomer(ctx context.Context, arg FindOrganizationByDodoSubscriptionOrCustomerParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, findOrganizationByDodoSubscriptionOrCustomer, arg.DodoSubscriptionID, arg.DodoCustomerID)
	var organization_id uuid.UUID
	err := row.Scan(&organization_id)
	return organization_id, err
}

const finishBillingWebhookEvent = `-- name: FinishBillingWebhookEvent :execrows
UPDATE billing_webhook_events
SET status = $1,
    error = $2,
    processed_at = now()
WHERE webhook_id = $3
`

type FinishBillingWebhookEventParams struct {
	Status    string
	Error     *string
	WebhookID string
}

func (q *Queries) FinishBillingWebhookEvent(ctx context.Context, arg FinishBillingWebhookEventParams) (int64, error) {
	result, err := q.db.Exec(ctx, finishBillingWebhookEvent, arg.Status, arg.Error, arg.WebhookID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getBillingAccountByOrganizationID = `-- name: GetBillingAccountByOrganizationID :one
SELECT
    id,
    organization_id,
    dodo_customer_id,
    billing_email,
    status,
    created_at,
    updated_at
FROM billing_accounts
WHERE organization_id = $1
`

type GetBillingAccountByOrganizationIDParams struct {
	OrganizationID uuid.UUID
}

func (q *Queries) GetBillingAccountByOrganizationID(ctx context.Context, arg GetBillingAccountByOrganizationIDParams) (BillingAccount, error) {
	row := q.db.QueryRow(ctx, getBillingAccountByOrganizationID, arg.OrganizationID)
	var i BillingAccount
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.DodoCustomerID,
		&i.BillingEmail,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getBillingSubscriptionByDodoID = `-- name: GetBillingSubscriptionByDodoID :one
SELECT
    id,
    organization_id,
    dodo_subscription_id,
    dodo_customer_id,
    dodo_product_id,
    plan_key,
    billing_period,
    status,
    next_billing_date,
    cancel_at_next_billing_date,
    cancelled_at,
    expires_at,
    trial_period_days,
    seat_quantity,
    addon_quantities,
    latest_dodo_event_at,
    created_at,
    updated_at
FROM billing_subscriptions
WHERE dodo_subscription_id = $1
`

type GetBillingSubscriptionByDodoIDParams struct {
	DodoSubscriptionID string
}

func (q *Queries) GetBillingSubscriptionByDodoID(ctx context.Context, arg GetBillingSubscriptionByDodoIDParams) (BillingSubscription, error) {
	row := q.db.QueryRow(ctx, getBillingSubscriptionByDodoID, arg.DodoSubscriptionID)
	var i BillingSubscription
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.DodoSubscriptionID,
		&i.DodoCustomerID,
		&i.DodoProductID,
		&i.PlanKey,
		&i.BillingPeriod,
		&i.Status,
		&i.NextBillingDate,
		&i.CancelAtNextBillingDate,
		&i.CancelledAt,
		&i.ExpiresAt,
		&i.TrialPeriodDays,
		&i.SeatQuantity,
		&i.AddonQuantities,
		&i.LatestDodoEventAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getLatestBillingCheckoutIntentByOrganizationID = `-- name: GetLatestBillingCheckoutIntentByOrganizationID :one
SELECT
    id,
    organization_id,
    requested_plan_key,
    billing_period,
    seat_quantity,
    return_url,
    checkout_url,
    dodo_checkout_session_id,
    status,
    metadata,
    created_at,
    updated_at
FROM billing_checkout_intents
WHERE organization_id = $1
ORDER BY created_at DESC
LIMIT 1
`

type GetLatestBillingCheckoutIntentByOrganizationIDParams struct {
	OrganizationID uuid.UUID
}

type GetLatestBillingCheckoutIntentByOrganizationIDRow struct {
	ID                    uuid.UUID
	OrganizationID        uuid.UUID
	RequestedPlanKey      string
	BillingPeriod         string
	SeatQuantity          int32
	ReturnUrl             string
	CheckoutUrl           string
	DodoCheckoutSessionID *string
	Status                string
	Metadata              []byte
	CreatedAt             pgtype.Timestamptz
	UpdatedAt             pgtype.Timestamptz
}

func (q *Queries) GetLatestBillingCheckoutIntentByOrganizationID(ctx context.Context, arg GetLatestBillingCheckoutIntentByOrganizationIDParams) (GetLatestBillingCheckoutIntentByOrganizationIDRow, error) {
	row := q.db.QueryRow(ctx, getLatestBillingCheckoutIntentByOrganizationID, arg.OrganizationID)
	var i GetLatestBillingCheckoutIntentByOrganizationIDRow
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.RequestedPlanKey,
		&i.BillingPeriod,
		&i.SeatQuantity,
		&i.ReturnUrl,
		&i.CheckoutUrl,
		&i.DodoCheckoutSessionID,
		&i.Status,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getLatestBillingSubscriptionByOrganizationID = `-- name: GetLatestBillingSubscriptionByOrganizationID :one
SELECT
    id,
    organization_id,
    dodo_subscription_id,
    dodo_customer_id,
    dodo_product_id,
    plan_key,
    billing_period,
    status,
    next_billing_date,
    cancel_at_next_billing_date,
    cancelled_at,
    expires_at,
    trial_period_days,
    seat_quantity,
    addon_quantities,
    latest_dodo_event_at,
    created_at,
    updated_at
FROM billing_subscriptions
WHERE organization_id = $1
ORDER BY latest_dodo_event_at DESC NULLS LAST, updated_at DESC
LIMIT 1
`

type GetLatestBillingSubscriptionByOrganizationIDParams struct {
	OrganizationID uuid.UUID
}

func (q *Queries) GetLatestBillingSubscriptionByOrganizationID(ctx context.Context, arg GetLatestBillingSubscriptionByOrganizationIDParams) (BillingSubscription, error) {
	row := q.db.QueryRow(ctx, getLatestBillingSubscriptionByOrganizationID, arg.OrganizationID)
	var i BillingSubscription
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.DodoSubscriptionID,
		&i.DodoCustomerID,
		&i.DodoProductID,
		&i.PlanKey,
		&i.BillingPeriod,
		&i.Status,
		&i.NextBillingDate,
		&i.CancelAtNextBillingDate,
		&i.CancelledAt,
		&i.ExpiresAt,
		&i.TrialPeriodDays,
		&i.SeatQuantity,
		&i.AddonQuantities,
		&i.LatestDodoEventAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getOrganizationEntitlements = `-- name: GetOrganizationEntitlements :one
SELECT
    plan_key,
    billing_period,
    status,
    seat_quantity,
    seats_limit,
    workspaces_limit,
    races_per_workspace_month,
    max_models_per_race,
    replay_retention_days,
    concurrency_limit,
    feature_flags,
    source_subscription_id,
    effective_at,
    expires_at,
    updated_at
FROM organization_entitlements
WHERE organization_id = $1
`

type GetOrganizationEntitlementsParams struct {
	OrganizationID uuid.UUID
}

type GetOrganizationEntitlementsRow struct {
	PlanKey                string
	BillingPeriod          string
	Status                 string
	SeatQuantity           int32
	SeatsLimit             *int32
	WorkspacesLimit        *int32
	RacesPerWorkspaceMonth *int32
	MaxModelsPerRace       *int32
	ReplayRetentionDays    *int32
	ConcurrencyLimit       *int32
	FeatureFlags           []byte
	SourceSubscriptionID   *uuid.UUID
	EffectiveAt            pgtype.Timestamptz
	ExpiresAt              pgtype.Timestamptz
	UpdatedAt              pgtype.Timestamptz
}

func (q *Queries) GetOrganizationEntitlements(ctx context.Context, arg GetOrganizationEntitlementsParams) (GetOrganizationEntitlementsRow, error) {
	row := q.db.QueryRow(ctx, getOrganizationEntitlements, arg.OrganizationID)
	var i GetOrganizationEntitlementsRow
	err := row.Scan(
		&i.PlanKey,
		&i.BillingPeriod,
		&i.Status,
		&i.SeatQuantity,
		&i.SeatsLimit,
		&i.WorkspacesLimit,
		&i.RacesPerWorkspaceMonth,
		&i.MaxModelsPerRace,
		&i.ReplayRetentionDays,
		&i.ConcurrencyLimit,
		&i.FeatureFlags,
		&i.SourceSubscriptionID,
		&i.EffectiveAt,
		&i.ExpiresAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getWorkspaceUsageWindowRaceCount = `-- name: GetWorkspaceUsageWindowRaceCount :one
SELECT race_count
FROM workspace_usage_windows
WHERE workspace_id = $1
  AND window_start = $2
`

type GetWorkspaceUsageWindowRaceCountParams struct {
	WorkspaceID uuid.UUID
	WindowStart pgtype.Timestamptz
}

func (q *Queries) GetWorkspaceUsageWindowRaceCount(ctx context.Context, arg GetWorkspaceUsageWindowRaceCountParams) (int32, error) {
	row := q.db.QueryRow(ctx, getWorkspaceUsageWindowRaceCount, arg.WorkspaceID, arg.WindowStart)
	var race_count int32
	err := row.Scan(&race_count)
	return race_count, err
}

const markBillingCheckoutIntentCompleted = `-- name: MarkBillingCheckoutIntentCompleted :execrows
UPDATE billing_checkout_intents
SET status = 'completed'
WHERE id = $1
  AND status <> 'completed'
`

type MarkBillingCheckoutIntentCompletedParams struct {
	ID uuid.UUID
}

func (q *Queries) MarkBillingCheckoutIntentCompleted(ctx context.Context, arg MarkBillingCheckoutIntentCompletedParams) (int64, error) {
	result, err := q.db.Exec(ctx, markBillingCheckoutIntentCompleted, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const resolveWorkspaceOrganization = `-- name: ResolveWorkspaceOrganization :one
SELECT organization_id
FROM workspaces
WHERE id = $1
  AND status = 'active'
`

type ResolveWorkspaceOrganizationParams struct {
	WorkspaceID uuid.UUID
}

func (q *Queries) ResolveWorkspaceOrganization(ctx context.Context, arg ResolveWorkspaceOrganizationParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, resolveWorkspaceOrganization, arg.WorkspaceID)
	var organization_id uuid.UUID
	err := row.Scan(&organization_id)
	return organization_id, err
}

const upsertBillingAccount = `-- name: UpsertBillingAccount :exec
INSERT INTO billing_accounts (organization_id, dodo_customer_id, billing_email, status)
VALUES (
    $1,
    NULLIF($2, ''),
    NULLIF($3, ''),
    $4
)
ON CONFLICT (organization_id) DO UPDATE SET
    dodo_customer_id = COALESCE(EXCLUDED.dodo_customer_id, billing_accounts.dodo_customer_id),
    billing_email = COALESCE(EXCLUDED.billing_email, billing_accounts.billing_email),
    status = EXCLUDED.status
`

type UpsertBillingAccountParams struct {
	OrganizationID uuid.UUID
	DodoCustomerID interface{}
	BillingEmail   interface{}
	Status         string
}

func (q *Queries) UpsertBillingAccount(ctx context.Context, arg UpsertBillingAccountParams) error {
	_, err := q.db.Exec(ctx, upsertBillingAccount,
		arg.OrganizationID,
		arg.DodoCustomerID,
		arg.BillingEmail,
		arg.Status,
	)
	return err
}

const upsertBillingSubscription = `-- name: UpsertBillingSubscription :one
INSERT INTO billing_subscriptions (
    organization_id,
    dodo_subscription_id,
    dodo_customer_id,
    dodo_product_id,
    plan_key,
    billing_period,
    status,
    next_billing_date,
    cancel_at_next_billing_date,
    cancelled_at,
    expires_at,
    trial_period_days,
    seat_quantity,
    addon_quantities,
    latest_dodo_event_at
)
VALUES (
    $1,
    $2,
    NULLIF($3, ''),
    $4,
    $5,
    $6,
    $7,
    $8,
    $9,
    $10,
    $11,
    $12,
    $13,
    $14::jsonb,
    $15
)
ON CONFLICT (dodo_subscription_id) DO UPDATE SET
    organization_id = EXCLUDED.organization_id,
    dodo_customer_id = COALESCE(EXCLUDED.dodo_customer_id, billing_subscriptions.dodo_customer_id),
    dodo_product_id = EXCLUDED.dodo_product_id,
    plan_key = EXCLUDED.plan_key,
    billing_period = EXCLUDED.billing_period,
    status = EXCLUDED.status,
    next_billing_date = EXCLUDED.next_billing_date,
    cancel_at_next_billing_date = EXCLUDED.cancel_at_next_billing_date,
    cancelled_at = EXCLUDED.cancelled_at,
    expires_at = EXCLUDED.expires_at,
    trial_period_days = EXCLUDED.trial_period_days,
    seat_quantity = EXCLUDED.seat_quantity,
    addon_quantities = EXCLUDED.addon_quantities,
    latest_dodo_event_at = COALESCE(
        GREATEST(billing_subscriptions.latest_dodo_event_at, EXCLUDED.latest_dodo_event_at),
        billing_subscriptions.latest_dodo_event_at,
        EXCLUDED.latest_dodo_event_at
    )
WHERE billing_subscriptions.latest_dodo_event_at IS NULL
   OR EXCLUDED.latest_dodo_event_at IS NULL
   OR EXCLUDED.latest_dodo_event_at >= billing_subscriptions.latest_dodo_event_at
RETURNING
    id,
    organization_id,
    dodo_subscription_id,
    dodo_customer_id,
    dodo_product_id,
    plan_key,
    billing_period,
    status,
    next_billing_date,
    cancel_at_next_billing_date,
    cancelled_at,
    expires_at,
    trial_period_days,
    seat_quantity,
    addon_quantities,
    latest_dodo_event_at,
    created_at,
    updated_at
`

type UpsertBillingSubscriptionParams struct {
	OrganizationID          uuid.UUID
	DodoSubscriptionID      string
	DodoCustomerID          interface{}
	DodoProductID           string
	PlanKey                 string
	BillingPeriod           string
	Status                  string
	NextBillingDate         pgtype.Timestamptz
	CancelAtNextBillingDate bool
	CancelledAt             pgtype.Timestamptz
	ExpiresAt               pgtype.Timestamptz
	TrialPeriodDays         *int32
	SeatQuantity            int32
	AddonQuantities         []byte
	LatestDodoEventAt       pgtype.Timestamptz
}

func (q *Queries) UpsertBillingSubscription(ctx context.Context, arg UpsertBillingSubscriptionParams) (BillingSubscription, error) {
	row := q.db.QueryRow(ctx, upsertBillingSubscription,
		arg.OrganizationID,
		arg.DodoSubscriptionID,
		arg.DodoCustomerID,
		arg.DodoProductID,
		arg.PlanKey,
		arg.BillingPeriod,
		arg.Status,
		arg.NextBillingDate,
		arg.CancelAtNextBillingDate,
		arg.CancelledAt,
		arg.ExpiresAt,
		arg.TrialPeriodDays,
		arg.SeatQuantity,
		arg.AddonQuantities,
		arg.LatestDodoEventAt,
	)
	var i BillingSubscription
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.DodoSubscriptionID,
		&i.DodoCustomerID,
		&i.DodoProductID,
		&i.PlanKey,
		&i.BillingPeriod,
		&i.Status,
		&i.NextBillingDate,
		&i.CancelAtNextBillingDate,
		&i.CancelledAt,
		&i.ExpiresAt,
		&i.TrialPeriodDays,
		&i.SeatQuantity,
		&i.AddonQuantities,
		&i.LatestDodoEventAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertOrganizationEntitlements = `-- name: UpsertOrganizationEntitlements :exec
INSERT INTO organization_entitlements (
    organization_id,
    plan_key,
    billing_period,
    status,
    seat_quantity,
    seats_limit,
    workspaces_limit,
    races_per_workspace_month,
    max_models_per_race,
    replay_retention_days,
    concurrency_limit,
    feature_flags,
    source_subscription_id,
    effective_at,
    expires_at
)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9,
    $10,
    $11,
    $12::jsonb,
    $13,
    now(),
    $14
)
ON CONFLICT (organization_id) DO UPDATE SET
    plan_key = EXCLUDED.plan_key,
    billing_period = EXCLUDED.billing_period,
    status = EXCLUDED.status,
    seat_quantity = EXCLUDED.seat_quantity,
    seats_limit = EXCLUDED.seats_limit,
    workspaces_limit = EXCLUDED.workspaces_limit,
    races_per_workspace_month = EXCLUDED.races_per_workspace_month,
    max_models_per_race = EXCLUDED.max_models_per_race,
    replay_retention_days = EXCLUDED.replay_retention_days,
    concurrency_limit = EXCLUDED.concurrency_limit,
    feature_flags = EXCLUDED.feature_flags,
    source_subscription_id = EXCLUDED.source_subscription_id,
    effective_at = EXCLUDED.effective_at,
    expires_at = EXCLUDED.expires_at
`

type UpsertOrganizationEntitlementsParams struct {
	OrganizationID         uuid.UUID
	PlanKey                string
	BillingPeriod          string
	Status                 string
	SeatQuantity           int32
	SeatsLimit             *int32
	WorkspacesLimit        *int32
	RacesPerWorkspaceMonth *int32
	MaxModelsPerRace       *int32
	ReplayRetentionDays    *int32
	ConcurrencyLimit       *int32
	FeatureFlags           []byte
	SourceSubscriptionID   *uuid.UUID
	ExpiresAt              pgtype.Timestamptz
}

func (q *Queries) UpsertOrganizationEntitlements(ctx context.Context, arg UpsertOrganizationEntitlementsParams) error {
	_, err := q.db.Exec(ctx, upsertOrganizationEntitlements,
		arg.OrganizationID,
		arg.PlanKey,
		arg.BillingPeriod,
		arg.Status,
		arg.SeatQuantity,
		arg.SeatsLimit,
		arg.WorkspacesLimit,
		arg.RacesPerWorkspaceMonth,
		arg.MaxModelsPerRace,
		arg.ReplayRetentionDays,
		arg.ConcurrencyLimit,
		arg.FeatureFlags,
		arg.SourceSubscriptionID,
		arg.ExpiresAt,
	)
	return err
}
