// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: challenge_pack_drafts.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const createChallengePackDraft = `-- name: CreateChallengePackDraft :one
INSERT INTO challenge_pack_drafts (
    workspace_id,
    name,
    execution_mode,
    challenge_pack_id,
    composition,
    created_by_user_id
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6
)
RETURNING id, workspace_id, name, execution_mode, challenge_pack_id, composition, status, last_published_version_id, created_by_user_id, created_at, updated_at
`

type CreateChallengePackDraftParams struct {
	WorkspaceID     uuid.UUID
	Name            string
	ExecutionMode   string
	ChallengePackID *uuid.UUID
	Composition     []byte
	CreatedByUserID *uuid.UUID
}

func (q *Queries) CreateChallengePackDraft(ctx context.Context, arg CreateChallengePackDraftParams) (ChallengePackDraft, error) {
	row := q.db.QueryRow(ctx, createChallengePackDraft,
		arg.WorkspaceID,
		arg.Name,
		arg.ExecutionMode,
		arg.ChallengePackID,
		arg.Composition,
		arg.CreatedByUserID,
	)
	var i ChallengePackDraft
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Name,
		&i.ExecutionMode,
		&i.ChallengePackID,
		&i.Composition,
		&i.Status,
		&i.LastPublishedVersionID,
		&i.CreatedByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteChallengePackDraft = `-- name: DeleteChallengePackDraft :exec
DELETE FROM challenge_pack_drafts
WHERE id = $1
`

type DeleteChallengePackDraftParams struct {
	ID uuid.UUID
}

func (q *Queries) DeleteChallengePackDraft(ctx context.Context, arg DeleteChallengePackDraftParams) error {
	_, err := q.db.Exec(ctx, deleteChallengePackDraft, arg.ID)
	return err
}

const getChallengePackDraftByID = `-- name: GetChallengePackDraftByID :one
SELECT id, workspace_id, name, execution_mode, challenge_pack_id, composition, status, last_published_version_id, created_by_user_id, created_at, updated_at
FROM challenge_pack_drafts
WHERE id = $1
LIMIT 1
`

type GetChallengePackDraftByIDParams struct {
	ID uuid.UUID
}

func (q *Queries) GetChallengePackDraftByID(ctx context.Context, arg GetChallengePackDraftByIDParams) (ChallengePackDraft, error) {
	row := q.db.QueryRow(ctx, getChallengePackDraftByID, arg.ID)
	var i ChallengePackDraft
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Name,
		&i.ExecutionMode,
		&i.ChallengePackID,
		&i.Composition,
		&i.Status,
		&i.LastPublishedVersionID,
		&i.CreatedByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listChallengePackDraftsByWorkspace = `-- name: ListChallengePackDraftsByWorkspace :many
SELECT id, workspace_id, name, execution_mode, challenge_pack_id, composition, status, last_published_version_id, created_by_user_id, created_at, updated_at
FROM challenge_pack_drafts
WHERE workspace_id = $1
  AND status = 'draft'
ORDER BY updated_at DESC, id DESC
`

type ListChallengePackDraftsByWorkspaceParams struct {
	WorkspaceID uuid.UUID
}

func (q *Queries) ListChallengePackDraftsByWorkspace(ctx context.Context, arg ListChallengePackDraftsByWorkspaceParams) ([]ChallengePackDraft, error) {
	rows, err := q.db.Query(ctx, listChallengePackDraftsByWorkspace, arg.WorkspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ChallengePackDraft
	for rows.Next() {
		var i ChallengePackDraft
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.Name,
			&i.ExecutionMode,
			&i.ChallengePackID,
			&i.Composition,
			&i.Status,
			&i.LastPublishedVersionID,
			&i.CreatedByUserID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const patchChallengePackDraft = `-- name: PatchChallengePackDraft :one
UPDATE challenge_pack_drafts
SET name = COALESCE($1, name),
    execution_mode = COALESCE($2, execution_mode),
    composition = COALESCE($3::jsonb, composition),
    challenge_pack_id = COALESCE($4, challenge_pack_id),
    status = COALESCE($5::text, status),
    last_published_version_id = COALESCE($6, last_published_version_id)
WHERE id = $7
RETURNING id, workspace_id, name, execution_mode, challenge_pack_id, composition, status, last_published_version_id, created_by_user_id, created_at, updated_at
`

type PatchChallengePackDraftParams struct {
	Name                   *string
	ExecutionMode          *string
	Composition            []byte
	ChallengePackID        *uuid.UUID
	ToStatus               *string
	LastPublishedVersionID *uuid.UUID
	ID                     uuid.UUID
}

func (q *Queries) PatchChallengePackDraft(ctx context.Context, arg PatchChallengePackDraftParams) (ChallengePackDraft, error) {
	row := q.db.QueryRow(ctx, patchChallengePackDraft,
		arg.Name,
		arg.ExecutionMode,
		arg.Composition,
		arg.ChallengePackID,
		arg.ToStatus,
		arg.LastPublishedVersionID,
		arg.ID,
	)
	var i ChallengePackDraft
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Name,
		&i.ExecutionMode,
		&i.ChallengePackID,
		&i.Composition,
		&i.Status,
		&i.LastPublishedVersionID,
		&i.CreatedByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
