// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: challenge_pieces.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const archiveChallengePiece = `-- name: ArchiveChallengePiece :one
UPDATE challenge_pieces
SET lifecycle_status = 'archived',
    archived_at = now()
WHERE id = $1
  AND lifecycle_status = 'active'
RETURNING id, workspace_id, kind, slug, name, description, definition, lifecycle_status, created_by_user_id, created_at, updated_at, archived_at
`

type ArchiveChallengePieceParams struct {
	ID uuid.UUID
}

func (q *Queries) ArchiveChallengePiece(ctx context.Context, arg ArchiveChallengePieceParams) (ChallengePiece, error) {
	row := q.db.QueryRow(ctx, archiveChallengePiece, arg.ID)
	var i ChallengePiece
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Kind,
		&i.Slug,
		&i.Name,
		&i.Description,
		&i.Definition,
		&i.LifecycleStatus,
		&i.CreatedByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ArchivedAt,
	)
	return i, err
}

const createChallengePiece = `-- name: CreateChallengePiece :one
INSERT INTO challenge_pieces (
    workspace_id,
    kind,
    slug,
    name,
    description,
    definition,
    created_by_user_id
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7
)
RETURNING id, workspace_id, kind, slug, name, description, definition, lifecycle_status, created_by_user_id, created_at, updated_at, archived_at
`

type CreateChallengePieceParams struct {
	WorkspaceID     uuid.UUID
	Kind            string
	Slug            string
	Name            string
	Description     string
	Definition      []byte
	CreatedByUserID *uuid.UUID
}

func (q *Queries) CreateChallengePiece(ctx context.Context, arg CreateChallengePieceParams) (ChallengePiece, error) {
	row := q.db.QueryRow(ctx, createChallengePiece,
		arg.WorkspaceID,
		arg.Kind,
		arg.Slug,
		arg.Name,
		arg.Description,
		arg.Definition,
		arg.CreatedByUserID,
	)
	var i ChallengePiece
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Kind,
		&i.Slug,
		&i.Name,
		&i.Description,
		&i.Definition,
		&i.LifecycleStatus,
		&i.CreatedByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ArchivedAt,
	)
	return i, err
}

const getChallengePieceByID = `-- name: GetChallengePieceByID :one
SELECT id, workspace_id, kind, slug, name, description, definition, lifecycle_status, created_by_user_id, created_at, updated_at, archived_at
FROM challenge_pieces
WHERE id = $1
LIMIT 1
`

type GetChallengePieceByIDParams struct {
	ID uuid.UUID
}

func (q *Queries) GetChallengePieceByID(ctx context.Context, arg GetChallengePieceByIDParams) (ChallengePiece, error) {
	row := q.db.QueryRow(ctx, getChallengePieceByID, arg.ID)
	var i ChallengePiece
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Kind,
		&i.Slug,
		&i.Name,
		&i.Description,
		&i.Definition,
		&i.LifecycleStatus,
		&i.CreatedByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ArchivedAt,
	)
	return i, err
}

const listChallengePiecesByIDs = `-- name: ListChallengePiecesByIDs :many
SELECT id, workspace_id, kind, slug, name, description, definition, lifecycle_status, created_by_user_id, created_at, updated_at, archived_at
FROM challenge_pieces
WHERE id = ANY ($1::uuid[])
  AND lifecycle_status = 'active'
`

type ListChallengePiecesByIDsParams struct {
	Ids []uuid.UUID
}

func (q *Queries) ListChallengePiecesByIDs(ctx context.Context, arg ListChallengePiecesByIDsParams) ([]ChallengePiece, error) {
	rows, err := q.db.Query(ctx, listChallengePiecesByIDs, arg.Ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ChallengePiece
	for rows.Next() {
		var i ChallengePiece
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.Kind,
			&i.Slug,
			&i.Name,
			&i.Description,
			&i.Definition,
			&i.LifecycleStatus,
			&i.CreatedByUserID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ArchivedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listChallengePiecesByWorkspace = `-- name: ListChallengePiecesByWorkspace :many
SELECT id, workspace_id, kind, slug, name, description, definition, lifecycle_status, created_by_user_id, created_at, updated_at, archived_at
FROM challenge_pieces
WHERE workspace_id = $1
  AND lifecycle_status = 'active'
  AND ($2::text IS NULL OR kind = $2::text)
ORDER BY created_at DESC, id DESC
`

type ListChallengePiecesByWorkspaceParams struct {
	WorkspaceID uuid.UUID
	Kind        *string
}

func (q *Queries) ListChallengePiecesByWorkspace(ctx context.Context, arg ListChallengePiecesByWorkspaceParams) ([]ChallengePiece, error) {
	rows, err := q.db.Query(ctx, listChallengePiecesByWorkspace, arg.WorkspaceID, arg.Kind)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ChallengePiece
	for rows.Next() {
		var i ChallengePiece
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.Kind,
			&i.Slug,
			&i.Name,
			&i.Description,
			&i.Definition,
			&i.LifecycleStatus,
			&i.CreatedByUserID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ArchivedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const patchChallengePiece = `-- name: PatchChallengePiece :one
UPDATE challenge_pieces
SET name = COALESCE($1, name),
    slug = COALESCE($2, slug),
    description = COALESCE($3, description),
    definition = COALESCE($4::jsonb, definition)
WHERE id = $5
  AND lifecycle_status = 'active'
RETURNING id, workspace_id, kind, slug, name, description, definition, lifecycle_status, created_by_user_id, created_at, updated_at, archived_at
`

type PatchChallengePieceParams struct {
	Name        *string
	Slug        *string
	Description *string
	Definition  []byte
	ID          uuid.UUID
}

func (q *Queries) PatchChallengePiece(ctx context.Context, arg PatchChallengePieceParams) (ChallengePiece, error) {
	row := q.db.QueryRow(ctx, patchChallengePiece,
		arg.Name,
		arg.Slug,
		arg.Description,
		arg.Definition,
		arg.ID,
	)
	var i ChallengePiece
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Kind,
		&i.Slug,
		&i.Name,
		&i.Description,
		&i.Definition,
		&i.LifecycleStatus,
		&i.CreatedByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ArchivedAt,
	)
	return i, err
}
