// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: challenge_packs.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const getWorkspaceChallengePackVersionBySlug = `-- name: GetWorkspaceChallengePackVersionBySlug :one
SELECT p.id AS challenge_pack_id, v.id AS challenge_pack_version_id
FROM challenge_packs p
JOIN challenge_pack_versions v ON v.challenge_pack_id = p.id
WHERE p.workspace_id = $1::uuid
  AND p.slug = $2
  AND p.archived_at IS NULL
  AND v.lifecycle_status = 'runnable'
  AND v.archived_at IS NULL
ORDER BY v.version_number DESC
LIMIT 1
`

type GetWorkspaceChallengePackVersionBySlugParams struct {
	WorkspaceID uuid.UUID
	Slug        string
}

type GetWorkspaceChallengePackVersionBySlugRow struct {
	ChallengePackID        uuid.UUID
	ChallengePackVersionID uuid.UUID
}

func (q *Queries) GetWorkspaceChallengePackVersionBySlug(ctx context.Context, arg GetWorkspaceChallengePackVersionBySlugParams) (GetWorkspaceChallengePackVersionBySlugRow, error) {
	row := q.db.QueryRow(ctx, getWorkspaceChallengePackVersionBySlug, arg.WorkspaceID, arg.Slug)
	var i GetWorkspaceChallengePackVersionBySlugRow
	err := row.Scan(&i.ChallengePackID, &i.ChallengePackVersionID)
	return i, err
}

const listChallengePacks = `-- name: ListChallengePacks :many
SELECT cp.id, cp.name, cp.description, cp.created_at, cp.updated_at
FROM challenge_packs cp
WHERE cp.archived_at IS NULL
ORDER BY cp.name ASC
`

type ListChallengePacksRow struct {
	ID          uuid.UUID
	Name        string
	Description *string
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
}

func (q *Queries) ListChallengePacks(ctx context.Context) ([]ListChallengePacksRow, error) {
	rows, err := q.db.Query(ctx, listChallengePacks)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListChallengePacksRow
	for rows.Next() {
		var i ListChallengePacksRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRunnableChallengePVersionsByPackID = `-- name: ListRunnableChallengePVersionsByPackID :many
SELECT id, challenge_pack_id, version_number, lifecycle_status, manifest, created_at, updated_at
FROM challenge_pack_versions
WHERE challenge_pack_id = $1
  AND lifecycle_status = 'runnable'
  AND archived_at IS NULL
ORDER BY created_at DESC
`

type ListRunnableChallengePVersionsByPackIDParams struct {
	ChallengePackID uuid.UUID
}

type ListRunnableChallengePVersionsByPackIDRow struct {
	ID              uuid.UUID
	ChallengePackID uuid.UUID
	VersionNumber   int32
	LifecycleStatus string
	Manifest        []byte
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
}

func (q *Queries) ListRunnableChallengePVersionsByPackID(ctx context.Context, arg ListRunnableChallengePVersionsByPackIDParams) ([]ListRunnableChallengePVersionsByPackIDRow, error) {
	rows, err := q.db.Query(ctx, listRunnableChallengePVersionsByPackID, arg.ChallengePackID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRunnableChallengePVersionsByPackIDRow
	for rows.Next() {
		var i ListRunnableChallengePVersionsByPackIDRow
		if err := rows.Scan(
			&i.ID,
			&i.ChallengePackID,
			&i.VersionNumber,
			&i.LifecycleStatus,
			&i.Manifest,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
