// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: hosted_runs.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const applyHostedRunEvent = `-- name: ApplyHostedRunEvent :one
UPDATE hosted_run_executions
SET status = $1,
    external_run_id = COALESCE(external_run_id, $2),
    last_event_type = $3,
    last_event_payload = $4,
    result_payload = CASE
        WHEN $5 IS NULL THEN result_payload
        ELSE $5
    END,
    error_message = CASE
        WHEN $6 IS NULL THEN error_message
        ELSE $6
    END,
    started_at = CASE
        WHEN $1 IN ('running', 'completed', 'failed') AND started_at IS NULL THEN $7
        ELSE started_at
    END,
    finished_at = CASE
        WHEN $1 IN ('completed', 'failed') AND finished_at IS NULL THEN $7
        ELSE finished_at
    END
WHERE run_agent_id = $8
RETURNING id, run_id, run_agent_id, endpoint_url, trace_level, status, external_run_id, accepted_response, last_event_type, last_event_payload, result_payload, error_message, deadline_at, accepted_at, started_at, finished_at, created_at, updated_at
`

type ApplyHostedRunEventParams struct {
	Status           string
	ExternalRunID    *string
	LastEventType    *string
	LastEventPayload []byte
	ResultPayload    []byte
	ErrorMessage     *string
	OccurredAt       pgtype.Timestamptz
	RunAgentID       uuid.UUID
}

func (q *Queries) ApplyHostedRunEvent(ctx context.Context, arg ApplyHostedRunEventParams) (HostedRunExecution, error) {
	row := q.db.QueryRow(ctx, applyHostedRunEvent,
		arg.Status,
		arg.ExternalRunID,
		arg.LastEventType,
		arg.LastEventPayload,
		arg.ResultPayload,
		arg.ErrorMessage,
		arg.OccurredAt,
		arg.RunAgentID,
	)
	var i HostedRunExecution
	err := row.Scan(
		&i.ID,
		&i.RunID,
		&i.RunAgentID,
		&i.EndpointUrl,
		&i.TraceLevel,
		&i.Status,
		&i.ExternalRunID,
		&i.AcceptedResponse,
		&i.LastEventType,
		&i.LastEventPayload,
		&i.ResultPayload,
		&i.ErrorMessage,
		&i.DeadlineAt,
		&i.AcceptedAt,
		&i.StartedAt,
		&i.FinishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createHostedRunExecution = `-- name: CreateHostedRunExecution :one
INSERT INTO hosted_run_executions (
    run_id,
    run_agent_id,
    endpoint_url,
    trace_level,
    status,
    deadline_at
)
VALUES (
    $1,
    $2,
    $3,
    $4,
    'starting',
    $5
)
ON CONFLICT (run_agent_id) DO UPDATE
SET endpoint_url = EXCLUDED.endpoint_url,
    trace_level = EXCLUDED.trace_level,
    status = EXCLUDED.status,
    external_run_id = NULL,
    accepted_response = '{}'::jsonb,
    last_event_type = NULL,
    last_event_payload = '{}'::jsonb,
    result_payload = '{}'::jsonb,
    error_message = NULL,
    deadline_at = EXCLUDED.deadline_at,
    accepted_at = NULL,
    started_at = NULL,
    finished_at = NULL
RETURNING id, run_id, run_agent_id, endpoint_url, trace_level, status, external_run_id, accepted_response, last_event_type, last_event_payload, result_payload, error_message, deadline_at, accepted_at, started_at, finished_at, created_at, updated_at
`

type CreateHostedRunExecutionParams struct {
	RunID       uuid.UUID
	RunAgentID  uuid.UUID
	EndpointUrl string
	TraceLevel  string
	DeadlineAt  pgtype.Timestamptz
}

func (q *Queries) CreateHostedRunExecution(ctx context.Context, arg CreateHostedRunExecutionParams) (HostedRunExecution, error) {
	row := q.db.QueryRow(ctx, createHostedRunExecution,
		arg.RunID,
		arg.RunAgentID,
		arg.EndpointUrl,
		arg.TraceLevel,
		arg.DeadlineAt,
	)
	var i HostedRunExecution
	err := row.Scan(
		&i.ID,
		&i.RunID,
		&i.RunAgentID,
		&i.EndpointUrl,
		&i.TraceLevel,
		&i.Status,
		&i.ExternalRunID,
		&i.AcceptedResponse,
		&i.LastEventType,
		&i.LastEventPayload,
		&i.ResultPayload,
		&i.ErrorMessage,
		&i.DeadlineAt,
		&i.AcceptedAt,
		&i.StartedAt,
		&i.FinishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getHostedRunExecutionByRunAgentID = `-- name: GetHostedRunExecutionByRunAgentID :one
SELECT id, run_id, run_agent_id, endpoint_url, trace_level, status, external_run_id, accepted_response, last_event_type, last_event_payload, result_payload, error_message, deadline_at, accepted_at, started_at, finished_at, created_at, updated_at
FROM hosted_run_executions
WHERE run_agent_id = $1
LIMIT 1
`

type GetHostedRunExecutionByRunAgentIDParams struct {
	RunAgentID uuid.UUID
}

func (q *Queries) GetHostedRunExecutionByRunAgentID(ctx context.Context, arg GetHostedRunExecutionByRunAgentIDParams) (HostedRunExecution, error) {
	row := q.db.QueryRow(ctx, getHostedRunExecutionByRunAgentID, arg.RunAgentID)
	var i HostedRunExecution
	err := row.Scan(
		&i.ID,
		&i.RunID,
		&i.RunAgentID,
		&i.EndpointUrl,
		&i.TraceLevel,
		&i.Status,
		&i.ExternalRunID,
		&i.AcceptedResponse,
		&i.LastEventType,
		&i.LastEventPayload,
		&i.ResultPayload,
		&i.ErrorMessage,
		&i.DeadlineAt,
		&i.AcceptedAt,
		&i.StartedAt,
		&i.FinishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const markHostedRunExecutionAccepted = `-- name: MarkHostedRunExecutionAccepted :one
UPDATE hosted_run_executions
SET external_run_id = $1,
    status = 'accepted',
    accepted_response = $2,
    accepted_at = COALESCE(accepted_at, now())
WHERE run_agent_id = $3
RETURNING id, run_id, run_agent_id, endpoint_url, trace_level, status, external_run_id, accepted_response, last_event_type, last_event_payload, result_payload, error_message, deadline_at, accepted_at, started_at, finished_at, created_at, updated_at
`

type MarkHostedRunExecutionAcceptedParams struct {
	ExternalRunID    *string
	AcceptedResponse []byte
	RunAgentID       uuid.UUID
}

func (q *Queries) MarkHostedRunExecutionAccepted(ctx context.Context, arg MarkHostedRunExecutionAcceptedParams) (HostedRunExecution, error) {
	row := q.db.QueryRow(ctx, markHostedRunExecutionAccepted, arg.ExternalRunID, arg.AcceptedResponse, arg.RunAgentID)
	var i HostedRunExecution
	err := row.Scan(
		&i.ID,
		&i.RunID,
		&i.RunAgentID,
		&i.EndpointUrl,
		&i.TraceLevel,
		&i.Status,
		&i.ExternalRunID,
		&i.AcceptedResponse,
		&i.LastEventType,
		&i.LastEventPayload,
		&i.ResultPayload,
		&i.ErrorMessage,
		&i.DeadlineAt,
		&i.AcceptedAt,
		&i.StartedAt,
		&i.FinishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const markHostedRunExecutionFailed = `-- name: MarkHostedRunExecutionFailed :one
UPDATE hosted_run_executions
SET status = 'failed',
    error_message = $1,
    finished_at = COALESCE(finished_at, now()),
    last_event_type = $2,
    last_event_payload = CASE
        WHEN $3 IS NULL THEN last_event_payload
        ELSE $3
    END,
    result_payload = CASE
        WHEN $4 IS NULL THEN result_payload
        ELSE $4
    END
WHERE run_agent_id = $5
RETURNING id, run_id, run_agent_id, endpoint_url, trace_level, status, external_run_id, accepted_response, last_event_type, last_event_payload, result_payload, error_message, deadline_at, accepted_at, started_at, finished_at, created_at, updated_at
`

type MarkHostedRunExecutionFailedParams struct {
	ErrorMessage     *string
	LastEventType    *string
	LastEventPayload []byte
	ResultPayload    []byte
	RunAgentID       uuid.UUID
}

func (q *Queries) MarkHostedRunExecutionFailed(ctx context.Context, arg MarkHostedRunExecutionFailedParams) (HostedRunExecution, error) {
	row := q.db.QueryRow(ctx, markHostedRunExecutionFailed,
		arg.ErrorMessage,
		arg.LastEventType,
		arg.LastEventPayload,
		arg.ResultPayload,
		arg.RunAgentID,
	)
	var i HostedRunExecution
	err := row.Scan(
		&i.ID,
		&i.RunID,
		&i.RunAgentID,
		&i.EndpointUrl,
		&i.TraceLevel,
		&i.Status,
		&i.ExternalRunID,
		&i.AcceptedResponse,
		&i.LastEventType,
		&i.LastEventPayload,
		&i.ResultPayload,
		&i.ErrorMessage,
		&i.DeadlineAt,
		&i.AcceptedAt,
		&i.StartedAt,
		&i.FinishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const markHostedRunExecutionTimedOut = `-- name: MarkHostedRunExecutionTimedOut :one
UPDATE hosted_run_executions
SET status = 'timed_out',
    error_message = $1,
    finished_at = COALESCE(finished_at, now())
WHERE run_agent_id = $2
RETURNING id, run_id, run_agent_id, endpoint_url, trace_level, status, external_run_id, accepted_response, last_event_type, last_event_payload, result_payload, error_message, deadline_at, accepted_at, started_at, finished_at, created_at, updated_at
`

type MarkHostedRunExecutionTimedOutParams struct {
	ErrorMessage *string
	RunAgentID   uuid.UUID
}

func (q *Queries) MarkHostedRunExecutionTimedOut(ctx context.Context, arg MarkHostedRunExecutionTimedOutParams) (HostedRunExecution, error) {
	row := q.db.QueryRow(ctx, markHostedRunExecutionTimedOut, arg.ErrorMessage, arg.RunAgentID)
	var i HostedRunExecution
	err := row.Scan(
		&i.ID,
		&i.RunID,
		&i.RunAgentID,
		&i.EndpointUrl,
		&i.TraceLevel,
		&i.Status,
		&i.ExternalRunID,
		&i.AcceptedResponse,
		&i.LastEventType,
		&i.LastEventPayload,
		&i.ResultPayload,
		&i.ErrorMessage,
		&i.DeadlineAt,
		&i.AcceptedAt,
		&i.StartedAt,
		&i.FinishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertRunAgentReplaySummary = `-- name: UpsertRunAgentReplaySummary :one
INSERT INTO run_agent_replays (
    run_agent_id,
    summary,
    latest_sequence_number,
    event_count
)
VALUES (
    $1,
    $2,
    $3,
    $4
)
ON CONFLICT (run_agent_id) DO UPDATE
SET summary = EXCLUDED.summary,
    latest_sequence_number = EXCLUDED.latest_sequence_number,
    event_count = EXCLUDED.event_count
RETURNING id, run_agent_id, artifact_id, summary, latest_sequence_number, event_count, created_at, updated_at
`

type UpsertRunAgentReplaySummaryParams struct {
	RunAgentID           uuid.UUID
	Summary              []byte
	LatestSequenceNumber *int64
	EventCount           int64
}

func (q *Queries) UpsertRunAgentReplaySummary(ctx context.Context, arg UpsertRunAgentReplaySummaryParams) (RunAgentReplay, error) {
	row := q.db.QueryRow(ctx, upsertRunAgentReplaySummary,
		arg.RunAgentID,
		arg.Summary,
		arg.LatestSequenceNumber,
		arg.EventCount,
	)
	var i RunAgentReplay
	err := row.Scan(
		&i.ID,
		&i.RunAgentID,
		&i.ArtifactID,
		&i.Summary,
		&i.LatestSequenceNumber,
		&i.EventCount,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
