// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type ChallengeInputSet struct {
	ID                     uuid.UUID
	ChallengePackVersionID uuid.UUID
	InputKey               string
	Name                   string
	Description            *string
	InputChecksum          string
	GeneratedAt            pgtype.Timestamptz
	CreatedAt              pgtype.Timestamptz
	UpdatedAt              pgtype.Timestamptz
	ArchivedAt             pgtype.Timestamptz
}

type ChallengePackVersion struct {
	ID               uuid.UUID
	ChallengePackID  uuid.UUID
	VersionNumber    int32
	LifecycleStatus  string
	ManifestChecksum string
	Manifest         []byte
	PublishedAt      pgtype.Timestamptz
	CreatedAt        pgtype.Timestamptz
	UpdatedAt        pgtype.Timestamptz
	ArchivedAt       pgtype.Timestamptz
}

type EvaluationSpec struct {
	ID                     uuid.UUID
	ChallengePackVersionID *uuid.UUID
	Name                   string
	VersionNumber          int32
	JudgeMode              string
	Definition             []byte
	CreatedAt              pgtype.Timestamptz
	UpdatedAt              pgtype.Timestamptz
}

type HostedRunExecution struct {
	ID               uuid.UUID
	RunID            uuid.UUID
	RunAgentID       uuid.UUID
	EndpointUrl      string
	TraceLevel       string
	Status           string
	ExternalRunID    *string
	AcceptedResponse []byte
	LastEventType    *string
	LastEventPayload []byte
	ResultPayload    []byte
	ErrorMessage     *string
	DeadlineAt       pgtype.Timestamptz
	AcceptedAt       pgtype.Timestamptz
	StartedAt        pgtype.Timestamptz
	FinishedAt       pgtype.Timestamptz
	CreatedAt        pgtype.Timestamptz
	UpdatedAt        pgtype.Timestamptz
}

type JudgeResult struct {
	ID                  uuid.UUID
	RunAgentID          uuid.UUID
	EvaluationSpecID    uuid.UUID
	ChallengeIdentityID *uuid.UUID
	JudgeKey            string
	Verdict             *string
	NormalizedScore     pgtype.Numeric
	RawOutput           []byte
	CreatedAt           pgtype.Timestamptz
}

type MetricResult struct {
	ID                  uuid.UUID
	RunAgentID          uuid.UUID
	EvaluationSpecID    uuid.UUID
	ChallengeIdentityID *uuid.UUID
	MetricKey           string
	MetricType          string
	NumericValue        pgtype.Numeric
	TextValue           *string
	BooleanValue        *bool
	Unit                *string
	Metadata            []byte
	CreatedAt           pgtype.Timestamptz
}

type Run struct {
	ID                     uuid.UUID
	OrganizationID         uuid.UUID
	WorkspaceID            uuid.UUID
	ChallengePackVersionID uuid.UUID
	ChallengeInputSetID    *uuid.UUID
	CreatedByUserID        *uuid.UUID
	Name                   string
	Status                 string
	ExecutionMode          string
	TemporalWorkflowID     *string
	TemporalRunID          *string
	ExecutionPlan          []byte
	QueuedAt               pgtype.Timestamptz
	StartedAt              pgtype.Timestamptz
	FinishedAt             pgtype.Timestamptz
	CancelledAt            pgtype.Timestamptz
	FailedAt               pgtype.Timestamptz
	CreatedAt              pgtype.Timestamptz
	UpdatedAt              pgtype.Timestamptz
}

type RunAgent struct {
	ID                        uuid.UUID
	OrganizationID            uuid.UUID
	WorkspaceID               uuid.UUID
	RunID                     uuid.UUID
	AgentDeploymentID         uuid.UUID
	AgentDeploymentSnapshotID uuid.UUID
	LaneIndex                 int32
	Label                     string
	Status                    string
	QueuedAt                  pgtype.Timestamptz
	StartedAt                 pgtype.Timestamptz
	FinishedAt                pgtype.Timestamptz
	FailureReason             *string
	CreatedAt                 pgtype.Timestamptz
	UpdatedAt                 pgtype.Timestamptz
}

type RunAgentReplay struct {
	ID                   uuid.UUID
	RunAgentID           uuid.UUID
	ArtifactID           *uuid.UUID
	Summary              []byte
	LatestSequenceNumber *int64
	EventCount           int64
	CreatedAt            pgtype.Timestamptz
	UpdatedAt            pgtype.Timestamptz
}

type RunAgentScorecard struct {
	ID               uuid.UUID
	RunAgentID       uuid.UUID
	EvaluationSpecID uuid.UUID
	OverallScore     pgtype.Numeric
	CorrectnessScore pgtype.Numeric
	ReliabilityScore pgtype.Numeric
	LatencyScore     pgtype.Numeric
	CostScore        pgtype.Numeric
	Scorecard        []byte
	CreatedAt        pgtype.Timestamptz
	UpdatedAt        pgtype.Timestamptz
}

type RunAgentStatusHistory struct {
	ID         uuid.UUID
	RunAgentID uuid.UUID
	FromStatus *string
	ToStatus   string
	Reason     *string
	ChangedAt  pgtype.Timestamptz
}

type RunEvent struct {
	ID             int64
	RunID          uuid.UUID
	RunAgentID     uuid.UUID
	SequenceNumber int64
	EventType      string
	ActorType      string
	OccurredAt     pgtype.Timestamptz
	ArtifactID     *uuid.UUID
	Payload        []byte
}

type RunStatusHistory struct {
	ID              uuid.UUID
	RunID           uuid.UUID
	FromStatus      *string
	ToStatus        string
	Reason          *string
	ChangedByUserID *uuid.UUID
	ChangedAt       pgtype.Timestamptz
}
