// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package sqlc

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type AgentBuild struct {
	ID              uuid.UUID
	OrganizationID  uuid.UUID
	WorkspaceID     uuid.UUID
	Name            string
	Slug            string
	Description     *string
	BuildKind       string
	LifecycleStatus string
	CreatedByUserID *uuid.UUID
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
	ArchivedAt      pgtype.Timestamptz
}

type AgentBuildVersion struct {
	ID              uuid.UUID
	AgentBuildID    uuid.UUID
	VersionNumber   int32
	VersionStatus   string
	BuildDefinition []byte
	PromptSpec      *string
	OutputSchema    []byte
	TraceContract   []byte
	CreatedByUserID *uuid.UUID
	CreatedAt       pgtype.Timestamptz
	AgentKind       string
	InterfaceSpec   []byte
	PolicySpec      []byte
	ReasoningSpec   []byte
	MemorySpec      []byte
	WorkflowSpec    []byte
	GuardrailSpec   []byte
	ModelSpec       []byte
	PublicationSpec []byte
}

type AgentDeployment struct {
	ID                    uuid.UUID
	OrganizationID        uuid.UUID
	WorkspaceID           uuid.UUID
	AgentBuildID          uuid.UUID
	CurrentBuildVersionID uuid.UUID
	RuntimeProfileID      uuid.UUID
	ProviderAccountID     *uuid.UUID
	ModelAliasID          *uuid.UUID
	RoutingPolicyID       *uuid.UUID
	SpendPolicyID         *uuid.UUID
	Name                  string
	Slug                  string
	DeploymentType        string
	EndpointUrl           *string
	HealthcheckUrl        *string
	Status                string
	DeploymentConfig      []byte
	CreatedAt             pgtype.Timestamptz
	UpdatedAt             pgtype.Timestamptz
	ArchivedAt            pgtype.Timestamptz
}

type BillingAccount struct {
	ID             uuid.UUID
	OrganizationID uuid.UUID
	DodoCustomerID *string
	BillingEmail   *string
	Status         string
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
}

type BillingSubscription struct {
	ID                      uuid.UUID
	OrganizationID          uuid.UUID
	DodoSubscriptionID      string
	DodoCustomerID          *string
	DodoProductID           string
	PlanKey                 string
	BillingPeriod           string
	Status                  string
	NextBillingDate         pgtype.Timestamptz
	CancelAtNextBillingDate bool
	CancelledAt             pgtype.Timestamptz
	ExpiresAt               pgtype.Timestamptz
	TrialPeriodDays         *int32
	SeatQuantity            int32
	AddonQuantities         []byte
	LatestDodoEventAt       pgtype.Timestamptz
	CreatedAt               pgtype.Timestamptz
	UpdatedAt               pgtype.Timestamptz
}

type BillingTrialGrant struct {
	ID              uuid.UUID
	OrganizationID  uuid.UUID
	PlanKey         string
	BillingPeriod   string
	StartedByUserID *uuid.UUID
	StartedAt       pgtype.Timestamptz
	ExpiresAt       pgtype.Timestamptz
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
}

type ChallengeInputItem struct {
	ID                     uuid.UUID
	ChallengeInputSetID    uuid.UUID
	ChallengePackVersionID uuid.UUID
	ChallengeIdentityID    uuid.UUID
	ItemKey                string
	Payload                []byte
	CreatedAt              pgtype.Timestamptz
}

type ChallengeInputSet struct {
	ID                     uuid.UUID
	ChallengePackVersionID uuid.UUID
	InputKey               string
	Name                   string
	Description            *string
	InputChecksum          string
	GeneratedAt            pgtype.Timestamptz
	CreatedAt              pgtype.Timestamptz
	UpdatedAt              pgtype.Timestamptz
	ArchivedAt             pgtype.Timestamptz
}

type ChallengePackVersion struct {
	ID               uuid.UUID
	ChallengePackID  uuid.UUID
	VersionNumber    int32
	LifecycleStatus  string
	ManifestChecksum string
	Manifest         []byte
	PublishedAt      pgtype.Timestamptz
	CreatedAt        pgtype.Timestamptz
	UpdatedAt        pgtype.Timestamptz
	ArchivedAt       pgtype.Timestamptz
}

type Dataset struct {
	ID                            uuid.UUID
	OrganizationID                uuid.UUID
	WorkspaceID                   uuid.UUID
	Slug                          string
	Name                          string
	Description                   string
	InputSchema                   []byte
	InputSchemaEnforced           bool
	DefaultChallengePackVersionID *uuid.UUID
	CreatedBy                     uuid.UUID
	CreatedAt                     pgtype.Timestamptz
	UpdatedAt                     pgtype.Timestamptz
	ArchivedAt                    pgtype.Timestamptz
}

type DatasetBaseline struct {
	ID                       uuid.UUID
	DatasetID                uuid.UUID
	DatasetVersionID         uuid.UUID
	DatasetVersionInputSetID *uuid.UUID
	ChallengePackVersionID   uuid.UUID
	ChallengeKey             string
	AgentDeploymentID        *uuid.UUID
	RunID                    uuid.UUID
	PassRate                 pgtype.Numeric
	Metrics                  []byte
	ExampleOutcomes          []byte
	Label                    *string
	CreatedByUserID          uuid.UUID
	CreatedAt                pgtype.Timestamptz
}

type DatasetEvalRun struct {
	ID                       uuid.UUID
	DatasetID                uuid.UUID
	DatasetVersionID         uuid.UUID
	DatasetVersionInputSetID uuid.UUID
	RunID                    uuid.UUID
	CreatedAt                pgtype.Timestamptz
}

type DatasetExample struct {
	ID             uuid.UUID
	DatasetID      uuid.UUID
	ExternalID     *string
	Input          []byte
	Expected       []byte
	Metadata       []byte
	Tags           []string
	Status         string
	Source         string
	SourceRunID    *uuid.UUID
	SourceTraceID  *string
	SourcePlatform *string
	ArtifactID     *uuid.UUID
	CreatedBy      uuid.UUID
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
}

type DatasetExampleRevision struct {
	ID        uuid.UUID
	DatasetID uuid.UUID
	ExampleID *uuid.UUID
	VersionID *uuid.UUID
	Operation string
	Before    []byte
	After     []byte
	Actor     uuid.UUID
	CreatedAt pgtype.Timestamptz
}

type DatasetInputItemLink struct {
	ID                       uuid.UUID
	DatasetVersionInputSetID uuid.UUID
	DatasetExampleID         uuid.UUID
	ChallengeInputItemID     uuid.UUID
	ItemKey                  string
	CreatedAt                pgtype.Timestamptz
}

type DatasetRegressionSuiteLink struct {
	DatasetID         uuid.UUID
	RegressionSuiteID uuid.UUID
	SyncedVersionID   *uuid.UUID
	CreatedAt         pgtype.Timestamptz
	UpdatedAt         pgtype.Timestamptz
}

type DatasetTraceCandidate struct {
	ID                uuid.UUID
	DatasetID         uuid.UUID
	ImportID          uuid.UUID
	SourcePlatform    string
	SourceTraceID     *string
	SourceRunID       *uuid.UUID
	SourceRunAgentID  *uuid.UUID
	ExternalID        *string
	Input             []byte
	Output            []byte
	Expected          []byte
	Metadata          []byte
	Tags              []string
	Status            string
	PromotedExampleID *uuid.UUID
	CreatedAt         pgtype.Timestamptz
	UpdatedAt         pgtype.Timestamptz
}

type DatasetTraceImport struct {
	ID             uuid.UUID
	DatasetID      uuid.UUID
	SourcePlatform string
	ArtifactID     *uuid.UUID
	CandidateCount int32
	Status         string
	CreatedBy      uuid.UUID
	CreatedAt      pgtype.Timestamptz
}

type DatasetVersion struct {
	ID               uuid.UUID
	DatasetID        uuid.UUID
	VersionNumber    int32
	Label            *string
	ExampleCount     int32
	ManifestChecksum string
	CreatedBy        uuid.UUID
	CreatedAt        pgtype.Timestamptz
}

type DatasetVersionInputSet struct {
	ID                     uuid.UUID
	DatasetID              uuid.UUID
	DatasetVersionID       uuid.UUID
	ChallengePackVersionID uuid.UUID
	ChallengeIdentityID    uuid.UUID
	ChallengeKey           string
	ChallengeInputSetID    uuid.UUID
	InputKey               string
	InputChecksum          string
	Mapping                []byte
	CreatedAt              pgtype.Timestamptz
	UpdatedAt              pgtype.Timestamptz
}

type EvalSession struct {
	ID                     uuid.UUID
	Status                 string
	Repetitions            int32
	AggregationConfig      []byte
	SuccessThresholdConfig []byte
	RoutingTaskSnapshot    []byte
	SchemaVersion          int32
	CreatedAt              pgtype.Timestamptz
	StartedAt              pgtype.Timestamptz
	FinishedAt             pgtype.Timestamptz
	UpdatedAt              pgtype.Timestamptz
}

type EvalSessionResult struct {
	ID               uuid.UUID
	EvalSessionID    uuid.UUID
	SchemaVersion    int32
	ChildRunCount    int32
	ScoredChildCount int32
	Aggregate        []byte
	Evidence         []byte
	ComputedAt       pgtype.Timestamptz
	CreatedAt        pgtype.Timestamptz
	UpdatedAt        pgtype.Timestamptz
}

type EvaluationSpec struct {
	ID                     uuid.UUID
	ChallengePackVersionID *uuid.UUID
	Name                   string
	VersionNumber          int32
	JudgeMode              string
	Definition             []byte
	CreatedAt              pgtype.Timestamptz
	UpdatedAt              pgtype.Timestamptz
}

type HostedRunExecution struct {
	ID               uuid.UUID
	RunID            uuid.UUID
	RunAgentID       uuid.UUID
	EndpointUrl      string
	TraceLevel       string
	Status           string
	ExternalRunID    *string
	AcceptedResponse []byte
	LastEventType    *string
	LastEventPayload []byte
	ResultPayload    []byte
	ErrorMessage     *string
	DeadlineAt       pgtype.Timestamptz
	AcceptedAt       pgtype.Timestamptz
	StartedAt        pgtype.Timestamptz
	FinishedAt       pgtype.Timestamptz
	CreatedAt        pgtype.Timestamptz
	UpdatedAt        pgtype.Timestamptz
}

type LlmJudgeResult struct {
	ID               uuid.UUID
	RunAgentID       uuid.UUID
	EvaluationSpecID uuid.UUID
	JudgeKey         string
	Mode             string
	NormalizedScore  pgtype.Numeric
	Payload          []byte
	Confidence       *string
	Variance         pgtype.Numeric
	SampleCount      int32
	ModelCount       int32
	CreatedAt        pgtype.Timestamptz
	UpdatedAt        pgtype.Timestamptz
}

type Playground struct {
	ID              uuid.UUID
	OrganizationID  uuid.UUID
	WorkspaceID     uuid.UUID
	Name            string
	PromptTemplate  string
	SystemPrompt    string
	EvaluationSpec  []byte
	CreatedByUserID *uuid.UUID
	UpdatedByUserID *uuid.UUID
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
}

type PlaygroundExperiment struct {
	ID                 uuid.UUID
	OrganizationID     uuid.UUID
	WorkspaceID        uuid.UUID
	PlaygroundID       uuid.UUID
	ProviderAccountID  uuid.UUID
	ModelAliasID       uuid.UUID
	Name               string
	Status             string
	RequestConfig      []byte
	Summary            []byte
	TemporalWorkflowID *string
	TemporalRunID      *string
	QueuedAt           pgtype.Timestamptz
	StartedAt          pgtype.Timestamptz
	FinishedAt         pgtype.Timestamptz
	FailedAt           pgtype.Timestamptz
	CreatedByUserID    *uuid.UUID
	CreatedAt          pgtype.Timestamptz
	UpdatedAt          pgtype.Timestamptz
}

type PlaygroundExperimentResult struct {
	ID                     uuid.UUID
	PlaygroundExperimentID uuid.UUID
	PlaygroundTestCaseID   uuid.UUID
	CaseKey                string
	Status                 string
	Variables              []byte
	Expectations           []byte
	RenderedPrompt         string
	ActualOutput           string
	ProviderKey            string
	ProviderModelID        string
	InputTokens            int64
	OutputTokens           int64
	TotalTokens            int64
	LatencyMs              int64
	CostUsd                pgtype.Numeric
	ValidatorResults       []byte
	LlmJudgeResults        []byte
	DimensionResults       []byte
	DimensionScores        []byte
	Warnings               []byte
	ErrorMessage           *string
	CreatedAt              pgtype.Timestamptz
	UpdatedAt              pgtype.Timestamptz
}

type PlaygroundTestCase struct {
	ID           uuid.UUID
	PlaygroundID uuid.UUID
	CaseKey      string
	Variables    []byte
	Expectations []byte
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
}

type Run struct {
	ID                     uuid.UUID
	OrganizationID         uuid.UUID
	WorkspaceID            uuid.UUID
	ChallengePackVersionID *uuid.UUID
	ChallengeInputSetID    *uuid.UUID
	CreatedByUserID        *uuid.UUID
	Name                   string
	Status                 string
	ExecutionMode          string
	TemporalWorkflowID     *string
	TemporalRunID          *string
	ExecutionPlan          []byte
	QueuedAt               pgtype.Timestamptz
	StartedAt              pgtype.Timestamptz
	FinishedAt             pgtype.Timestamptz
	CancelledAt            pgtype.Timestamptz
	FailedAt               pgtype.Timestamptz
	CreatedAt              pgtype.Timestamptz
	UpdatedAt              pgtype.Timestamptz
	OfficialPackMode       string
	EvalSessionID          *uuid.UUID
	RaceContext            bool
	RaceContextMinStepGap  *int32
	CiMetadata             []byte
	SourceType             string
}

type RunAgent struct {
	ID                        uuid.UUID
	OrganizationID            uuid.UUID
	WorkspaceID               uuid.UUID
	RunID                     uuid.UUID
	AgentDeploymentID         *uuid.UUID
	AgentDeploymentSnapshotID *uuid.UUID
	LaneIndex                 int32
	Label                     string
	Status                    string
	QueuedAt                  pgtype.Timestamptz
	StartedAt                 pgtype.Timestamptz
	FinishedAt                pgtype.Timestamptz
	FailureReason             *string
	CreatedAt                 pgtype.Timestamptz
	UpdatedAt                 pgtype.Timestamptz
	SourceType                string
}

type RunAgentReplay struct {
	ID                   uuid.UUID
	RunAgentID           uuid.UUID
	ArtifactID           *uuid.UUID
	Summary              []byte
	LatestSequenceNumber *int64
	EventCount           int64
	CreatedAt            pgtype.Timestamptz
	UpdatedAt            pgtype.Timestamptz
}

type RunAgentStatusHistory struct {
	ID         uuid.UUID
	RunAgentID uuid.UUID
	FromStatus *string
	ToStatus   string
	Reason     *string
	ChangedAt  pgtype.Timestamptz
}

type RunCaseSelection struct {
	ID                  uuid.UUID
	RunID               uuid.UUID
	ChallengeIdentityID uuid.UUID
	SelectionOrigin     string
	RegressionCaseID    *uuid.UUID
	SelectionRank       int32
	CreatedAt           pgtype.Timestamptz
}

type RunComparison struct {
	ID                  uuid.UUID
	BaselineRunID       uuid.UUID
	CandidateRunID      uuid.UUID
	BaselineRunAgentID  *uuid.UUID
	CandidateRunAgentID *uuid.UUID
	Status              string
	ReasonCode          *string
	SourceFingerprint   string
	Summary             []byte
	CreatedAt           pgtype.Timestamptz
	UpdatedAt           pgtype.Timestamptz
}

type RunEvent struct {
	ID             int64
	RunID          uuid.UUID
	RunAgentID     uuid.UUID
	SequenceNumber int64
	EventType      string
	ActorType      string
	OccurredAt     pgtype.Timestamptz
	ArtifactID     *uuid.UUID
	Payload        []byte
}

type RunScorecard struct {
	ID                uuid.UUID
	RunID             uuid.UUID
	EvaluationSpecID  uuid.UUID
	WinningRunAgentID *uuid.UUID
	Scorecard         []byte
	CreatedAt         pgtype.Timestamptz
	UpdatedAt         pgtype.Timestamptz
}

type RunStatusHistory struct {
	ID              uuid.UUID
	RunID           uuid.UUID
	FromStatus      *string
	ToStatus        string
	Reason          *string
	ChangedByUserID *uuid.UUID
	ChangedAt       pgtype.Timestamptz
}

type VibeEvalConversation struct {
	ID              uuid.UUID
	OrganizationID  uuid.UUID
	WorkspaceID     uuid.UUID
	CreatedByUserID uuid.UUID
	Title           string
	Phase           string
	Status          string
	ActiveDraftID   *uuid.UUID
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
	ArchivedAt      pgtype.Timestamptz
}

type VibeEvalDraft struct {
	ID                              uuid.UUID
	OrganizationID                  uuid.UUID
	WorkspaceID                     uuid.UUID
	ConversationID                  uuid.UUID
	DraftKind                       string
	Content                         []byte
	ValidationState                 string
	ValidationErrors                []byte
	PublishedChallengePackID        *uuid.UUID
	PublishedChallengePackVersionID *uuid.UUID
	CreatedByUserID                 uuid.UUID
	UpdatedByUserID                 uuid.UUID
	CreatedAt                       pgtype.Timestamptz
	UpdatedAt                       pgtype.Timestamptz
}

type WorkspaceRegressionCase struct {
	ID                           uuid.UUID
	SuiteID                      uuid.UUID
	Title                        string
	Description                  string
	Status                       string
	Severity                     string
	PromotionMode                string
	SourceRunID                  *uuid.UUID
	SourceRunAgentID             *uuid.UUID
	SourceReplayID               *uuid.UUID
	SourceChallengePackVersionID uuid.UUID
	SourceChallengeInputSetID    *uuid.UUID
	SourceChallengeIdentityID    uuid.UUID
	SourceCaseKey                string
	SourceItemKey                *string
	EvidenceTier                 string
	FailureClass                 string
	FailureSummary               string
	PayloadSnapshot              []byte
	ExpectedContract             []byte
	ValidatorOverrides           []byte
	Metadata                     []byte
	CreatedAt                    pgtype.Timestamptz
	UpdatedAt                    pgtype.Timestamptz
}

type WorkspaceRegressionPromotion struct {
	ID                        uuid.UUID
	WorkspaceRegressionCaseID uuid.UUID
	SourceRunID               uuid.UUID
	SourceRunAgentID          uuid.UUID
	SourceEventRefs           []byte
	PromotedByUserID          uuid.UUID
	PromotionReason           string
	PromotionSnapshot         []byte
	CreatedAt                 pgtype.Timestamptz
}

type WorkspaceRegressionSuite struct {
	ID                    uuid.UUID
	WorkspaceID           uuid.UUID
	SourceChallengePackID uuid.UUID
	Name                  string
	Description           string
	Status                string
	SourceMode            string
	DefaultGateSeverity   string
	CreatedByUserID       uuid.UUID
	CreatedAt             pgtype.Timestamptz
	UpdatedAt             pgtype.Timestamptz
}
