// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: playgrounds.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createPlayground = `-- name: CreatePlayground :one
INSERT INTO playgrounds (
    organization_id,
    workspace_id,
    name,
    prompt_template,
    system_prompt,
    evaluation_spec,
    created_by_user_id,
    updated_by_user_id
)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8
)
RETURNING id, organization_id, workspace_id, name, prompt_template, system_prompt, evaluation_spec, created_by_user_id, updated_by_user_id, created_at, updated_at
`

type CreatePlaygroundParams struct {
	OrganizationID  uuid.UUID
	WorkspaceID     uuid.UUID
	Name            string
	PromptTemplate  string
	SystemPrompt    string
	EvaluationSpec  []byte
	CreatedByUserID *uuid.UUID
	UpdatedByUserID *uuid.UUID
}

func (q *Queries) CreatePlayground(ctx context.Context, arg CreatePlaygroundParams) (Playground, error) {
	row := q.db.QueryRow(ctx, createPlayground,
		arg.OrganizationID,
		arg.WorkspaceID,
		arg.Name,
		arg.PromptTemplate,
		arg.SystemPrompt,
		arg.EvaluationSpec,
		arg.CreatedByUserID,
		arg.UpdatedByUserID,
	)
	var i Playground
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.WorkspaceID,
		&i.Name,
		&i.PromptTemplate,
		&i.SystemPrompt,
		&i.EvaluationSpec,
		&i.CreatedByUserID,
		&i.UpdatedByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createPlaygroundExperiment = `-- name: CreatePlaygroundExperiment :one
INSERT INTO playground_experiments (
    organization_id,
    workspace_id,
    playground_id,
    provider_account_id,
    model_alias_id,
    name,
    status,
    request_config,
    summary,
    queued_at,
    created_by_user_id
)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9,
    $10,
    $11
)
RETURNING id, organization_id, workspace_id, playground_id, provider_account_id, model_alias_id, name, status, request_config, summary, temporal_workflow_id, temporal_run_id, queued_at, started_at, finished_at, failed_at, created_by_user_id, created_at, updated_at
`

type CreatePlaygroundExperimentParams struct {
	OrganizationID    uuid.UUID
	WorkspaceID       uuid.UUID
	PlaygroundID      uuid.UUID
	ProviderAccountID uuid.UUID
	ModelAliasID      uuid.UUID
	Name              string
	Status            string
	RequestConfig     []byte
	Summary           []byte
	QueuedAt          pgtype.Timestamptz
	CreatedByUserID   *uuid.UUID
}

func (q *Queries) CreatePlaygroundExperiment(ctx context.Context, arg CreatePlaygroundExperimentParams) (PlaygroundExperiment, error) {
	row := q.db.QueryRow(ctx, createPlaygroundExperiment,
		arg.OrganizationID,
		arg.WorkspaceID,
		arg.PlaygroundID,
		arg.ProviderAccountID,
		arg.ModelAliasID,
		arg.Name,
		arg.Status,
		arg.RequestConfig,
		arg.Summary,
		arg.QueuedAt,
		arg.CreatedByUserID,
	)
	var i PlaygroundExperiment
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.WorkspaceID,
		&i.PlaygroundID,
		&i.ProviderAccountID,
		&i.ModelAliasID,
		&i.Name,
		&i.Status,
		&i.RequestConfig,
		&i.Summary,
		&i.TemporalWorkflowID,
		&i.TemporalRunID,
		&i.QueuedAt,
		&i.StartedAt,
		&i.FinishedAt,
		&i.FailedAt,
		&i.CreatedByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createPlaygroundTestCase = `-- name: CreatePlaygroundTestCase :one
INSERT INTO playground_test_cases (
    playground_id,
    case_key,
    variables,
    expectations
)
VALUES (
    $1,
    $2,
    $3,
    $4
)
RETURNING id, playground_id, case_key, variables, expectations, created_at, updated_at
`

type CreatePlaygroundTestCaseParams struct {
	PlaygroundID uuid.UUID
	CaseKey      string
	Variables    []byte
	Expectations []byte
}

func (q *Queries) CreatePlaygroundTestCase(ctx context.Context, arg CreatePlaygroundTestCaseParams) (PlaygroundTestCase, error) {
	row := q.db.QueryRow(ctx, createPlaygroundTestCase,
		arg.PlaygroundID,
		arg.CaseKey,
		arg.Variables,
		arg.Expectations,
	)
	var i PlaygroundTestCase
	err := row.Scan(
		&i.ID,
		&i.PlaygroundID,
		&i.CaseKey,
		&i.Variables,
		&i.Expectations,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deletePlayground = `-- name: DeletePlayground :exec
DELETE FROM playgrounds
WHERE id = $1
`

type DeletePlaygroundParams struct {
	ID uuid.UUID
}

func (q *Queries) DeletePlayground(ctx context.Context, arg DeletePlaygroundParams) error {
	_, err := q.db.Exec(ctx, deletePlayground, arg.ID)
	return err
}

const deletePlaygroundTestCase = `-- name: DeletePlaygroundTestCase :exec
DELETE FROM playground_test_cases
WHERE id = $1
`

type DeletePlaygroundTestCaseParams struct {
	ID uuid.UUID
}

func (q *Queries) DeletePlaygroundTestCase(ctx context.Context, arg DeletePlaygroundTestCaseParams) error {
	_, err := q.db.Exec(ctx, deletePlaygroundTestCase, arg.ID)
	return err
}

const getPlaygroundByID = `-- name: GetPlaygroundByID :one
SELECT id, organization_id, workspace_id, name, prompt_template, system_prompt, evaluation_spec, created_by_user_id, updated_by_user_id, created_at, updated_at
FROM playgrounds
WHERE id = $1
LIMIT 1
`

type GetPlaygroundByIDParams struct {
	ID uuid.UUID
}

func (q *Queries) GetPlaygroundByID(ctx context.Context, arg GetPlaygroundByIDParams) (Playground, error) {
	row := q.db.QueryRow(ctx, getPlaygroundByID, arg.ID)
	var i Playground
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.WorkspaceID,
		&i.Name,
		&i.PromptTemplate,
		&i.SystemPrompt,
		&i.EvaluationSpec,
		&i.CreatedByUserID,
		&i.UpdatedByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPlaygroundExperimentByID = `-- name: GetPlaygroundExperimentByID :one
SELECT id, organization_id, workspace_id, playground_id, provider_account_id, model_alias_id, name, status, request_config, summary, temporal_workflow_id, temporal_run_id, queued_at, started_at, finished_at, failed_at, created_by_user_id, created_at, updated_at
FROM playground_experiments
WHERE id = $1
LIMIT 1
`

type GetPlaygroundExperimentByIDParams struct {
	ID uuid.UUID
}

func (q *Queries) GetPlaygroundExperimentByID(ctx context.Context, arg GetPlaygroundExperimentByIDParams) (PlaygroundExperiment, error) {
	row := q.db.QueryRow(ctx, getPlaygroundExperimentByID, arg.ID)
	var i PlaygroundExperiment
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.WorkspaceID,
		&i.PlaygroundID,
		&i.ProviderAccountID,
		&i.ModelAliasID,
		&i.Name,
		&i.Status,
		&i.RequestConfig,
		&i.Summary,
		&i.TemporalWorkflowID,
		&i.TemporalRunID,
		&i.QueuedAt,
		&i.StartedAt,
		&i.FinishedAt,
		&i.FailedAt,
		&i.CreatedByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPlaygroundTestCaseByID = `-- name: GetPlaygroundTestCaseByID :one
SELECT id, playground_id, case_key, variables, expectations, created_at, updated_at
FROM playground_test_cases
WHERE id = $1
LIMIT 1
`

type GetPlaygroundTestCaseByIDParams struct {
	ID uuid.UUID
}

func (q *Queries) GetPlaygroundTestCaseByID(ctx context.Context, arg GetPlaygroundTestCaseByIDParams) (PlaygroundTestCase, error) {
	row := q.db.QueryRow(ctx, getPlaygroundTestCaseByID, arg.ID)
	var i PlaygroundTestCase
	err := row.Scan(
		&i.ID,
		&i.PlaygroundID,
		&i.CaseKey,
		&i.Variables,
		&i.Expectations,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listPlaygroundExperimentResultsByExperimentID = `-- name: ListPlaygroundExperimentResultsByExperimentID :many
SELECT id, playground_experiment_id, playground_test_case_id, case_key, status, variables, expectations, rendered_prompt, actual_output, provider_key, provider_model_id, input_tokens, output_tokens, total_tokens, latency_ms, cost_usd, validator_results, llm_judge_results, dimension_results, dimension_scores, warnings, error_message, created_at, updated_at
FROM playground_experiment_results
WHERE playground_experiment_id = $1
ORDER BY case_key
`

type ListPlaygroundExperimentResultsByExperimentIDParams struct {
	PlaygroundExperimentID uuid.UUID
}

func (q *Queries) ListPlaygroundExperimentResultsByExperimentID(ctx context.Context, arg ListPlaygroundExperimentResultsByExperimentIDParams) ([]PlaygroundExperimentResult, error) {
	rows, err := q.db.Query(ctx, listPlaygroundExperimentResultsByExperimentID, arg.PlaygroundExperimentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PlaygroundExperimentResult
	for rows.Next() {
		var i PlaygroundExperimentResult
		if err := rows.Scan(
			&i.ID,
			&i.PlaygroundExperimentID,
			&i.PlaygroundTestCaseID,
			&i.CaseKey,
			&i.Status,
			&i.Variables,
			&i.Expectations,
			&i.RenderedPrompt,
			&i.ActualOutput,
			&i.ProviderKey,
			&i.ProviderModelID,
			&i.InputTokens,
			&i.OutputTokens,
			&i.TotalTokens,
			&i.LatencyMs,
			&i.CostUsd,
			&i.ValidatorResults,
			&i.LlmJudgeResults,
			&i.DimensionResults,
			&i.DimensionScores,
			&i.Warnings,
			&i.ErrorMessage,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPlaygroundExperimentsByPlaygroundID = `-- name: ListPlaygroundExperimentsByPlaygroundID :many
SELECT id, organization_id, workspace_id, playground_id, provider_account_id, model_alias_id, name, status, request_config, summary, temporal_workflow_id, temporal_run_id, queued_at, started_at, finished_at, failed_at, created_by_user_id, created_at, updated_at
FROM playground_experiments
WHERE playground_id = $1
ORDER BY created_at DESC
`

type ListPlaygroundExperimentsByPlaygroundIDParams struct {
	PlaygroundID uuid.UUID
}

func (q *Queries) ListPlaygroundExperimentsByPlaygroundID(ctx context.Context, arg ListPlaygroundExperimentsByPlaygroundIDParams) ([]PlaygroundExperiment, error) {
	rows, err := q.db.Query(ctx, listPlaygroundExperimentsByPlaygroundID, arg.PlaygroundID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PlaygroundExperiment
	for rows.Next() {
		var i PlaygroundExperiment
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.WorkspaceID,
			&i.PlaygroundID,
			&i.ProviderAccountID,
			&i.ModelAliasID,
			&i.Name,
			&i.Status,
			&i.RequestConfig,
			&i.Summary,
			&i.TemporalWorkflowID,
			&i.TemporalRunID,
			&i.QueuedAt,
			&i.StartedAt,
			&i.FinishedAt,
			&i.FailedAt,
			&i.CreatedByUserID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPlaygroundTestCasesByPlaygroundID = `-- name: ListPlaygroundTestCasesByPlaygroundID :many
SELECT id, playground_id, case_key, variables, expectations, created_at, updated_at
FROM playground_test_cases
WHERE playground_id = $1
ORDER BY case_key
`

type ListPlaygroundTestCasesByPlaygroundIDParams struct {
	PlaygroundID uuid.UUID
}

func (q *Queries) ListPlaygroundTestCasesByPlaygroundID(ctx context.Context, arg ListPlaygroundTestCasesByPlaygroundIDParams) ([]PlaygroundTestCase, error) {
	rows, err := q.db.Query(ctx, listPlaygroundTestCasesByPlaygroundID, arg.PlaygroundID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PlaygroundTestCase
	for rows.Next() {
		var i PlaygroundTestCase
		if err := rows.Scan(
			&i.ID,
			&i.PlaygroundID,
			&i.CaseKey,
			&i.Variables,
			&i.Expectations,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPlaygroundsByWorkspaceID = `-- name: ListPlaygroundsByWorkspaceID :many
SELECT id, organization_id, workspace_id, name, prompt_template, system_prompt, evaluation_spec, created_by_user_id, updated_by_user_id, created_at, updated_at
FROM playgrounds
WHERE workspace_id = $1
ORDER BY updated_at DESC
`

type ListPlaygroundsByWorkspaceIDParams struct {
	WorkspaceID uuid.UUID
}

func (q *Queries) ListPlaygroundsByWorkspaceID(ctx context.Context, arg ListPlaygroundsByWorkspaceIDParams) ([]Playground, error) {
	rows, err := q.db.Query(ctx, listPlaygroundsByWorkspaceID, arg.WorkspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Playground
	for rows.Next() {
		var i Playground
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.WorkspaceID,
			&i.Name,
			&i.PromptTemplate,
			&i.SystemPrompt,
			&i.EvaluationSpec,
			&i.CreatedByUserID,
			&i.UpdatedByUserID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setPlaygroundExperimentTemporalIDs = `-- name: SetPlaygroundExperimentTemporalIDs :one
UPDATE playground_experiments
SET
    temporal_workflow_id = $1,
    temporal_run_id = $2
WHERE id = $3
RETURNING id, organization_id, workspace_id, playground_id, provider_account_id, model_alias_id, name, status, request_config, summary, temporal_workflow_id, temporal_run_id, queued_at, started_at, finished_at, failed_at, created_by_user_id, created_at, updated_at
`

type SetPlaygroundExperimentTemporalIDsParams struct {
	TemporalWorkflowID *string
	TemporalRunID      *string
	ID                 uuid.UUID
}

func (q *Queries) SetPlaygroundExperimentTemporalIDs(ctx context.Context, arg SetPlaygroundExperimentTemporalIDsParams) (PlaygroundExperiment, error) {
	row := q.db.QueryRow(ctx, setPlaygroundExperimentTemporalIDs, arg.TemporalWorkflowID, arg.TemporalRunID, arg.ID)
	var i PlaygroundExperiment
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.WorkspaceID,
		&i.PlaygroundID,
		&i.ProviderAccountID,
		&i.ModelAliasID,
		&i.Name,
		&i.Status,
		&i.RequestConfig,
		&i.Summary,
		&i.TemporalWorkflowID,
		&i.TemporalRunID,
		&i.QueuedAt,
		&i.StartedAt,
		&i.FinishedAt,
		&i.FailedAt,
		&i.CreatedByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updatePlayground = `-- name: UpdatePlayground :one
UPDATE playgrounds
SET
    name = $1,
    prompt_template = $2,
    system_prompt = $3,
    evaluation_spec = $4,
    updated_by_user_id = $5
WHERE id = $6
RETURNING id, organization_id, workspace_id, name, prompt_template, system_prompt, evaluation_spec, created_by_user_id, updated_by_user_id, created_at, updated_at
`

type UpdatePlaygroundParams struct {
	Name            string
	PromptTemplate  string
	SystemPrompt    string
	EvaluationSpec  []byte
	UpdatedByUserID *uuid.UUID
	ID              uuid.UUID
}

func (q *Queries) UpdatePlayground(ctx context.Context, arg UpdatePlaygroundParams) (Playground, error) {
	row := q.db.QueryRow(ctx, updatePlayground,
		arg.Name,
		arg.PromptTemplate,
		arg.SystemPrompt,
		arg.EvaluationSpec,
		arg.UpdatedByUserID,
		arg.ID,
	)
	var i Playground
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.WorkspaceID,
		&i.Name,
		&i.PromptTemplate,
		&i.SystemPrompt,
		&i.EvaluationSpec,
		&i.CreatedByUserID,
		&i.UpdatedByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updatePlaygroundExperimentStatus = `-- name: UpdatePlaygroundExperimentStatus :one
UPDATE playground_experiments
SET
    status = $1,
    summary = $2,
    started_at = $3,
    finished_at = $4,
    failed_at = $5
WHERE id = $6
RETURNING id, organization_id, workspace_id, playground_id, provider_account_id, model_alias_id, name, status, request_config, summary, temporal_workflow_id, temporal_run_id, queued_at, started_at, finished_at, failed_at, created_by_user_id, created_at, updated_at
`

type UpdatePlaygroundExperimentStatusParams struct {
	Status     string
	Summary    []byte
	StartedAt  pgtype.Timestamptz
	FinishedAt pgtype.Timestamptz
	FailedAt   pgtype.Timestamptz
	ID         uuid.UUID
}

func (q *Queries) UpdatePlaygroundExperimentStatus(ctx context.Context, arg UpdatePlaygroundExperimentStatusParams) (PlaygroundExperiment, error) {
	row := q.db.QueryRow(ctx, updatePlaygroundExperimentStatus,
		arg.Status,
		arg.Summary,
		arg.StartedAt,
		arg.FinishedAt,
		arg.FailedAt,
		arg.ID,
	)
	var i PlaygroundExperiment
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.WorkspaceID,
		&i.PlaygroundID,
		&i.ProviderAccountID,
		&i.ModelAliasID,
		&i.Name,
		&i.Status,
		&i.RequestConfig,
		&i.Summary,
		&i.TemporalWorkflowID,
		&i.TemporalRunID,
		&i.QueuedAt,
		&i.StartedAt,
		&i.FinishedAt,
		&i.FailedAt,
		&i.CreatedByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updatePlaygroundTestCase = `-- name: UpdatePlaygroundTestCase :one
UPDATE playground_test_cases
SET
    case_key = $1,
    variables = $2,
    expectations = $3
WHERE id = $4
RETURNING id, playground_id, case_key, variables, expectations, created_at, updated_at
`

type UpdatePlaygroundTestCaseParams struct {
	CaseKey      string
	Variables    []byte
	Expectations []byte
	ID           uuid.UUID
}

func (q *Queries) UpdatePlaygroundTestCase(ctx context.Context, arg UpdatePlaygroundTestCaseParams) (PlaygroundTestCase, error) {
	row := q.db.QueryRow(ctx, updatePlaygroundTestCase,
		arg.CaseKey,
		arg.Variables,
		arg.Expectations,
		arg.ID,
	)
	var i PlaygroundTestCase
	err := row.Scan(
		&i.ID,
		&i.PlaygroundID,
		&i.CaseKey,
		&i.Variables,
		&i.Expectations,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertPlaygroundExperimentResult = `-- name: UpsertPlaygroundExperimentResult :one
INSERT INTO playground_experiment_results (
    playground_experiment_id,
    playground_test_case_id,
    case_key,
    status,
    variables,
    expectations,
    rendered_prompt,
    actual_output,
    provider_key,
    provider_model_id,
    input_tokens,
    output_tokens,
    total_tokens,
    latency_ms,
    cost_usd,
    validator_results,
    llm_judge_results,
    dimension_results,
    dimension_scores,
    warnings,
    error_message
)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9,
    $10,
    $11,
    $12,
    $13,
    $14,
    $15,
    $16,
    $17,
    $18,
    $19,
    $20,
    $21
)
ON CONFLICT (playground_experiment_id, playground_test_case_id)
DO UPDATE SET
    case_key = EXCLUDED.case_key,
    status = EXCLUDED.status,
    variables = EXCLUDED.variables,
    expectations = EXCLUDED.expectations,
    rendered_prompt = EXCLUDED.rendered_prompt,
    actual_output = EXCLUDED.actual_output,
    provider_key = EXCLUDED.provider_key,
    provider_model_id = EXCLUDED.provider_model_id,
    input_tokens = EXCLUDED.input_tokens,
    output_tokens = EXCLUDED.output_tokens,
    total_tokens = EXCLUDED.total_tokens,
    latency_ms = EXCLUDED.latency_ms,
    cost_usd = EXCLUDED.cost_usd,
    validator_results = EXCLUDED.validator_results,
    llm_judge_results = EXCLUDED.llm_judge_results,
    dimension_results = EXCLUDED.dimension_results,
    dimension_scores = EXCLUDED.dimension_scores,
    warnings = EXCLUDED.warnings,
    error_message = EXCLUDED.error_message
RETURNING id, playground_experiment_id, playground_test_case_id, case_key, status, variables, expectations, rendered_prompt, actual_output, provider_key, provider_model_id, input_tokens, output_tokens, total_tokens, latency_ms, cost_usd, validator_results, llm_judge_results, dimension_results, dimension_scores, warnings, error_message, created_at, updated_at
`

type UpsertPlaygroundExperimentResultParams struct {
	PlaygroundExperimentID uuid.UUID
	PlaygroundTestCaseID   uuid.UUID
	CaseKey                string
	Status                 string
	Variables              []byte
	Expectations           []byte
	RenderedPrompt         string
	ActualOutput           string
	ProviderKey            string
	ProviderModelID        string
	InputTokens            int64
	OutputTokens           int64
	TotalTokens            int64
	LatencyMs              int64
	CostUsd                pgtype.Numeric
	ValidatorResults       []byte
	LlmJudgeResults        []byte
	DimensionResults       []byte
	DimensionScores        []byte
	Warnings               []byte
	ErrorMessage           *string
}

func (q *Queries) UpsertPlaygroundExperimentResult(ctx context.Context, arg UpsertPlaygroundExperimentResultParams) (PlaygroundExperimentResult, error) {
	row := q.db.QueryRow(ctx, upsertPlaygroundExperimentResult,
		arg.PlaygroundExperimentID,
		arg.PlaygroundTestCaseID,
		arg.CaseKey,
		arg.Status,
		arg.Variables,
		arg.Expectations,
		arg.RenderedPrompt,
		arg.ActualOutput,
		arg.ProviderKey,
		arg.ProviderModelID,
		arg.InputTokens,
		arg.OutputTokens,
		arg.TotalTokens,
		arg.LatencyMs,
		arg.CostUsd,
		arg.ValidatorResults,
		arg.LlmJudgeResults,
		arg.DimensionResults,
		arg.DimensionScores,
		arg.Warnings,
		arg.ErrorMessage,
	)
	var i PlaygroundExperimentResult
	err := row.Scan(
		&i.ID,
		&i.PlaygroundExperimentID,
		&i.PlaygroundTestCaseID,
		&i.CaseKey,
		&i.Status,
		&i.Variables,
		&i.Expectations,
		&i.RenderedPrompt,
		&i.ActualOutput,
		&i.ProviderKey,
		&i.ProviderModelID,
		&i.InputTokens,
		&i.OutputTokens,
		&i.TotalTokens,
		&i.LatencyMs,
		&i.CostUsd,
		&i.ValidatorResults,
		&i.LlmJudgeResults,
		&i.DimensionResults,
		&i.DimensionScores,
		&i.Warnings,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
