// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	// Append-only audit row for one draft+ tool call (#875 §6). request_payload/result_payload are
	// audit-scrubbed metadata only. confirmation_id is a soft reference (no FK).
	AppendVibeEvalToolInvocation(ctx context.Context, arg AppendVibeEvalToolInvocationParams) (VibeEvalToolInvocation, error)
	ApplyHostedRunEvent(ctx context.Context, arg ApplyHostedRunEventParams) (HostedRunExecution, error)
	ArchiveDataset(ctx context.Context, arg ArchiveDatasetParams) (Dataset, error)
	AttachRunToEvalSession(ctx context.Context, arg AttachRunToEvalSessionParams) (Run, error)
	BeginBillingWebhookEvent(ctx context.Context, arg BeginBillingWebhookEventParams) (string, error)
	ClaimAgentTryout(ctx context.Context, arg ClaimAgentTryoutParams) (AgentTryout, error)
	CountActiveOrgMembers(ctx context.Context, arg CountActiveOrgMembersParams) (int32, error)
	CountActiveWorkspaceRuns(ctx context.Context, arg CountActiveWorkspaceRunsParams) (int32, error)
	CountActiveWorkspaces(ctx context.Context, arg CountActiveWorkspacesParams) (int32, error)
	CountDatasetBaselinesByDatasetID(ctx context.Context, arg CountDatasetBaselinesByDatasetIDParams) (int64, error)
	CountDatasetEvalResults(ctx context.Context, arg CountDatasetEvalResultsParams) (int64, error)
	CountDatasetExamplesByDatasetID(ctx context.Context, arg CountDatasetExamplesByDatasetIDParams) (int64, error)
	CountDatasetGenerationRejectionsByJobID(ctx context.Context, arg CountDatasetGenerationRejectionsByJobIDParams) (int64, error)
	CountDatasetTraceCandidates(ctx context.Context, arg CountDatasetTraceCandidatesParams) (int64, error)
	CountDatasetsByWorkspaceID(ctx context.Context, arg CountDatasetsByWorkspaceIDParams) (int64, error)
	CountRegressionCasesBySuiteID(ctx context.Context, arg CountRegressionCasesBySuiteIDParams) (int64, error)
	CountRegressionCasesBySuiteIDs(ctx context.Context, arg CountRegressionCasesBySuiteIDsParams) ([]CountRegressionCasesBySuiteIDsRow, error)
	CountRegressionCasesByWorkspaceID(ctx context.Context, arg CountRegressionCasesByWorkspaceIDParams) (int64, error)
	CountRegressionSuitesByWorkspaceID(ctx context.Context, arg CountRegressionSuitesByWorkspaceIDParams) (int64, error)
	CountRunsByWorkspaceID(ctx context.Context, arg CountRunsByWorkspaceIDParams) (int64, error)
	CreateAgentBuild(ctx context.Context, arg CreateAgentBuildParams) (AgentBuild, error)
	CreateAgentBuildVersion(ctx context.Context, arg CreateAgentBuildVersionParams) (AgentBuildVersion, error)
	CreateAgentDeployment(ctx context.Context, arg CreateAgentDeploymentParams) (AgentDeployment, error)
	CreateAgentTryout(ctx context.Context, arg CreateAgentTryoutParams) (AgentTryout, error)
	CreateBillingCheckoutIntent(ctx context.Context, arg CreateBillingCheckoutIntentParams) (CreateBillingCheckoutIntentRow, error)
	CreateBillingTrialGrant(ctx context.Context, arg CreateBillingTrialGrantParams) (BillingTrialGrant, error)
	CreateDataset(ctx context.Context, arg CreateDatasetParams) (Dataset, error)
	CreateDatasetEvalChallengeInputSet(ctx context.Context, arg CreateDatasetEvalChallengeInputSetParams) (ChallengeInputSet, error)
	CreateDatasetGenerationJob(ctx context.Context, arg CreateDatasetGenerationJobParams) (DatasetGenerationJob, error)
	CreateDatasetGenerationRejection(ctx context.Context, arg CreateDatasetGenerationRejectionParams) (DatasetGenerationRejection, error)
	CreateDatasetTraceCandidate(ctx context.Context, arg CreateDatasetTraceCandidateParams) (DatasetTraceCandidate, error)
	CreateDatasetTraceImport(ctx context.Context, arg CreateDatasetTraceImportParams) (DatasetTraceImport, error)
	CreateDatasetVersion(ctx context.Context, arg CreateDatasetVersionParams) (DatasetVersion, error)
	CreateDatasetVersionInputSet(ctx context.Context, arg CreateDatasetVersionInputSetParams) (DatasetVersionInputSet, error)
	CreateEvalSession(ctx context.Context, arg CreateEvalSessionParams) (EvalSession, error)
	CreateEvaluationSpec(ctx context.Context, arg CreateEvaluationSpecParams) (EvaluationSpec, error)
	CreateHostedRunExecution(ctx context.Context, arg CreateHostedRunExecutionParams) (HostedRunExecution, error)
	CreatePlayground(ctx context.Context, arg CreatePlaygroundParams) (Playground, error)
	CreatePlaygroundExperiment(ctx context.Context, arg CreatePlaygroundExperimentParams) (PlaygroundExperiment, error)
	CreatePlaygroundTestCase(ctx context.Context, arg CreatePlaygroundTestCaseParams) (PlaygroundTestCase, error)
	CreateRegressionCase(ctx context.Context, arg CreateRegressionCaseParams) (WorkspaceRegressionCase, error)
	CreateRegressionPromotion(ctx context.Context, arg CreateRegressionPromotionParams) (WorkspaceRegressionPromotion, error)
	CreateRegressionSuite(ctx context.Context, arg CreateRegressionSuiteParams) (WorkspaceRegressionSuite, error)
	CreateRun(ctx context.Context, arg CreateRunParams) (Run, error)
	CreateRunAgent(ctx context.Context, arg CreateRunAgentParams) (RunAgent, error)
	CreateRunCaseSelection(ctx context.Context, arg CreateRunCaseSelectionParams) (RunCaseSelection, error)
	CreateVibeEvalConversation(ctx context.Context, arg CreateVibeEvalConversationParams) (VibeEvalConversation, error)
	CreateVibeEvalDraft(ctx context.Context, arg CreateVibeEvalDraftParams) (VibeEvalDraft, error)
	// Propose half of the confirmation engine (#875 §5.3). bound_args is the verbatim args to
	// execute on approve; payload_hash binds the confirmation to exactly those args.
	CreateVibeEvalPendingConfirmation(ctx context.Context, arg CreateVibeEvalPendingConfirmationParams) (VibeEvalPendingConfirmation, error)
	DeletePlayground(ctx context.Context, arg DeletePlaygroundParams) error
	DeletePlaygroundTestCase(ctx context.Context, arg DeletePlaygroundTestCaseParams) error
	// Transition lapsed 'pending' rows for a conversation to 'expired' so they leave the active
	// partial unique index and stop blocking re-proposal (#875 §5.3). The create path runs this in
	// the same tx before inserting.
	ExpireStaleVibeEvalPendingConfirmations(ctx context.Context, arg ExpireStaleVibeEvalPendingConfirmationsParams) ([]VibeEvalPendingConfirmation, error)
	FindOrganizationByDodoSubscriptionOrCustomer(ctx context.Context, arg FindOrganizationByDodoSubscriptionOrCustomerParams) (uuid.UUID, error)
	FinishBillingWebhookEvent(ctx context.Context, arg FinishBillingWebhookEventParams) (int64, error)
	GetAgentBuildByID(ctx context.Context, arg GetAgentBuildByIDParams) (AgentBuild, error)
	GetAgentBuildVersionByID(ctx context.Context, arg GetAgentBuildVersionByIDParams) (AgentBuildVersion, error)
	GetAgentTryoutByID(ctx context.Context, arg GetAgentTryoutByIDParams) (AgentTryout, error)
	GetBillingAccountByOrganizationID(ctx context.Context, arg GetBillingAccountByOrganizationIDParams) (BillingAccount, error)
	GetBillingSubscriptionByDodoID(ctx context.Context, arg GetBillingSubscriptionByDodoIDParams) (BillingSubscription, error)
	GetChallengeIdentityForDatasetEval(ctx context.Context, arg GetChallengeIdentityForDatasetEvalParams) (uuid.UUID, error)
	GetChallengeInputSetByID(ctx context.Context, arg GetChallengeInputSetByIDParams) (ChallengeInputSet, error)
	GetDatasetBaselineByID(ctx context.Context, arg GetDatasetBaselineByIDParams) (DatasetBaseline, error)
	GetDatasetByID(ctx context.Context, arg GetDatasetByIDParams) (GetDatasetByIDRow, error)
	GetDatasetEvalRunByRunID(ctx context.Context, arg GetDatasetEvalRunByRunIDParams) (DatasetEvalRun, error)
	GetDatasetExampleByExternalID(ctx context.Context, arg GetDatasetExampleByExternalIDParams) (DatasetExample, error)
	GetDatasetExampleByID(ctx context.Context, arg GetDatasetExampleByIDParams) (DatasetExample, error)
	GetDatasetGenerationJobByID(ctx context.Context, arg GetDatasetGenerationJobByIDParams) (DatasetGenerationJob, error)
	GetDatasetRegressionSuiteLinkByDatasetID(ctx context.Context, arg GetDatasetRegressionSuiteLinkByDatasetIDParams) (DatasetRegressionSuiteLink, error)
	GetDatasetTraceCandidateByID(ctx context.Context, arg GetDatasetTraceCandidateByIDParams) (DatasetTraceCandidate, error)
	GetDatasetVersionByID(ctx context.Context, arg GetDatasetVersionByIDParams) (DatasetVersion, error)
	GetDatasetVersionInputSetByBinding(ctx context.Context, arg GetDatasetVersionInputSetByBindingParams) (DatasetVersionInputSet, error)
	GetDatasetVersionInputSetByID(ctx context.Context, arg GetDatasetVersionInputSetByIDParams) (DatasetVersionInputSet, error)
	GetEvalSessionByID(ctx context.Context, arg GetEvalSessionByIDParams) (EvalSession, error)
	GetEvalSessionResultBySessionID(ctx context.Context, arg GetEvalSessionResultBySessionIDParams) (EvalSessionResult, error)
	GetEvaluationSpecByChallengePackVersionAndVersion(ctx context.Context, arg GetEvaluationSpecByChallengePackVersionAndVersionParams) (EvaluationSpec, error)
	GetEvaluationSpecByID(ctx context.Context, arg GetEvaluationSpecByIDParams) (EvaluationSpec, error)
	GetHostedRunExecutionByRunAgentID(ctx context.Context, arg GetHostedRunExecutionByRunAgentIDParams) (HostedRunExecution, error)
	GetLatestBillingCheckoutIntentByOrganizationID(ctx context.Context, arg GetLatestBillingCheckoutIntentByOrganizationIDParams) (GetLatestBillingCheckoutIntentByOrganizationIDRow, error)
	GetLatestBillingSubscriptionByOrganizationID(ctx context.Context, arg GetLatestBillingSubscriptionByOrganizationIDParams) (BillingSubscription, error)
	GetLatestRegressionPromotionByCaseID(ctx context.Context, arg GetLatestRegressionPromotionByCaseIDParams) (WorkspaceRegressionPromotion, error)
	GetLatestVersionNumberForBuild(ctx context.Context, arg GetLatestVersionNumberForBuildParams) (int32, error)
	GetOrganizationEntitlements(ctx context.Context, arg GetOrganizationEntitlementsParams) (GetOrganizationEntitlementsRow, error)
	GetPlaygroundByID(ctx context.Context, arg GetPlaygroundByIDParams) (Playground, error)
	GetPlaygroundExperimentByID(ctx context.Context, arg GetPlaygroundExperimentByIDParams) (PlaygroundExperiment, error)
	GetPlaygroundTestCaseByID(ctx context.Context, arg GetPlaygroundTestCaseByIDParams) (PlaygroundTestCase, error)
	GetRegressionCaseByID(ctx context.Context, arg GetRegressionCaseByIDParams) (GetRegressionCaseByIDRow, error)
	GetRegressionCaseIDByPromotionSource(ctx context.Context, arg GetRegressionCaseIDByPromotionSourceParams) (uuid.UUID, error)
	GetRegressionCaseValidationStatsByCaseID(ctx context.Context, arg GetRegressionCaseValidationStatsByCaseIDParams) (GetRegressionCaseValidationStatsByCaseIDRow, error)
	GetRegressionSuiteByID(ctx context.Context, arg GetRegressionSuiteByIDParams) (WorkspaceRegressionSuite, error)
	GetRunAgentByID(ctx context.Context, arg GetRunAgentByIDParams) (RunAgent, error)
	GetRunAgentExecutionContextByID(ctx context.Context, arg GetRunAgentExecutionContextByIDParams) (GetRunAgentExecutionContextByIDRow, error)
	GetRunAgentReplayByRunAgentID(ctx context.Context, arg GetRunAgentReplayByRunAgentIDParams) (RunAgentReplay, error)
	GetRunAgentScorecardByRunAgentID(ctx context.Context, arg GetRunAgentScorecardByRunAgentIDParams) (GetRunAgentScorecardByRunAgentIDRow, error)
	GetRunByID(ctx context.Context, arg GetRunByIDParams) (Run, error)
	GetRunComparisonByRunIDs(ctx context.Context, arg GetRunComparisonByRunIDsParams) (RunComparison, error)
	GetRunScorecardByRunID(ctx context.Context, arg GetRunScorecardByRunIDParams) (RunScorecard, error)
	GetRunnableChallengePackVersionByID(ctx context.Context, arg GetRunnableChallengePackVersionByIDParams) (ChallengePackVersion, error)
	// The durable, outcome-aware execution result for a confirmation: the latest ok/error audit row
	// (the confirmation_required propose row is excluded). 0 rows ⇒ the confirmed effect never ran (or
	// ran but its best-effort audit write was lost — the caller treats that ambiguity conservatively).
	GetVibeEvalConfirmedToolOutcome(ctx context.Context, arg GetVibeEvalConfirmedToolOutcomeParams) (string, error)
	GetVibeEvalConversationByID(ctx context.Context, arg GetVibeEvalConversationByIDParams) (VibeEvalConversation, error)
	GetVibeEvalDraftByID(ctx context.Context, arg GetVibeEvalDraftByIDParams) (VibeEvalDraft, error)
	GetVibeEvalPendingConfirmationByID(ctx context.Context, arg GetVibeEvalPendingConfirmationByIDParams) (VibeEvalPendingConfirmation, error)
	// Crash-safe re-entry: returns the row only if it is still 'executing' and the presented hash
	// matches, so a retried POST can resume effect execution exactly once. 0 rows => not resumable.
	GetVibeEvalPendingConfirmationForResume(ctx context.Context, arg GetVibeEvalPendingConfirmationForResumeParams) (VibeEvalPendingConfirmation, error)
	GetWorkspaceUsageWindowCounts(ctx context.Context, arg GetWorkspaceUsageWindowCountsParams) (GetWorkspaceUsageWindowCountsRow, error)
	InsertDatasetBaseline(ctx context.Context, arg InsertDatasetBaselineParams) (DatasetBaseline, error)
	InsertDatasetExample(ctx context.Context, arg InsertDatasetExampleParams) (DatasetExample, error)
	InsertDatasetExampleRevision(ctx context.Context, arg InsertDatasetExampleRevisionParams) (DatasetExampleRevision, error)
	InsertDatasetVersionExample(ctx context.Context, arg InsertDatasetVersionExampleParams) error
	InsertRunAgentStatusHistory(ctx context.Context, arg InsertRunAgentStatusHistoryParams) (RunAgentStatusHistory, error)
	InsertRunEvent(ctx context.Context, arg InsertRunEventParams) (RunEvent, error)
	InsertRunStatusHistory(ctx context.Context, arg InsertRunStatusHistoryParams) (RunStatusHistory, error)
	// Step 2 of the append: runs after LockVibeEvalConversationForAppend in the same transaction,
	// so MAX(seq) is computed against a post-lock snapshot. org/workspace come from the locked row.
	InsertVibeEvalMessage(ctx context.Context, arg InsertVibeEvalMessageParams) (VibeEvalMessage, error)
	ListActiveAgentDeploymentsByWorkspaceID(ctx context.Context, arg ListActiveAgentDeploymentsByWorkspaceIDParams) ([]ListActiveAgentDeploymentsByWorkspaceIDRow, error)
	ListAgentBuildVersionsByBuildID(ctx context.Context, arg ListAgentBuildVersionsByBuildIDParams) ([]AgentBuildVersion, error)
	ListAgentBuildsByWorkspaceID(ctx context.Context, arg ListAgentBuildsByWorkspaceIDParams) ([]AgentBuild, error)
	ListAgentTryoutsByWorkspaceID(ctx context.Context, arg ListAgentTryoutsByWorkspaceIDParams) ([]AgentTryout, error)
	ListChallengeIdentityIDsByPackVersionID(ctx context.Context, arg ListChallengeIdentityIDsByPackVersionIDParams) ([]uuid.UUID, error)
	ListChallengeInputSetsByVersionID(ctx context.Context, arg ListChallengeInputSetsByVersionIDParams) ([]ListChallengeInputSetsByVersionIDRow, error)
	ListChallengePacks(ctx context.Context) ([]ListChallengePacksRow, error)
	ListDatasetBaselinesByDatasetID(ctx context.Context, arg ListDatasetBaselinesByDatasetIDParams) ([]DatasetBaseline, error)
	ListDatasetEvalResults(ctx context.Context, arg ListDatasetEvalResultsParams) ([]ListDatasetEvalResultsRow, error)
	ListDatasetEvalResultsForRun(ctx context.Context, arg ListDatasetEvalResultsForRunParams) ([]ListDatasetEvalResultsForRunRow, error)
	ListDatasetExamplesByDatasetID(ctx context.Context, arg ListDatasetExamplesByDatasetIDParams) ([]DatasetExample, error)
	ListDatasetGenerationRejectionsByJobID(ctx context.Context, arg ListDatasetGenerationRejectionsByJobIDParams) ([]DatasetGenerationRejection, error)
	ListDatasetInputItemLinksByVersionInputSet(ctx context.Context, arg ListDatasetInputItemLinksByVersionInputSetParams) ([]DatasetInputItemLink, error)
	ListDatasetTraceCandidates(ctx context.Context, arg ListDatasetTraceCandidatesParams) ([]DatasetTraceCandidate, error)
	ListDatasetVersionExamples(ctx context.Context, arg ListDatasetVersionExamplesParams) ([]DatasetExample, error)
	ListDatasetVersionsByDatasetID(ctx context.Context, arg ListDatasetVersionsByDatasetIDParams) ([]DatasetVersion, error)
	ListDatasetsByWorkspaceID(ctx context.Context, arg ListDatasetsByWorkspaceIDParams) ([]ListDatasetsByWorkspaceIDRow, error)
	ListEvalSessions(ctx context.Context, arg ListEvalSessionsParams) ([]EvalSession, error)
	ListEvalSessionsByWorkspaceID(ctx context.Context, arg ListEvalSessionsByWorkspaceIDParams) ([]EvalSession, error)
	ListJudgeResultsByRunAgentAndEvaluationSpec(ctx context.Context, arg ListJudgeResultsByRunAgentAndEvaluationSpecParams) ([]ListJudgeResultsByRunAgentAndEvaluationSpecRow, error)
	ListLLMJudgeResultsByRunAgentAndEvaluationSpec(ctx context.Context, arg ListLLMJudgeResultsByRunAgentAndEvaluationSpecParams) ([]LlmJudgeResult, error)
	ListLatestDatasetExampleRevisions(ctx context.Context, arg ListLatestDatasetExampleRevisionsParams) ([]DatasetExampleRevision, error)
	ListLatestRegressionPromotionsByCaseIDs(ctx context.Context, arg ListLatestRegressionPromotionsByCaseIDsParams) ([]WorkspaceRegressionPromotion, error)
	ListMetricResultsByRunAgentAndEvaluationSpec(ctx context.Context, arg ListMetricResultsByRunAgentAndEvaluationSpecParams) ([]ListMetricResultsByRunAgentAndEvaluationSpecRow, error)
	ListPlaygroundExperimentResultsByExperimentID(ctx context.Context, arg ListPlaygroundExperimentResultsByExperimentIDParams) ([]PlaygroundExperimentResult, error)
	ListPlaygroundExperimentsByPlaygroundID(ctx context.Context, arg ListPlaygroundExperimentsByPlaygroundIDParams) ([]PlaygroundExperiment, error)
	ListPlaygroundTestCasesByPlaygroundID(ctx context.Context, arg ListPlaygroundTestCasesByPlaygroundIDParams) ([]PlaygroundTestCase, error)
	ListPlaygroundsByWorkspaceID(ctx context.Context, arg ListPlaygroundsByWorkspaceIDParams) ([]Playground, error)
	ListRecentComparableScoredRunsBeforeRunID(ctx context.Context, arg ListRecentComparableScoredRunsBeforeRunIDParams) ([]Run, error)
	ListRegressionCaseValidationStatsByCaseIDs(ctx context.Context, arg ListRegressionCaseValidationStatsByCaseIDsParams) ([]ListRegressionCaseValidationStatsByCaseIDsRow, error)
	ListRegressionCaseValidationStatsBySuiteID(ctx context.Context, arg ListRegressionCaseValidationStatsBySuiteIDParams) ([]ListRegressionCaseValidationStatsBySuiteIDRow, error)
	ListRegressionCasesBySuiteID(ctx context.Context, arg ListRegressionCasesBySuiteIDParams) ([]ListRegressionCasesBySuiteIDRow, error)
	ListRegressionCasesByWorkspaceID(ctx context.Context, arg ListRegressionCasesByWorkspaceIDParams) ([]ListRegressionCasesByWorkspaceIDRow, error)
	ListRegressionSuitesByWorkspaceID(ctx context.Context, arg ListRegressionSuitesByWorkspaceIDParams) ([]WorkspaceRegressionSuite, error)
	ListRunAgentScorecardsByRunID(ctx context.Context, arg ListRunAgentScorecardsByRunIDParams) ([]ListRunAgentScorecardsByRunIDRow, error)
	ListRunAgentStatusHistoryByRunAgentID(ctx context.Context, arg ListRunAgentStatusHistoryByRunAgentIDParams) ([]RunAgentStatusHistory, error)
	ListRunAgentsByRunID(ctx context.Context, arg ListRunAgentsByRunIDParams) ([]RunAgent, error)
	ListRunCaseSelectionsByRunID(ctx context.Context, arg ListRunCaseSelectionsByRunIDParams) ([]RunCaseSelection, error)
	ListRunEventsByRunAgentID(ctx context.Context, arg ListRunEventsByRunAgentIDParams) ([]RunEvent, error)
	// Cursor-paginated event feed for a run, ordered by the global row id so the
	// cursor is stable and resumable across all of a run's agents.
	ListRunEventsByRunIDAfter(ctx context.Context, arg ListRunEventsByRunIDAfterParams) ([]RunEvent, error)
	ListRunRegressionCoverageCasesByRunID(ctx context.Context, arg ListRunRegressionCoverageCasesByRunIDParams) ([]ListRunRegressionCoverageCasesByRunIDRow, error)
	ListRunStatusHistoryByRunID(ctx context.Context, arg ListRunStatusHistoryByRunIDParams) ([]RunStatusHistory, error)
	ListRunnableChallengePVersionsByPackID(ctx context.Context, arg ListRunnableChallengePVersionsByPackIDParams) ([]ListRunnableChallengePVersionsByPackIDRow, error)
	// The frozen billing identity for each lane comes from the SNAPSHOT path (4d-1):
	// source_provider_account_id is the BYOK signal; the model identity (provider_key/provider_model_id)
	// and the FROZEN output rate (model_aliases.output_cost_per_million_tokens) drive the eval-credit
	// estimate. LEFT JOINs so a deployment with no managed alias still returns one row.
	ListRunnableDeploymentsWithLatestSnapshot(ctx context.Context, arg ListRunnableDeploymentsWithLatestSnapshotParams) ([]ListRunnableDeploymentsWithLatestSnapshotRow, error)
	ListRunsByEvalSessionID(ctx context.Context, arg ListRunsByEvalSessionIDParams) ([]Run, error)
	ListRunsByWorkspaceID(ctx context.Context, arg ListRunsByWorkspaceIDParams) ([]Run, error)
	ListVibeEvalConversationsByWorkspaceID(ctx context.Context, arg ListVibeEvalConversationsByWorkspaceIDParams) ([]VibeEvalConversation, error)
	ListVibeEvalDraftsByConversationID(ctx context.Context, arg ListVibeEvalDraftsByConversationIDParams) ([]VibeEvalDraft, error)
	ListVibeEvalMessagesByConversationID(ctx context.Context, arg ListVibeEvalMessagesByConversationIDParams) ([]VibeEvalMessage, error)
	ListVibeEvalToolInvocationsByConversationID(ctx context.Context, arg ListVibeEvalToolInvocationsByConversationIDParams) ([]VibeEvalToolInvocation, error)
	LockActiveDatasetForVersion(ctx context.Context, arg LockActiveDatasetForVersionParams) (uuid.UUID, error)
	// Step 1 of a two-statement append (run inside a repository transaction). Locks the
	// conversation row FOR NO KEY UPDATE so concurrent appends to the same conversation serialize.
	// NO KEY UPDATE (not FOR UPDATE) still mutually excludes concurrent appenders while staying
	// compatible with the FOR KEY SHARE locks that FK checks from sibling inserts
	// (e.g. vibe_eval_drafts referencing this conversation) take on the same row.
	// The lock must be taken in its OWN statement: under READ COMMITTED, the following INSERT then
	// runs with a fresh snapshot taken AFTER the lock wait, so its MAX(seq) sees the prior
	// appender's committed row. A single CTE statement would compute MAX(seq) against the snapshot
	// taken before the lock wait and could still collide on seq.
	LockVibeEvalConversationForAppend(ctx context.Context, arg LockVibeEvalConversationForAppendParams) (LockVibeEvalConversationForAppendRow, error)
	MarkAgentBuildVersionReady(ctx context.Context, arg MarkAgentBuildVersionReadyParams) error
	MarkBillingCheckoutIntentCompleted(ctx context.Context, arg MarkBillingCheckoutIntentCompletedParams) (int64, error)
	MarkDatasetTraceCandidatePromotedIfPending(ctx context.Context, arg MarkDatasetTraceCandidatePromotedIfPendingParams) (DatasetTraceCandidate, error)
	MarkHostedRunExecutionAccepted(ctx context.Context, arg MarkHostedRunExecutionAcceptedParams) (HostedRunExecution, error)
	MarkHostedRunExecutionFailed(ctx context.Context, arg MarkHostedRunExecutionFailedParams) (HostedRunExecution, error)
	MarkHostedRunExecutionTimedOut(ctx context.Context, arg MarkHostedRunExecutionTimedOutParams) (HostedRunExecution, error)
	MarkVibeEvalDraftPublished(ctx context.Context, arg MarkVibeEvalDraftPublishedParams) (VibeEvalDraft, error)
	// Content-preserving validation update (validate_draft) — sets only validation state/errors.
	MarkVibeEvalDraftValidation(ctx context.Context, arg MarkVibeEvalDraftValidationParams) (VibeEvalDraft, error)
	// Terminal transition after the bound effect runs: 'executing' -> 'succeeded' | 'failed'.
	// Conditioned on status='executing' so a crashed/retried effect transitions exactly once.
	MarkVibeEvalPendingConfirmationResult(ctx context.Context, arg MarkVibeEvalPendingConfirmationResultParams) (VibeEvalPendingConfirmation, error)
	NextDatasetVersionNumber(ctx context.Context, arg NextDatasetVersionNumberParams) (int32, error)
	PatchDataset(ctx context.Context, arg PatchDatasetParams) (Dataset, error)
	PatchDatasetExample(ctx context.Context, arg PatchDatasetExampleParams) (DatasetExample, error)
	PatchRegressionCase(ctx context.Context, arg PatchRegressionCaseParams) (WorkspaceRegressionCase, error)
	PatchRegressionSuite(ctx context.Context, arg PatchRegressionSuiteParams) (WorkspaceRegressionSuite, error)
	RecordDatasetEvalRun(ctx context.Context, arg RecordDatasetEvalRunParams) (DatasetEvalRun, error)
	// Atomic, single-use transition out of 'pending' (#875 §5.3). Only the request that matches a
	// still-pending, unexpired row with the presented payload_hash wins (0 rows => already resolved,
	// expired, or hash mismatch => reject). @new_status is 'executing' (approve) or 'denied' (deny).
	ResolveVibeEvalPendingConfirmation(ctx context.Context, arg ResolveVibeEvalPendingConfirmationParams) (VibeEvalPendingConfirmation, error)
	ResolveWorkspaceOrganization(ctx context.Context, arg ResolveWorkspaceOrganizationParams) (uuid.UUID, error)
	SetAgentTryoutRunID(ctx context.Context, arg SetAgentTryoutRunIDParams) (AgentTryout, error)
	SetDatasetGenerationJobTemporalIDs(ctx context.Context, arg SetDatasetGenerationJobTemporalIDsParams) (DatasetGenerationJob, error)
	SetPlaygroundExperimentTemporalIDs(ctx context.Context, arg SetPlaygroundExperimentTemporalIDsParams) (PlaygroundExperiment, error)
	SetRunTemporalIDs(ctx context.Context, arg SetRunTemporalIDsParams) (Run, error)
	SetVibeEvalConversationActiveDraft(ctx context.Context, arg SetVibeEvalConversationActiveDraftParams) (VibeEvalConversation, error)
	UpdateAgentBuildVersionDraft(ctx context.Context, arg UpdateAgentBuildVersionDraftParams) error
	UpdateAgentTryoutStatus(ctx context.Context, arg UpdateAgentTryoutStatusParams) (AgentTryout, error)
	UpdateDatasetExample(ctx context.Context, arg UpdateDatasetExampleParams) (DatasetExample, error)
	UpdateDatasetGenerationJobProgress(ctx context.Context, arg UpdateDatasetGenerationJobProgressParams) (DatasetGenerationJob, error)
	UpdateDatasetGenerationJobStatus(ctx context.Context, arg UpdateDatasetGenerationJobStatusParams) (DatasetGenerationJob, error)
	UpdateDatasetTraceCandidatePromotion(ctx context.Context, arg UpdateDatasetTraceCandidatePromotionParams) (DatasetTraceCandidate, error)
	UpdateEvalSessionStatus(ctx context.Context, arg UpdateEvalSessionStatusParams) (EvalSession, error)
	UpdatePlayground(ctx context.Context, arg UpdatePlaygroundParams) (Playground, error)
	UpdatePlaygroundExperimentStatus(ctx context.Context, arg UpdatePlaygroundExperimentStatusParams) (PlaygroundExperiment, error)
	UpdatePlaygroundTestCase(ctx context.Context, arg UpdatePlaygroundTestCaseParams) (PlaygroundTestCase, error)
	UpdateRunAgentStatus(ctx context.Context, arg UpdateRunAgentStatusParams) (RunAgent, error)
	UpdateRunStatus(ctx context.Context, arg UpdateRunStatusParams) (Run, error)
	// Editing content unpublishes the draft: the published refs are cleared so a stale published
	// version can never be reused as an idempotency signal for changed content (3c-3 effect identity).
	UpdateVibeEvalDraft(ctx context.Context, arg UpdateVibeEvalDraftParams) (VibeEvalDraft, error)
	UpsertBillingAccount(ctx context.Context, arg UpsertBillingAccountParams) error
	UpsertBillingSubscription(ctx context.Context, arg UpsertBillingSubscriptionParams) (BillingSubscription, error)
	UpsertCrossRunComparison(ctx context.Context, arg UpsertCrossRunComparisonParams) (RunComparison, error)
	UpsertDatasetChallengeInputItem(ctx context.Context, arg UpsertDatasetChallengeInputItemParams) (ChallengeInputItem, error)
	UpsertDatasetInputItemLink(ctx context.Context, arg UpsertDatasetInputItemLinkParams) (DatasetInputItemLink, error)
	UpsertDatasetRegressionSuiteLink(ctx context.Context, arg UpsertDatasetRegressionSuiteLinkParams) (DatasetRegressionSuiteLink, error)
	UpsertEvalSessionResult(ctx context.Context, arg UpsertEvalSessionResultParams) (EvalSessionResult, error)
	UpsertJudgeResult(ctx context.Context, arg UpsertJudgeResultParams) (UpsertJudgeResultRow, error)
	UpsertLLMJudgeResult(ctx context.Context, arg UpsertLLMJudgeResultParams) (LlmJudgeResult, error)
	UpsertMetricResult(ctx context.Context, arg UpsertMetricResultParams) (UpsertMetricResultRow, error)
	UpsertOrganizationEntitlements(ctx context.Context, arg UpsertOrganizationEntitlementsParams) error
	UpsertPlaygroundExperimentResult(ctx context.Context, arg UpsertPlaygroundExperimentResultParams) (PlaygroundExperimentResult, error)
	UpsertRunAgentReplayIndex(ctx context.Context, arg UpsertRunAgentReplayIndexParams) (RunAgentReplay, error)
	UpsertRunAgentReplaySummary(ctx context.Context, arg UpsertRunAgentReplaySummaryParams) (RunAgentReplay, error)
	UpsertRunAgentScorecard(ctx context.Context, arg UpsertRunAgentScorecardParams) (UpsertRunAgentScorecardRow, error)
	UpsertRunScorecard(ctx context.Context, arg UpsertRunScorecardParams) (RunScorecard, error)
	UpsertSameRunAgentComparison(ctx context.Context, arg UpsertSameRunAgentComparisonParams) (RunComparison, error)
}

var _ Querier = (*Queries)(nil)
