// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"context"
)

type Querier interface {
	CreateRun(ctx context.Context, arg CreateRunParams) (Run, error)
	CreateRunAgent(ctx context.Context, arg CreateRunAgentParams) (RunAgent, error)
	GetRunAgentByID(ctx context.Context, arg GetRunAgentByIDParams) (RunAgent, error)
	GetRunByID(ctx context.Context, arg GetRunByIDParams) (Run, error)
	InsertRunAgentStatusHistory(ctx context.Context, arg InsertRunAgentStatusHistoryParams) (RunAgentStatusHistory, error)
	InsertRunStatusHistory(ctx context.Context, arg InsertRunStatusHistoryParams) (RunStatusHistory, error)
	ListRunAgentStatusHistoryByRunAgentID(ctx context.Context, arg ListRunAgentStatusHistoryByRunAgentIDParams) ([]RunAgentStatusHistory, error)
	ListRunAgentsByRunID(ctx context.Context, arg ListRunAgentsByRunIDParams) ([]RunAgent, error)
	ListRunStatusHistoryByRunID(ctx context.Context, arg ListRunStatusHistoryByRunIDParams) ([]RunStatusHistory, error)
	SetRunTemporalIDs(ctx context.Context, arg SetRunTemporalIDsParams) (Run, error)
	UpdateRunAgentStatus(ctx context.Context, arg UpdateRunAgentStatusParams) (RunAgent, error)
	UpdateRunStatus(ctx context.Context, arg UpdateRunStatusParams) (Run, error)
}

var _ Querier = (*Queries)(nil)
