// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: regression_suites.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countRegressionSuitesByWorkspaceID = `-- name: CountRegressionSuitesByWorkspaceID :one
SELECT count(*)
FROM workspace_regression_suites
WHERE workspace_id = $1
`

type CountRegressionSuitesByWorkspaceIDParams struct {
	WorkspaceID uuid.UUID
}

func (q *Queries) CountRegressionSuitesByWorkspaceID(ctx context.Context, arg CountRegressionSuitesByWorkspaceIDParams) (int64, error) {
	row := q.db.QueryRow(ctx, countRegressionSuitesByWorkspaceID, arg.WorkspaceID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createRegressionCase = `-- name: CreateRegressionCase :one
INSERT INTO workspace_regression_cases (
    suite_id,
    title,
    description,
    status,
    severity,
    promotion_mode,
    source_run_id,
    source_run_agent_id,
    source_replay_id,
    source_challenge_pack_version_id,
    source_challenge_input_set_id,
    source_challenge_identity_id,
    source_case_key,
    source_item_key,
    evidence_tier,
    failure_class,
    failure_summary,
    payload_snapshot,
    expected_contract,
    validator_overrides,
    metadata
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9,
    $10,
    $11,
    $12,
    $13,
    $14,
    $15,
    $16,
    $17,
    $18,
    $19,
    $20,
    $21
)
RETURNING id, suite_id, title, description, status, severity, promotion_mode, source_run_id, source_run_agent_id, source_replay_id, source_challenge_pack_version_id, source_challenge_input_set_id, source_challenge_identity_id, source_case_key, source_item_key, evidence_tier, failure_class, failure_summary, payload_snapshot, expected_contract, validator_overrides, metadata, created_at, updated_at
`

type CreateRegressionCaseParams struct {
	SuiteID                      uuid.UUID
	Title                        string
	Description                  string
	Status                       string
	Severity                     string
	PromotionMode                string
	SourceRunID                  *uuid.UUID
	SourceRunAgentID             *uuid.UUID
	SourceReplayID               *uuid.UUID
	SourceChallengePackVersionID uuid.UUID
	SourceChallengeInputSetID    *uuid.UUID
	SourceChallengeIdentityID    uuid.UUID
	SourceCaseKey                string
	SourceItemKey                *string
	EvidenceTier                 string
	FailureClass                 string
	FailureSummary               string
	PayloadSnapshot              []byte
	ExpectedContract             []byte
	ValidatorOverrides           []byte
	Metadata                     []byte
}

func (q *Queries) CreateRegressionCase(ctx context.Context, arg CreateRegressionCaseParams) (WorkspaceRegressionCase, error) {
	row := q.db.QueryRow(ctx, createRegressionCase,
		arg.SuiteID,
		arg.Title,
		arg.Description,
		arg.Status,
		arg.Severity,
		arg.PromotionMode,
		arg.SourceRunID,
		arg.SourceRunAgentID,
		arg.SourceReplayID,
		arg.SourceChallengePackVersionID,
		arg.SourceChallengeInputSetID,
		arg.SourceChallengeIdentityID,
		arg.SourceCaseKey,
		arg.SourceItemKey,
		arg.EvidenceTier,
		arg.FailureClass,
		arg.FailureSummary,
		arg.PayloadSnapshot,
		arg.ExpectedContract,
		arg.ValidatorOverrides,
		arg.Metadata,
	)
	var i WorkspaceRegressionCase
	err := row.Scan(
		&i.ID,
		&i.SuiteID,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.Severity,
		&i.PromotionMode,
		&i.SourceRunID,
		&i.SourceRunAgentID,
		&i.SourceReplayID,
		&i.SourceChallengePackVersionID,
		&i.SourceChallengeInputSetID,
		&i.SourceChallengeIdentityID,
		&i.SourceCaseKey,
		&i.SourceItemKey,
		&i.EvidenceTier,
		&i.FailureClass,
		&i.FailureSummary,
		&i.PayloadSnapshot,
		&i.ExpectedContract,
		&i.ValidatorOverrides,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createRegressionPromotion = `-- name: CreateRegressionPromotion :one
INSERT INTO workspace_regression_promotions (
    workspace_regression_case_id,
    source_run_id,
    source_run_agent_id,
    source_event_refs,
    promoted_by_user_id,
    promotion_reason,
    promotion_snapshot
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7
)
RETURNING id, workspace_regression_case_id, source_run_id, source_run_agent_id, source_event_refs, promoted_by_user_id, promotion_reason, promotion_snapshot, created_at
`

type CreateRegressionPromotionParams struct {
	WorkspaceRegressionCaseID uuid.UUID
	SourceRunID               uuid.UUID
	SourceRunAgentID          uuid.UUID
	SourceEventRefs           []byte
	PromotedByUserID          uuid.UUID
	PromotionReason           string
	PromotionSnapshot         []byte
}

func (q *Queries) CreateRegressionPromotion(ctx context.Context, arg CreateRegressionPromotionParams) (WorkspaceRegressionPromotion, error) {
	row := q.db.QueryRow(ctx, createRegressionPromotion,
		arg.WorkspaceRegressionCaseID,
		arg.SourceRunID,
		arg.SourceRunAgentID,
		arg.SourceEventRefs,
		arg.PromotedByUserID,
		arg.PromotionReason,
		arg.PromotionSnapshot,
	)
	var i WorkspaceRegressionPromotion
	err := row.Scan(
		&i.ID,
		&i.WorkspaceRegressionCaseID,
		&i.SourceRunID,
		&i.SourceRunAgentID,
		&i.SourceEventRefs,
		&i.PromotedByUserID,
		&i.PromotionReason,
		&i.PromotionSnapshot,
		&i.CreatedAt,
	)
	return i, err
}

const createRegressionSuite = `-- name: CreateRegressionSuite :one
INSERT INTO workspace_regression_suites (
    workspace_id,
    source_challenge_pack_id,
    name,
    description,
    status,
    source_mode,
    default_gate_severity,
    created_by_user_id
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8
)
RETURNING
    id,
    workspace_id,
    source_challenge_pack_id,
    name,
    description,
    status,
    source_mode,
    default_gate_severity,
    created_by_user_id,
    created_at,
    updated_at
`

type CreateRegressionSuiteParams struct {
	WorkspaceID           uuid.UUID
	SourceChallengePackID uuid.UUID
	Name                  string
	Description           string
	Status                string
	SourceMode            string
	DefaultGateSeverity   string
	CreatedByUserID       uuid.UUID
}

func (q *Queries) CreateRegressionSuite(ctx context.Context, arg CreateRegressionSuiteParams) (WorkspaceRegressionSuite, error) {
	row := q.db.QueryRow(ctx, createRegressionSuite,
		arg.WorkspaceID,
		arg.SourceChallengePackID,
		arg.Name,
		arg.Description,
		arg.Status,
		arg.SourceMode,
		arg.DefaultGateSeverity,
		arg.CreatedByUserID,
	)
	var i WorkspaceRegressionSuite
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.SourceChallengePackID,
		&i.Name,
		&i.Description,
		&i.Status,
		&i.SourceMode,
		&i.DefaultGateSeverity,
		&i.CreatedByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getRegressionCaseByID = `-- name: GetRegressionCaseByID :one
SELECT
    c.id,
    c.suite_id,
    s.workspace_id,
    c.title,
    c.description,
    c.status,
    c.severity,
    c.promotion_mode,
    c.source_run_id,
    c.source_run_agent_id,
    c.source_replay_id,
    c.source_challenge_pack_version_id,
    c.source_challenge_input_set_id,
    c.source_challenge_identity_id,
    c.source_case_key,
    c.source_item_key,
    c.evidence_tier,
    c.failure_class,
    c.failure_summary,
    c.payload_snapshot,
    c.expected_contract,
    c.validator_overrides,
    c.metadata,
    c.created_at,
    c.updated_at
FROM workspace_regression_cases c
JOIN workspace_regression_suites s ON s.id = c.suite_id
WHERE c.id = $1
LIMIT 1
`

type GetRegressionCaseByIDParams struct {
	ID uuid.UUID
}

type GetRegressionCaseByIDRow struct {
	ID                           uuid.UUID
	SuiteID                      uuid.UUID
	WorkspaceID                  uuid.UUID
	Title                        string
	Description                  string
	Status                       string
	Severity                     string
	PromotionMode                string
	SourceRunID                  *uuid.UUID
	SourceRunAgentID             *uuid.UUID
	SourceReplayID               *uuid.UUID
	SourceChallengePackVersionID uuid.UUID
	SourceChallengeInputSetID    *uuid.UUID
	SourceChallengeIdentityID    uuid.UUID
	SourceCaseKey                string
	SourceItemKey                *string
	EvidenceTier                 string
	FailureClass                 string
	FailureSummary               string
	PayloadSnapshot              []byte
	ExpectedContract             []byte
	ValidatorOverrides           []byte
	Metadata                     []byte
	CreatedAt                    pgtype.Timestamptz
	UpdatedAt                    pgtype.Timestamptz
}

func (q *Queries) GetRegressionCaseByID(ctx context.Context, arg GetRegressionCaseByIDParams) (GetRegressionCaseByIDRow, error) {
	row := q.db.QueryRow(ctx, getRegressionCaseByID, arg.ID)
	var i GetRegressionCaseByIDRow
	err := row.Scan(
		&i.ID,
		&i.SuiteID,
		&i.WorkspaceID,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.Severity,
		&i.PromotionMode,
		&i.SourceRunID,
		&i.SourceRunAgentID,
		&i.SourceReplayID,
		&i.SourceChallengePackVersionID,
		&i.SourceChallengeInputSetID,
		&i.SourceChallengeIdentityID,
		&i.SourceCaseKey,
		&i.SourceItemKey,
		&i.EvidenceTier,
		&i.FailureClass,
		&i.FailureSummary,
		&i.PayloadSnapshot,
		&i.ExpectedContract,
		&i.ValidatorOverrides,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getRegressionSuiteByID = `-- name: GetRegressionSuiteByID :one
SELECT id, workspace_id, source_challenge_pack_id, name, description, status, source_mode, default_gate_severity, created_by_user_id, created_at, updated_at
FROM workspace_regression_suites
WHERE id = $1
LIMIT 1
`

type GetRegressionSuiteByIDParams struct {
	ID uuid.UUID
}

func (q *Queries) GetRegressionSuiteByID(ctx context.Context, arg GetRegressionSuiteByIDParams) (WorkspaceRegressionSuite, error) {
	row := q.db.QueryRow(ctx, getRegressionSuiteByID, arg.ID)
	var i WorkspaceRegressionSuite
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.SourceChallengePackID,
		&i.Name,
		&i.Description,
		&i.Status,
		&i.SourceMode,
		&i.DefaultGateSeverity,
		&i.CreatedByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listRegressionCasesBySuiteID = `-- name: ListRegressionCasesBySuiteID :many
SELECT
    c.id,
    c.suite_id,
    s.workspace_id,
    c.title,
    c.description,
    c.status,
    c.severity,
    c.promotion_mode,
    c.source_run_id,
    c.source_run_agent_id,
    c.source_replay_id,
    c.source_challenge_pack_version_id,
    c.source_challenge_input_set_id,
    c.source_challenge_identity_id,
    c.source_case_key,
    c.source_item_key,
    c.evidence_tier,
    c.failure_class,
    c.failure_summary,
    c.payload_snapshot,
    c.expected_contract,
    c.validator_overrides,
    c.metadata,
    c.created_at,
    c.updated_at
FROM workspace_regression_cases c
JOIN workspace_regression_suites s ON s.id = c.suite_id
WHERE c.suite_id = $1
ORDER BY c.created_at DESC, c.id DESC
`

type ListRegressionCasesBySuiteIDParams struct {
	SuiteID uuid.UUID
}

type ListRegressionCasesBySuiteIDRow struct {
	ID                           uuid.UUID
	SuiteID                      uuid.UUID
	WorkspaceID                  uuid.UUID
	Title                        string
	Description                  string
	Status                       string
	Severity                     string
	PromotionMode                string
	SourceRunID                  *uuid.UUID
	SourceRunAgentID             *uuid.UUID
	SourceReplayID               *uuid.UUID
	SourceChallengePackVersionID uuid.UUID
	SourceChallengeInputSetID    *uuid.UUID
	SourceChallengeIdentityID    uuid.UUID
	SourceCaseKey                string
	SourceItemKey                *string
	EvidenceTier                 string
	FailureClass                 string
	FailureSummary               string
	PayloadSnapshot              []byte
	ExpectedContract             []byte
	ValidatorOverrides           []byte
	Metadata                     []byte
	CreatedAt                    pgtype.Timestamptz
	UpdatedAt                    pgtype.Timestamptz
}

func (q *Queries) ListRegressionCasesBySuiteID(ctx context.Context, arg ListRegressionCasesBySuiteIDParams) ([]ListRegressionCasesBySuiteIDRow, error) {
	rows, err := q.db.Query(ctx, listRegressionCasesBySuiteID, arg.SuiteID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRegressionCasesBySuiteIDRow
	for rows.Next() {
		var i ListRegressionCasesBySuiteIDRow
		if err := rows.Scan(
			&i.ID,
			&i.SuiteID,
			&i.WorkspaceID,
			&i.Title,
			&i.Description,
			&i.Status,
			&i.Severity,
			&i.PromotionMode,
			&i.SourceRunID,
			&i.SourceRunAgentID,
			&i.SourceReplayID,
			&i.SourceChallengePackVersionID,
			&i.SourceChallengeInputSetID,
			&i.SourceChallengeIdentityID,
			&i.SourceCaseKey,
			&i.SourceItemKey,
			&i.EvidenceTier,
			&i.FailureClass,
			&i.FailureSummary,
			&i.PayloadSnapshot,
			&i.ExpectedContract,
			&i.ValidatorOverrides,
			&i.Metadata,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRegressionSuitesByWorkspaceID = `-- name: ListRegressionSuitesByWorkspaceID :many
SELECT id, workspace_id, source_challenge_pack_id, name, description, status, source_mode, default_gate_severity, created_by_user_id, created_at, updated_at
FROM workspace_regression_suites
WHERE workspace_id = $1
ORDER BY created_at DESC, id DESC
LIMIT $3 OFFSET $2
`

type ListRegressionSuitesByWorkspaceIDParams struct {
	WorkspaceID  uuid.UUID
	ResultOffset int32
	ResultLimit  int32
}

func (q *Queries) ListRegressionSuitesByWorkspaceID(ctx context.Context, arg ListRegressionSuitesByWorkspaceIDParams) ([]WorkspaceRegressionSuite, error) {
	rows, err := q.db.Query(ctx, listRegressionSuitesByWorkspaceID, arg.WorkspaceID, arg.ResultOffset, arg.ResultLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []WorkspaceRegressionSuite
	for rows.Next() {
		var i WorkspaceRegressionSuite
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.SourceChallengePackID,
			&i.Name,
			&i.Description,
			&i.Status,
			&i.SourceMode,
			&i.DefaultGateSeverity,
			&i.CreatedByUserID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const patchRegressionCase = `-- name: PatchRegressionCase :one
UPDATE workspace_regression_cases
SET title = COALESCE($1, title),
    description = COALESCE($2, description),
    status = COALESCE($3::text, status),
    severity = COALESCE($4, severity),
    updated_at = now()
WHERE id = $5
  AND ($6::text IS NULL OR status = $6::text)
RETURNING id, suite_id, title, description, status, severity, promotion_mode, source_run_id, source_run_agent_id, source_replay_id, source_challenge_pack_version_id, source_challenge_input_set_id, source_challenge_identity_id, source_case_key, source_item_key, evidence_tier, failure_class, failure_summary, payload_snapshot, expected_contract, validator_overrides, metadata, created_at, updated_at
`

type PatchRegressionCaseParams struct {
	Title       *string
	Description *string
	ToStatus    *string
	Severity    *string
	ID          uuid.UUID
	FromStatus  *string
}

func (q *Queries) PatchRegressionCase(ctx context.Context, arg PatchRegressionCaseParams) (WorkspaceRegressionCase, error) {
	row := q.db.QueryRow(ctx, patchRegressionCase,
		arg.Title,
		arg.Description,
		arg.ToStatus,
		arg.Severity,
		arg.ID,
		arg.FromStatus,
	)
	var i WorkspaceRegressionCase
	err := row.Scan(
		&i.ID,
		&i.SuiteID,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.Severity,
		&i.PromotionMode,
		&i.SourceRunID,
		&i.SourceRunAgentID,
		&i.SourceReplayID,
		&i.SourceChallengePackVersionID,
		&i.SourceChallengeInputSetID,
		&i.SourceChallengeIdentityID,
		&i.SourceCaseKey,
		&i.SourceItemKey,
		&i.EvidenceTier,
		&i.FailureClass,
		&i.FailureSummary,
		&i.PayloadSnapshot,
		&i.ExpectedContract,
		&i.ValidatorOverrides,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const patchRegressionSuite = `-- name: PatchRegressionSuite :one
UPDATE workspace_regression_suites
SET name = COALESCE($1, name),
    description = COALESCE($2, description),
    status = COALESCE($3::text, status),
    default_gate_severity = COALESCE($4, default_gate_severity),
    updated_at = now()
WHERE id = $5
  AND ($6::text IS NULL OR status = $6::text)
RETURNING id, workspace_id, source_challenge_pack_id, name, description, status, source_mode, default_gate_severity, created_by_user_id, created_at, updated_at
`

type PatchRegressionSuiteParams struct {
	Name                *string
	Description         *string
	ToStatus            *string
	DefaultGateSeverity *string
	ID                  uuid.UUID
	FromStatus          *string
}

func (q *Queries) PatchRegressionSuite(ctx context.Context, arg PatchRegressionSuiteParams) (WorkspaceRegressionSuite, error) {
	row := q.db.QueryRow(ctx, patchRegressionSuite,
		arg.Name,
		arg.Description,
		arg.ToStatus,
		arg.DefaultGateSeverity,
		arg.ID,
		arg.FromStatus,
	)
	var i WorkspaceRegressionSuite
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.SourceChallengePackID,
		&i.Name,
		&i.Description,
		&i.Status,
		&i.SourceMode,
		&i.DefaultGateSeverity,
		&i.CreatedByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
