// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: replay_reads.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const getRunAgentReplayByRunAgentID = `-- name: GetRunAgentReplayByRunAgentID :one
SELECT
    id,
    run_agent_id,
    artifact_id,
    summary,
    latest_sequence_number,
    event_count,
    created_at,
    updated_at
FROM run_agent_replays
WHERE run_agent_id = $1
LIMIT 1
`

type GetRunAgentReplayByRunAgentIDParams struct {
	RunAgentID uuid.UUID
}

func (q *Queries) GetRunAgentReplayByRunAgentID(ctx context.Context, arg GetRunAgentReplayByRunAgentIDParams) (RunAgentReplay, error) {
	row := q.db.QueryRow(ctx, getRunAgentReplayByRunAgentID, arg.RunAgentID)
	var i RunAgentReplay
	err := row.Scan(
		&i.ID,
		&i.RunAgentID,
		&i.ArtifactID,
		&i.Summary,
		&i.LatestSequenceNumber,
		&i.EventCount,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getRunAgentScorecardByRunAgentID = `-- name: GetRunAgentScorecardByRunAgentID :one
SELECT
    id,
    run_agent_id,
    evaluation_spec_id,
    overall_score::double precision AS overall_score,
    correctness_score::double precision AS correctness_score,
    reliability_score::double precision AS reliability_score,
    latency_score::double precision AS latency_score,
    cost_score::double precision AS cost_score,
    scorecard,
    created_at,
    updated_at
FROM run_agent_scorecards
WHERE run_agent_id = $1
LIMIT 1
`

type GetRunAgentScorecardByRunAgentIDParams struct {
	RunAgentID uuid.UUID
}

type GetRunAgentScorecardByRunAgentIDRow struct {
	ID               uuid.UUID
	RunAgentID       uuid.UUID
	EvaluationSpecID uuid.UUID
	OverallScore     *float64
	CorrectnessScore *float64
	ReliabilityScore *float64
	LatencyScore     *float64
	CostScore        *float64
	Scorecard        []byte
	CreatedAt        pgtype.Timestamptz
	UpdatedAt        pgtype.Timestamptz
}

func (q *Queries) GetRunAgentScorecardByRunAgentID(ctx context.Context, arg GetRunAgentScorecardByRunAgentIDParams) (GetRunAgentScorecardByRunAgentIDRow, error) {
	row := q.db.QueryRow(ctx, getRunAgentScorecardByRunAgentID, arg.RunAgentID)
	var i GetRunAgentScorecardByRunAgentIDRow
	err := row.Scan(
		&i.ID,
		&i.RunAgentID,
		&i.EvaluationSpecID,
		&i.OverallScore,
		&i.CorrectnessScore,
		&i.ReliabilityScore,
		&i.LatencyScore,
		&i.CostScore,
		&i.Scorecard,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
