// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: replay_reads.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const getRunAgentReplayByRunAgentID = `-- name: GetRunAgentReplayByRunAgentID :one
SELECT
    id,
    run_agent_id,
    artifact_id,
    summary,
    latest_sequence_number,
    event_count,
    created_at,
    updated_at
FROM run_agent_replays
WHERE run_agent_id = $1
LIMIT 1
`

type GetRunAgentReplayByRunAgentIDParams struct {
	RunAgentID uuid.UUID
}

func (q *Queries) GetRunAgentReplayByRunAgentID(ctx context.Context, arg GetRunAgentReplayByRunAgentIDParams) (RunAgentReplay, error) {
	row := q.db.QueryRow(ctx, getRunAgentReplayByRunAgentID, arg.RunAgentID)
	var i RunAgentReplay
	err := row.Scan(
		&i.ID,
		&i.RunAgentID,
		&i.ArtifactID,
		&i.Summary,
		&i.LatestSequenceNumber,
		&i.EventCount,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getRunAgentScorecardByRunAgentID = `-- name: GetRunAgentScorecardByRunAgentID :one
SELECT
    id,
    run_agent_id,
    evaluation_spec_id,
    overall_score,
    correctness_score,
    reliability_score,
    latency_score,
    cost_score,
    scorecard,
    created_at,
    updated_at
FROM run_agent_scorecards
WHERE run_agent_id = $1
LIMIT 1
`

type GetRunAgentScorecardByRunAgentIDParams struct {
	RunAgentID uuid.UUID
}

func (q *Queries) GetRunAgentScorecardByRunAgentID(ctx context.Context, arg GetRunAgentScorecardByRunAgentIDParams) (RunAgentScorecard, error) {
	row := q.db.QueryRow(ctx, getRunAgentScorecardByRunAgentID, arg.RunAgentID)
	var i RunAgentScorecard
	err := row.Scan(
		&i.ID,
		&i.RunAgentID,
		&i.EvaluationSpecID,
		&i.OverallScore,
		&i.CorrectnessScore,
		&i.ReliabilityScore,
		&i.LatencyScore,
		&i.CostScore,
		&i.Scorecard,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertRunAgentReplayIndex = `-- name: UpsertRunAgentReplayIndex :one
INSERT INTO run_agent_replays (
    run_agent_id,
    artifact_id,
    summary,
    latest_sequence_number,
    event_count
)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5
)
ON CONFLICT (run_agent_id) DO UPDATE
SET artifact_id = EXCLUDED.artifact_id,
    summary = EXCLUDED.summary,
    latest_sequence_number = EXCLUDED.latest_sequence_number,
    event_count = EXCLUDED.event_count
RETURNING id, run_agent_id, artifact_id, summary, latest_sequence_number, event_count, created_at, updated_at
`

type UpsertRunAgentReplayIndexParams struct {
	RunAgentID           uuid.UUID
	ArtifactID           *uuid.UUID
	Summary              []byte
	LatestSequenceNumber *int64
	EventCount           int64
}

func (q *Queries) UpsertRunAgentReplayIndex(ctx context.Context, arg UpsertRunAgentReplayIndexParams) (RunAgentReplay, error) {
	row := q.db.QueryRow(ctx, upsertRunAgentReplayIndex,
		arg.RunAgentID,
		arg.ArtifactID,
		arg.Summary,
		arg.LatestSequenceNumber,
		arg.EventCount,
	)
	var i RunAgentReplay
	err := row.Scan(
		&i.ID,
		&i.RunAgentID,
		&i.ArtifactID,
		&i.Summary,
		&i.LatestSequenceNumber,
		&i.EventCount,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
