// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: replay_reads.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const getRunAgentReplayByRunAgentID = `-- name: GetRunAgentReplayByRunAgentID :one
SELECT
    id,
    run_agent_id,
    artifact_id,
    summary,
    latest_sequence_number,
    event_count,
    created_at,
    updated_at
FROM run_agent_replays
WHERE run_agent_id = $1
LIMIT 1
`

type GetRunAgentReplayByRunAgentIDParams struct {
	RunAgentID uuid.UUID
}

func (q *Queries) GetRunAgentReplayByRunAgentID(ctx context.Context, arg GetRunAgentReplayByRunAgentIDParams) (RunAgentReplay, error) {
	row := q.db.QueryRow(ctx, getRunAgentReplayByRunAgentID, arg.RunAgentID)
	var i RunAgentReplay
	err := row.Scan(
		&i.ID,
		&i.RunAgentID,
		&i.ArtifactID,
		&i.Summary,
		&i.LatestSequenceNumber,
		&i.EventCount,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getRunAgentScorecardByRunAgentID = `-- name: GetRunAgentScorecardByRunAgentID :one
SELECT
    id,
    run_agent_id,
    evaluation_spec_id,
    overall_score,
    correctness_score,
    reliability_score,
    latency_score,
    cost_score,
    behavioral_score,
    scorecard_passed,
    scorecard,
    created_at,
    updated_at
FROM run_agent_scorecards
WHERE run_agent_id = $1
ORDER BY updated_at DESC, id DESC
LIMIT 1
`

type GetRunAgentScorecardByRunAgentIDParams struct {
	RunAgentID uuid.UUID
}

type GetRunAgentScorecardByRunAgentIDRow struct {
	ID               uuid.UUID
	RunAgentID       uuid.UUID
	EvaluationSpecID uuid.UUID
	OverallScore     pgtype.Numeric
	CorrectnessScore pgtype.Numeric
	ReliabilityScore pgtype.Numeric
	LatencyScore     pgtype.Numeric
	CostScore        pgtype.Numeric
	BehavioralScore  pgtype.Numeric
	ScorecardPassed  *bool
	Scorecard        []byte
	CreatedAt        pgtype.Timestamptz
	UpdatedAt        pgtype.Timestamptz
}

func (q *Queries) GetRunAgentScorecardByRunAgentID(ctx context.Context, arg GetRunAgentScorecardByRunAgentIDParams) (GetRunAgentScorecardByRunAgentIDRow, error) {
	row := q.db.QueryRow(ctx, getRunAgentScorecardByRunAgentID, arg.RunAgentID)
	var i GetRunAgentScorecardByRunAgentIDRow
	err := row.Scan(
		&i.ID,
		&i.RunAgentID,
		&i.EvaluationSpecID,
		&i.OverallScore,
		&i.CorrectnessScore,
		&i.ReliabilityScore,
		&i.LatencyScore,
		&i.CostScore,
		&i.BehavioralScore,
		&i.ScorecardPassed,
		&i.Scorecard,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listRunAgentScorecardsByRunID = `-- name: ListRunAgentScorecardsByRunID :many
SELECT DISTINCT ON (sc.run_agent_id)
    sc.id,
    sc.run_agent_id,
    sc.evaluation_spec_id,
    sc.overall_score,
    sc.correctness_score,
    sc.reliability_score,
    sc.latency_score,
    sc.cost_score,
    sc.behavioral_score,
    sc.scorecard_passed,
    sc.scorecard,
    sc.created_at,
    sc.updated_at
FROM run_agent_scorecards sc
JOIN run_agents ra ON ra.id = sc.run_agent_id
WHERE ra.run_id = $1
ORDER BY sc.run_agent_id, sc.updated_at DESC, sc.id DESC
`

type ListRunAgentScorecardsByRunIDParams struct {
	RunID uuid.UUID
}

type ListRunAgentScorecardsByRunIDRow struct {
	ID               uuid.UUID
	RunAgentID       uuid.UUID
	EvaluationSpecID uuid.UUID
	OverallScore     pgtype.Numeric
	CorrectnessScore pgtype.Numeric
	ReliabilityScore pgtype.Numeric
	LatencyScore     pgtype.Numeric
	CostScore        pgtype.Numeric
	BehavioralScore  pgtype.Numeric
	ScorecardPassed  *bool
	Scorecard        []byte
	CreatedAt        pgtype.Timestamptz
	UpdatedAt        pgtype.Timestamptz
}

func (q *Queries) ListRunAgentScorecardsByRunID(ctx context.Context, arg ListRunAgentScorecardsByRunIDParams) ([]ListRunAgentScorecardsByRunIDRow, error) {
	rows, err := q.db.Query(ctx, listRunAgentScorecardsByRunID, arg.RunID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRunAgentScorecardsByRunIDRow
	for rows.Next() {
		var i ListRunAgentScorecardsByRunIDRow
		if err := rows.Scan(
			&i.ID,
			&i.RunAgentID,
			&i.EvaluationSpecID,
			&i.OverallScore,
			&i.CorrectnessScore,
			&i.ReliabilityScore,
			&i.LatencyScore,
			&i.CostScore,
			&i.BehavioralScore,
			&i.ScorecardPassed,
			&i.Scorecard,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertRunAgentReplayIndex = `-- name: UpsertRunAgentReplayIndex :one
INSERT INTO run_agent_replays (
    run_agent_id,
    artifact_id,
    summary,
    latest_sequence_number,
    event_count
)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5
)
ON CONFLICT (run_agent_id) DO UPDATE
SET artifact_id = EXCLUDED.artifact_id,
    summary = EXCLUDED.summary,
    latest_sequence_number = EXCLUDED.latest_sequence_number,
    event_count = EXCLUDED.event_count
RETURNING id, run_agent_id, artifact_id, summary, latest_sequence_number, event_count, created_at, updated_at
`

type UpsertRunAgentReplayIndexParams struct {
	RunAgentID           uuid.UUID
	ArtifactID           *uuid.UUID
	Summary              []byte
	LatestSequenceNumber *int64
	EventCount           int64
}

func (q *Queries) UpsertRunAgentReplayIndex(ctx context.Context, arg UpsertRunAgentReplayIndexParams) (RunAgentReplay, error) {
	row := q.db.QueryRow(ctx, upsertRunAgentReplayIndex,
		arg.RunAgentID,
		arg.ArtifactID,
		arg.Summary,
		arg.LatestSequenceNumber,
		arg.EventCount,
	)
	var i RunAgentReplay
	err := row.Scan(
		&i.ID,
		&i.RunAgentID,
		&i.ArtifactID,
		&i.Summary,
		&i.LatestSequenceNumber,
		&i.EventCount,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
