// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: run_creation.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const getChallengeInputSetByID = `-- name: GetChallengeInputSetByID :one
SELECT id, challenge_pack_version_id, input_key, name, description, input_checksum, generated_at, created_at, updated_at, archived_at
FROM challenge_input_sets
WHERE id = $1
  AND archived_at IS NULL
LIMIT 1
`

type GetChallengeInputSetByIDParams struct {
	ID uuid.UUID
}

type GetChallengeInputSetByIDRow struct {
	ID                     uuid.UUID
	ChallengePackVersionID uuid.UUID
	InputKey               string
	Name                   string
	Description            *string
	InputChecksum          string
	GeneratedAt            pgtype.Timestamptz
	CreatedAt              pgtype.Timestamptz
	UpdatedAt              pgtype.Timestamptz
	ArchivedAt             pgtype.Timestamptz
}

func (q *Queries) GetChallengeInputSetByID(ctx context.Context, arg GetChallengeInputSetByIDParams) (GetChallengeInputSetByIDRow, error) {
	row := q.db.QueryRow(ctx, getChallengeInputSetByID, arg.ID)
	var i GetChallengeInputSetByIDRow
	err := row.Scan(
		&i.ID,
		&i.ChallengePackVersionID,
		&i.InputKey,
		&i.Name,
		&i.Description,
		&i.InputChecksum,
		&i.GeneratedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ArchivedAt,
	)
	return i, err
}

const getRunnableChallengePackVersionByID = `-- name: GetRunnableChallengePackVersionByID :one
SELECT id, challenge_pack_id, version_number, lifecycle_status, manifest_checksum, manifest, published_at, created_at, updated_at, archived_at
FROM challenge_pack_versions
WHERE id = $1
  AND lifecycle_status = 'runnable'
  AND archived_at IS NULL
LIMIT 1
`

type GetRunnableChallengePackVersionByIDParams struct {
	ID uuid.UUID
}

type GetRunnableChallengePackVersionByIDRow struct {
	ID               uuid.UUID
	ChallengePackID  uuid.UUID
	VersionNumber    int32
	LifecycleStatus  string
	ManifestChecksum string
	Manifest         []byte
	PublishedAt      pgtype.Timestamptz
	CreatedAt        pgtype.Timestamptz
	UpdatedAt        pgtype.Timestamptz
	ArchivedAt       pgtype.Timestamptz
}

func (q *Queries) GetRunnableChallengePackVersionByID(ctx context.Context, arg GetRunnableChallengePackVersionByIDParams) (GetRunnableChallengePackVersionByIDRow, error) {
	row := q.db.QueryRow(ctx, getRunnableChallengePackVersionByID, arg.ID)
	var i GetRunnableChallengePackVersionByIDRow
	err := row.Scan(
		&i.ID,
		&i.ChallengePackID,
		&i.VersionNumber,
		&i.LifecycleStatus,
		&i.ManifestChecksum,
		&i.Manifest,
		&i.PublishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ArchivedAt,
	)
	return i, err
}

const listRunnableDeploymentsWithLatestSnapshot = `-- name: ListRunnableDeploymentsWithLatestSnapshot :many
SELECT DISTINCT ON (agent_deployments.id)
    agent_deployments.id,
    agent_deployments.organization_id,
    agent_deployments.workspace_id,
    agent_deployments.name,
    agent_deployment_snapshots.id AS agent_deployment_snapshot_id
FROM agent_deployments
JOIN agent_deployment_snapshots
  ON agent_deployment_snapshots.agent_deployment_id = agent_deployments.id
 AND agent_deployment_snapshots.organization_id = agent_deployments.organization_id
 AND agent_deployment_snapshots.workspace_id = agent_deployments.workspace_id
WHERE agent_deployments.workspace_id = $1
  AND agent_deployments.id = ANY($2::uuid[])
  AND agent_deployments.status = 'active'
  AND agent_deployments.archived_at IS NULL
ORDER BY agent_deployments.id, agent_deployment_snapshots.created_at DESC, agent_deployment_snapshots.id DESC
`

type ListRunnableDeploymentsWithLatestSnapshotParams struct {
	WorkspaceID   uuid.UUID
	DeploymentIds []uuid.UUID
}

type ListRunnableDeploymentsWithLatestSnapshotRow struct {
	ID                        uuid.UUID
	OrganizationID            uuid.UUID
	WorkspaceID               uuid.UUID
	Name                      string
	AgentDeploymentSnapshotID uuid.UUID
}

func (q *Queries) ListRunnableDeploymentsWithLatestSnapshot(ctx context.Context, arg ListRunnableDeploymentsWithLatestSnapshotParams) ([]ListRunnableDeploymentsWithLatestSnapshotRow, error) {
	rows, err := q.db.Query(ctx, listRunnableDeploymentsWithLatestSnapshot, arg.WorkspaceID, arg.DeploymentIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRunnableDeploymentsWithLatestSnapshotRow
	for rows.Next() {
		var i ListRunnableDeploymentsWithLatestSnapshotRow
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.WorkspaceID,
			&i.Name,
			&i.AgentDeploymentSnapshotID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
