// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: run_creation.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const getChallengeInputSetByID = `-- name: GetChallengeInputSetByID :one
SELECT id, challenge_pack_version_id, input_key, name, description, input_checksum, generated_at, created_at, updated_at, archived_at
FROM challenge_input_sets
WHERE id = $1
  AND archived_at IS NULL
LIMIT 1
`

type GetChallengeInputSetByIDParams struct {
	ID uuid.UUID
}

func (q *Queries) GetChallengeInputSetByID(ctx context.Context, arg GetChallengeInputSetByIDParams) (ChallengeInputSet, error) {
	row := q.db.QueryRow(ctx, getChallengeInputSetByID, arg.ID)
	var i ChallengeInputSet
	err := row.Scan(
		&i.ID,
		&i.ChallengePackVersionID,
		&i.InputKey,
		&i.Name,
		&i.Description,
		&i.InputChecksum,
		&i.GeneratedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ArchivedAt,
	)
	return i, err
}

const getRunnableChallengePackVersionByID = `-- name: GetRunnableChallengePackVersionByID :one
SELECT id, challenge_pack_id, version_number, lifecycle_status, manifest_checksum, manifest, published_at, created_at, updated_at, archived_at
FROM challenge_pack_versions
WHERE id = $1
  AND lifecycle_status = 'runnable'
  AND archived_at IS NULL
LIMIT 1
`

type GetRunnableChallengePackVersionByIDParams struct {
	ID uuid.UUID
}

func (q *Queries) GetRunnableChallengePackVersionByID(ctx context.Context, arg GetRunnableChallengePackVersionByIDParams) (ChallengePackVersion, error) {
	row := q.db.QueryRow(ctx, getRunnableChallengePackVersionByID, arg.ID)
	var i ChallengePackVersion
	err := row.Scan(
		&i.ID,
		&i.ChallengePackID,
		&i.VersionNumber,
		&i.LifecycleStatus,
		&i.ManifestChecksum,
		&i.Manifest,
		&i.PublishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ArchivedAt,
	)
	return i, err
}

const listChallengeIdentityIDsByPackVersionID = `-- name: ListChallengeIdentityIDsByPackVersionID :many
SELECT challenge_identity_id
FROM challenge_pack_version_challenges
WHERE challenge_pack_version_id = $1
ORDER BY execution_order ASC, id ASC
`

type ListChallengeIdentityIDsByPackVersionIDParams struct {
	ChallengePackVersionID uuid.UUID
}

func (q *Queries) ListChallengeIdentityIDsByPackVersionID(ctx context.Context, arg ListChallengeIdentityIDsByPackVersionIDParams) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, listChallengeIdentityIDsByPackVersionID, arg.ChallengePackVersionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []uuid.UUID
	for rows.Next() {
		var challenge_identity_id uuid.UUID
		if err := rows.Scan(&challenge_identity_id); err != nil {
			return nil, err
		}
		items = append(items, challenge_identity_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listChallengeInputSetsByVersionID = `-- name: ListChallengeInputSetsByVersionID :many
SELECT id, challenge_pack_version_id, input_key, name
FROM challenge_input_sets
WHERE challenge_pack_version_id = $1
  AND archived_at IS NULL
ORDER BY created_at ASC
`

type ListChallengeInputSetsByVersionIDParams struct {
	ChallengePackVersionID uuid.UUID
}

type ListChallengeInputSetsByVersionIDRow struct {
	ID                     uuid.UUID
	ChallengePackVersionID uuid.UUID
	InputKey               string
	Name                   string
}

func (q *Queries) ListChallengeInputSetsByVersionID(ctx context.Context, arg ListChallengeInputSetsByVersionIDParams) ([]ListChallengeInputSetsByVersionIDRow, error) {
	rows, err := q.db.Query(ctx, listChallengeInputSetsByVersionID, arg.ChallengePackVersionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListChallengeInputSetsByVersionIDRow
	for rows.Next() {
		var i ListChallengeInputSetsByVersionIDRow
		if err := rows.Scan(
			&i.ID,
			&i.ChallengePackVersionID,
			&i.InputKey,
			&i.Name,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRunnableDeploymentsWithLatestSnapshot = `-- name: ListRunnableDeploymentsWithLatestSnapshot :many
SELECT DISTINCT ON (agent_deployments.id)
    agent_deployments.id,
    agent_deployments.organization_id,
    agent_deployments.workspace_id,
    agent_deployments.name,
    agent_deployment_snapshots.id AS agent_deployment_snapshot_id,
    agent_deployments.spend_policy_id,
    agent_deployments.routing_policy_id
FROM agent_deployments
JOIN agent_deployment_snapshots
  ON agent_deployment_snapshots.agent_deployment_id = agent_deployments.id
 AND agent_deployment_snapshots.organization_id = agent_deployments.organization_id
 AND agent_deployment_snapshots.workspace_id = agent_deployments.workspace_id
WHERE agent_deployments.workspace_id = $1
  AND agent_deployments.id = ANY($2::uuid[])
  AND agent_deployments.status = 'active'
  AND agent_deployments.archived_at IS NULL
ORDER BY agent_deployments.id, agent_deployment_snapshots.created_at DESC, agent_deployment_snapshots.id DESC
`

type ListRunnableDeploymentsWithLatestSnapshotParams struct {
	WorkspaceID   uuid.UUID
	DeploymentIds []uuid.UUID
}

type ListRunnableDeploymentsWithLatestSnapshotRow struct {
	ID                        uuid.UUID
	OrganizationID            uuid.UUID
	WorkspaceID               uuid.UUID
	Name                      string
	AgentDeploymentSnapshotID uuid.UUID
	SpendPolicyID             *uuid.UUID
	RoutingPolicyID           *uuid.UUID
}

func (q *Queries) ListRunnableDeploymentsWithLatestSnapshot(ctx context.Context, arg ListRunnableDeploymentsWithLatestSnapshotParams) ([]ListRunnableDeploymentsWithLatestSnapshotRow, error) {
	rows, err := q.db.Query(ctx, listRunnableDeploymentsWithLatestSnapshot, arg.WorkspaceID, arg.DeploymentIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRunnableDeploymentsWithLatestSnapshotRow
	for rows.Next() {
		var i ListRunnableDeploymentsWithLatestSnapshotRow
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.WorkspaceID,
			&i.Name,
			&i.AgentDeploymentSnapshotID,
			&i.SpendPolicyID,
			&i.RoutingPolicyID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
