// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: run_comparisons.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const getRunComparisonByRunIDs = `-- name: GetRunComparisonByRunIDs :one
SELECT
    id,
    baseline_run_id,
    candidate_run_id,
    baseline_run_agent_id,
    candidate_run_agent_id,
    status,
    reason_code,
    source_fingerprint,
    summary,
    created_at,
    updated_at
FROM run_comparisons
WHERE baseline_run_id = $1
  AND candidate_run_id = $2
LIMIT 1
`

type GetRunComparisonByRunIDsParams struct {
	BaselineRunID  uuid.UUID
	CandidateRunID uuid.UUID
}

func (q *Queries) GetRunComparisonByRunIDs(ctx context.Context, arg GetRunComparisonByRunIDsParams) (RunComparison, error) {
	row := q.db.QueryRow(ctx, getRunComparisonByRunIDs, arg.BaselineRunID, arg.CandidateRunID)
	var i RunComparison
	err := row.Scan(
		&i.ID,
		&i.BaselineRunID,
		&i.CandidateRunID,
		&i.BaselineRunAgentID,
		&i.CandidateRunAgentID,
		&i.Status,
		&i.ReasonCode,
		&i.SourceFingerprint,
		&i.Summary,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertRunComparison = `-- name: UpsertRunComparison :one
INSERT INTO run_comparisons (
    baseline_run_id,
    candidate_run_id,
    baseline_run_agent_id,
    candidate_run_agent_id,
    status,
    reason_code,
    source_fingerprint,
    summary
)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8
)
ON CONFLICT (baseline_run_id, candidate_run_id)
DO UPDATE SET
    baseline_run_agent_id = EXCLUDED.baseline_run_agent_id,
    candidate_run_agent_id = EXCLUDED.candidate_run_agent_id,
    status = EXCLUDED.status,
    reason_code = EXCLUDED.reason_code,
    source_fingerprint = EXCLUDED.source_fingerprint,
    summary = EXCLUDED.summary
RETURNING
    id,
    baseline_run_id,
    candidate_run_id,
    baseline_run_agent_id,
    candidate_run_agent_id,
    status,
    reason_code,
    source_fingerprint,
    summary,
    created_at,
    updated_at
`

type UpsertRunComparisonParams struct {
	BaselineRunID       uuid.UUID
	CandidateRunID      uuid.UUID
	BaselineRunAgentID  *uuid.UUID
	CandidateRunAgentID *uuid.UUID
	Status              string
	ReasonCode          *string
	SourceFingerprint   string
	Summary             []byte
}

func (q *Queries) UpsertRunComparison(ctx context.Context, arg UpsertRunComparisonParams) (RunComparison, error) {
	row := q.db.QueryRow(ctx, upsertRunComparison,
		arg.BaselineRunID,
		arg.CandidateRunID,
		arg.BaselineRunAgentID,
		arg.CandidateRunAgentID,
		arg.Status,
		arg.ReasonCode,
		arg.SourceFingerprint,
		arg.Summary,
	)
	var i RunComparison
	err := row.Scan(
		&i.ID,
		&i.BaselineRunID,
		&i.CandidateRunID,
		&i.BaselineRunAgentID,
		&i.CandidateRunAgentID,
		&i.Status,
		&i.ReasonCode,
		&i.SourceFingerprint,
		&i.Summary,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
