// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: run_events.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const insertRunEvent = `-- name: InsertRunEvent :one
WITH next_sequence AS (
    SELECT COALESCE(MAX(sequence_number), 0) + 1 AS sequence_number
    FROM run_events
    WHERE run_agent_id = $2
)
INSERT INTO run_events (
    run_id,
    run_agent_id,
    sequence_number,
    event_type,
    actor_type,
    occurred_at,
    payload
)
SELECT
    $1,
    $2,
    next_sequence.sequence_number,
    $3,
    $4,
    $5,
    $6
FROM next_sequence
RETURNING id, run_id, run_agent_id, sequence_number, event_type, actor_type, occurred_at, artifact_id, payload
`

type InsertRunEventParams struct {
	RunID      uuid.UUID
	RunAgentID uuid.UUID
	EventType  string
	ActorType  string
	OccurredAt pgtype.Timestamptz
	Payload    []byte
}

func (q *Queries) InsertRunEvent(ctx context.Context, arg InsertRunEventParams) (RunEvent, error) {
	row := q.db.QueryRow(ctx, insertRunEvent,
		arg.RunID,
		arg.RunAgentID,
		arg.EventType,
		arg.ActorType,
		arg.OccurredAt,
		arg.Payload,
	)
	var i RunEvent
	err := row.Scan(
		&i.ID,
		&i.RunID,
		&i.RunAgentID,
		&i.SequenceNumber,
		&i.EventType,
		&i.ActorType,
		&i.OccurredAt,
		&i.ArtifactID,
		&i.Payload,
	)
	return i, err
}

const listRunEventsByRunAgentID = `-- name: ListRunEventsByRunAgentID :many
SELECT id, run_id, run_agent_id, sequence_number, event_type, actor_type, occurred_at, artifact_id, payload
FROM run_events
WHERE run_agent_id = $1
ORDER BY sequence_number ASC
`

type ListRunEventsByRunAgentIDParams struct {
	RunAgentID uuid.UUID
}

func (q *Queries) ListRunEventsByRunAgentID(ctx context.Context, arg ListRunEventsByRunAgentIDParams) ([]RunEvent, error) {
	rows, err := q.db.Query(ctx, listRunEventsByRunAgentID, arg.RunAgentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RunEvent
	for rows.Next() {
		var i RunEvent
		if err := rows.Scan(
			&i.ID,
			&i.RunID,
			&i.RunAgentID,
			&i.SequenceNumber,
			&i.EventType,
			&i.ActorType,
			&i.OccurredAt,
			&i.ArtifactID,
			&i.Payload,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
