// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: run_agents.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createRunAgent = `-- name: CreateRunAgent :one
INSERT INTO run_agents (
    organization_id,
    workspace_id,
    run_id,
    agent_deployment_id,
    agent_deployment_snapshot_id,
    lane_index,
    label,
    status,
    queued_at,
    started_at,
    finished_at,
    failure_reason
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9,
    $10,
    $11,
    $12
)
RETURNING id, organization_id, workspace_id, run_id, agent_deployment_id, agent_deployment_snapshot_id, lane_index, label, status, queued_at, started_at, finished_at, failure_reason, created_at, updated_at
`

type CreateRunAgentParams struct {
	OrganizationID            uuid.UUID
	WorkspaceID               uuid.UUID
	RunID                     uuid.UUID
	AgentDeploymentID         uuid.UUID
	AgentDeploymentSnapshotID uuid.UUID
	LaneIndex                 int32
	Label                     string
	Status                    string
	QueuedAt                  pgtype.Timestamptz
	StartedAt                 pgtype.Timestamptz
	FinishedAt                pgtype.Timestamptz
	FailureReason             *string
}

func (q *Queries) CreateRunAgent(ctx context.Context, arg CreateRunAgentParams) (RunAgent, error) {
	row := q.db.QueryRow(ctx, createRunAgent,
		arg.OrganizationID,
		arg.WorkspaceID,
		arg.RunID,
		arg.AgentDeploymentID,
		arg.AgentDeploymentSnapshotID,
		arg.LaneIndex,
		arg.Label,
		arg.Status,
		arg.QueuedAt,
		arg.StartedAt,
		arg.FinishedAt,
		arg.FailureReason,
	)
	var i RunAgent
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.WorkspaceID,
		&i.RunID,
		&i.AgentDeploymentID,
		&i.AgentDeploymentSnapshotID,
		&i.LaneIndex,
		&i.Label,
		&i.Status,
		&i.QueuedAt,
		&i.StartedAt,
		&i.FinishedAt,
		&i.FailureReason,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getRunAgentByID = `-- name: GetRunAgentByID :one
SELECT id, organization_id, workspace_id, run_id, agent_deployment_id, agent_deployment_snapshot_id, lane_index, label, status, queued_at, started_at, finished_at, failure_reason, created_at, updated_at
FROM run_agents
WHERE id = $1
LIMIT 1
`

type GetRunAgentByIDParams struct {
	ID uuid.UUID
}

func (q *Queries) GetRunAgentByID(ctx context.Context, arg GetRunAgentByIDParams) (RunAgent, error) {
	row := q.db.QueryRow(ctx, getRunAgentByID, arg.ID)
	var i RunAgent
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.WorkspaceID,
		&i.RunID,
		&i.AgentDeploymentID,
		&i.AgentDeploymentSnapshotID,
		&i.LaneIndex,
		&i.Label,
		&i.Status,
		&i.QueuedAt,
		&i.StartedAt,
		&i.FinishedAt,
		&i.FailureReason,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertRunAgentStatusHistory = `-- name: InsertRunAgentStatusHistory :one
INSERT INTO run_agent_status_history (
    run_agent_id,
    from_status,
    to_status,
    reason
) VALUES (
    $1,
    $2,
    $3,
    $4
)
RETURNING id, run_agent_id, from_status, to_status, reason, changed_at
`

type InsertRunAgentStatusHistoryParams struct {
	RunAgentID uuid.UUID
	FromStatus *string
	ToStatus   string
	Reason     *string
}

func (q *Queries) InsertRunAgentStatusHistory(ctx context.Context, arg InsertRunAgentStatusHistoryParams) (RunAgentStatusHistory, error) {
	row := q.db.QueryRow(ctx, insertRunAgentStatusHistory,
		arg.RunAgentID,
		arg.FromStatus,
		arg.ToStatus,
		arg.Reason,
	)
	var i RunAgentStatusHistory
	err := row.Scan(
		&i.ID,
		&i.RunAgentID,
		&i.FromStatus,
		&i.ToStatus,
		&i.Reason,
		&i.ChangedAt,
	)
	return i, err
}

const listRunAgentStatusHistoryByRunAgentID = `-- name: ListRunAgentStatusHistoryByRunAgentID :many
SELECT id, run_agent_id, from_status, to_status, reason, changed_at
FROM run_agent_status_history
WHERE run_agent_id = $1
ORDER BY changed_at ASC, id ASC
`

type ListRunAgentStatusHistoryByRunAgentIDParams struct {
	RunAgentID uuid.UUID
}

func (q *Queries) ListRunAgentStatusHistoryByRunAgentID(ctx context.Context, arg ListRunAgentStatusHistoryByRunAgentIDParams) ([]RunAgentStatusHistory, error) {
	rows, err := q.db.Query(ctx, listRunAgentStatusHistoryByRunAgentID, arg.RunAgentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RunAgentStatusHistory
	for rows.Next() {
		var i RunAgentStatusHistory
		if err := rows.Scan(
			&i.ID,
			&i.RunAgentID,
			&i.FromStatus,
			&i.ToStatus,
			&i.Reason,
			&i.ChangedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRunAgentsByRunID = `-- name: ListRunAgentsByRunID :many
SELECT id, organization_id, workspace_id, run_id, agent_deployment_id, agent_deployment_snapshot_id, lane_index, label, status, queued_at, started_at, finished_at, failure_reason, created_at, updated_at
FROM run_agents
WHERE run_id = $1
ORDER BY lane_index ASC
`

type ListRunAgentsByRunIDParams struct {
	RunID uuid.UUID
}

func (q *Queries) ListRunAgentsByRunID(ctx context.Context, arg ListRunAgentsByRunIDParams) ([]RunAgent, error) {
	rows, err := q.db.Query(ctx, listRunAgentsByRunID, arg.RunID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RunAgent
	for rows.Next() {
		var i RunAgent
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.WorkspaceID,
			&i.RunID,
			&i.AgentDeploymentID,
			&i.AgentDeploymentSnapshotID,
			&i.LaneIndex,
			&i.Label,
			&i.Status,
			&i.QueuedAt,
			&i.StartedAt,
			&i.FinishedAt,
			&i.FailureReason,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateRunAgentStatus = `-- name: UpdateRunAgentStatus :one
UPDATE run_agents
SET status = $1,
    started_at = CASE
        WHEN $1::text = 'executing' AND started_at IS NULL THEN now()
        ELSE started_at
    END,
    finished_at = CASE
        WHEN $1::text IN ('completed', 'failed') AND finished_at IS NULL THEN now()
        ELSE finished_at
    END,
    failure_reason = CASE
        WHEN $1::text = 'failed' THEN $2
        ELSE failure_reason
    END
WHERE id = $3
  AND status = $4
RETURNING id, organization_id, workspace_id, run_id, agent_deployment_id, agent_deployment_snapshot_id, lane_index, label, status, queued_at, started_at, finished_at, failure_reason, created_at, updated_at
`

type UpdateRunAgentStatusParams struct {
	ToStatus      string
	FailureReason *string
	ID            uuid.UUID
	FromStatus    string
}

func (q *Queries) UpdateRunAgentStatus(ctx context.Context, arg UpdateRunAgentStatusParams) (RunAgent, error) {
	row := q.db.QueryRow(ctx, updateRunAgentStatus,
		arg.ToStatus,
		arg.FailureReason,
		arg.ID,
		arg.FromStatus,
	)
	var i RunAgent
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.WorkspaceID,
		&i.RunID,
		&i.AgentDeploymentID,
		&i.AgentDeploymentSnapshotID,
		&i.LaneIndex,
		&i.Label,
		&i.Status,
		&i.QueuedAt,
		&i.StartedAt,
		&i.FinishedAt,
		&i.FailureReason,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
