// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: runs.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createRun = `-- name: CreateRun :one
INSERT INTO runs (
    organization_id,
    workspace_id,
    challenge_pack_version_id,
    challenge_input_set_id,
    created_by_user_id,
    name,
    status,
    execution_mode,
    temporal_workflow_id,
    temporal_run_id,
    execution_plan,
    queued_at,
    started_at,
    finished_at,
    cancelled_at,
    failed_at
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9,
    $10,
    $11,
    $12,
    $13,
    $14,
    $15,
    $16
)
RETURNING id, organization_id, workspace_id, challenge_pack_version_id, challenge_input_set_id, created_by_user_id, name, status, execution_mode, temporal_workflow_id, temporal_run_id, execution_plan, queued_at, started_at, finished_at, cancelled_at, failed_at, created_at, updated_at
`

type CreateRunParams struct {
	OrganizationID         uuid.UUID
	WorkspaceID            uuid.UUID
	ChallengePackVersionID uuid.UUID
	ChallengeInputSetID    *uuid.UUID
	CreatedByUserID        *uuid.UUID
	Name                   string
	Status                 string
	ExecutionMode          string
	TemporalWorkflowID     *string
	TemporalRunID          *string
	ExecutionPlan          []byte
	QueuedAt               pgtype.Timestamptz
	StartedAt              pgtype.Timestamptz
	FinishedAt             pgtype.Timestamptz
	CancelledAt            pgtype.Timestamptz
	FailedAt               pgtype.Timestamptz
}

func (q *Queries) CreateRun(ctx context.Context, arg CreateRunParams) (Run, error) {
	row := q.db.QueryRow(ctx, createRun,
		arg.OrganizationID,
		arg.WorkspaceID,
		arg.ChallengePackVersionID,
		arg.ChallengeInputSetID,
		arg.CreatedByUserID,
		arg.Name,
		arg.Status,
		arg.ExecutionMode,
		arg.TemporalWorkflowID,
		arg.TemporalRunID,
		arg.ExecutionPlan,
		arg.QueuedAt,
		arg.StartedAt,
		arg.FinishedAt,
		arg.CancelledAt,
		arg.FailedAt,
	)
	var i Run
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.WorkspaceID,
		&i.ChallengePackVersionID,
		&i.ChallengeInputSetID,
		&i.CreatedByUserID,
		&i.Name,
		&i.Status,
		&i.ExecutionMode,
		&i.TemporalWorkflowID,
		&i.TemporalRunID,
		&i.ExecutionPlan,
		&i.QueuedAt,
		&i.StartedAt,
		&i.FinishedAt,
		&i.CancelledAt,
		&i.FailedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getRunByID = `-- name: GetRunByID :one
SELECT id, organization_id, workspace_id, challenge_pack_version_id, challenge_input_set_id, created_by_user_id, name, status, execution_mode, temporal_workflow_id, temporal_run_id, execution_plan, queued_at, started_at, finished_at, cancelled_at, failed_at, created_at, updated_at
FROM runs
WHERE id = $1
LIMIT 1
`

type GetRunByIDParams struct {
	ID uuid.UUID
}

func (q *Queries) GetRunByID(ctx context.Context, arg GetRunByIDParams) (Run, error) {
	row := q.db.QueryRow(ctx, getRunByID, arg.ID)
	var i Run
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.WorkspaceID,
		&i.ChallengePackVersionID,
		&i.ChallengeInputSetID,
		&i.CreatedByUserID,
		&i.Name,
		&i.Status,
		&i.ExecutionMode,
		&i.TemporalWorkflowID,
		&i.TemporalRunID,
		&i.ExecutionPlan,
		&i.QueuedAt,
		&i.StartedAt,
		&i.FinishedAt,
		&i.CancelledAt,
		&i.FailedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertRunStatusHistory = `-- name: InsertRunStatusHistory :one
INSERT INTO run_status_history (
    run_id,
    from_status,
    to_status,
    reason,
    changed_by_user_id
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5
)
RETURNING id, run_id, from_status, to_status, reason, changed_by_user_id, changed_at
`

type InsertRunStatusHistoryParams struct {
	RunID           uuid.UUID
	FromStatus      *string
	ToStatus        string
	Reason          *string
	ChangedByUserID *uuid.UUID
}

func (q *Queries) InsertRunStatusHistory(ctx context.Context, arg InsertRunStatusHistoryParams) (RunStatusHistory, error) {
	row := q.db.QueryRow(ctx, insertRunStatusHistory,
		arg.RunID,
		arg.FromStatus,
		arg.ToStatus,
		arg.Reason,
		arg.ChangedByUserID,
	)
	var i RunStatusHistory
	err := row.Scan(
		&i.ID,
		&i.RunID,
		&i.FromStatus,
		&i.ToStatus,
		&i.Reason,
		&i.ChangedByUserID,
		&i.ChangedAt,
	)
	return i, err
}

const listRunStatusHistoryByRunID = `-- name: ListRunStatusHistoryByRunID :many
SELECT id, run_id, from_status, to_status, reason, changed_by_user_id, changed_at
FROM run_status_history
WHERE run_id = $1
ORDER BY changed_at ASC, id ASC
`

type ListRunStatusHistoryByRunIDParams struct {
	RunID uuid.UUID
}

func (q *Queries) ListRunStatusHistoryByRunID(ctx context.Context, arg ListRunStatusHistoryByRunIDParams) ([]RunStatusHistory, error) {
	rows, err := q.db.Query(ctx, listRunStatusHistoryByRunID, arg.RunID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RunStatusHistory
	for rows.Next() {
		var i RunStatusHistory
		if err := rows.Scan(
			&i.ID,
			&i.RunID,
			&i.FromStatus,
			&i.ToStatus,
			&i.Reason,
			&i.ChangedByUserID,
			&i.ChangedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setRunTemporalIDs = `-- name: SetRunTemporalIDs :one
UPDATE runs
SET temporal_workflow_id = $1,
    temporal_run_id = $2
WHERE id = $3
  AND temporal_workflow_id IS NULL
  AND temporal_run_id IS NULL
RETURNING id, organization_id, workspace_id, challenge_pack_version_id, challenge_input_set_id, created_by_user_id, name, status, execution_mode, temporal_workflow_id, temporal_run_id, execution_plan, queued_at, started_at, finished_at, cancelled_at, failed_at, created_at, updated_at
`

type SetRunTemporalIDsParams struct {
	TemporalWorkflowID *string
	TemporalRunID      *string
	ID                 uuid.UUID
}

func (q *Queries) SetRunTemporalIDs(ctx context.Context, arg SetRunTemporalIDsParams) (Run, error) {
	row := q.db.QueryRow(ctx, setRunTemporalIDs, arg.TemporalWorkflowID, arg.TemporalRunID, arg.ID)
	var i Run
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.WorkspaceID,
		&i.ChallengePackVersionID,
		&i.ChallengeInputSetID,
		&i.CreatedByUserID,
		&i.Name,
		&i.Status,
		&i.ExecutionMode,
		&i.TemporalWorkflowID,
		&i.TemporalRunID,
		&i.ExecutionPlan,
		&i.QueuedAt,
		&i.StartedAt,
		&i.FinishedAt,
		&i.CancelledAt,
		&i.FailedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateRunStatus = `-- name: UpdateRunStatus :one
UPDATE runs
SET status = $1,
    queued_at = CASE
        WHEN $1::text = 'queued' AND queued_at IS NULL THEN now()
        ELSE queued_at
    END,
    started_at = CASE
        WHEN $1::text = 'provisioning' AND started_at IS NULL THEN now()
        ELSE started_at
    END,
    finished_at = CASE
        WHEN $1::text IN ('completed', 'failed', 'cancelled') AND finished_at IS NULL THEN now()
        ELSE finished_at
    END,
    cancelled_at = CASE
        WHEN $1::text = 'cancelled' AND cancelled_at IS NULL THEN now()
        ELSE cancelled_at
    END,
    failed_at = CASE
        WHEN $1::text = 'failed' AND failed_at IS NULL THEN now()
        ELSE failed_at
    END
WHERE id = $2
  AND status = $3
RETURNING id, organization_id, workspace_id, challenge_pack_version_id, challenge_input_set_id, created_by_user_id, name, status, execution_mode, temporal_workflow_id, temporal_run_id, execution_plan, queued_at, started_at, finished_at, cancelled_at, failed_at, created_at, updated_at
`

type UpdateRunStatusParams struct {
	ToStatus   string
	ID         uuid.UUID
	FromStatus string
}

func (q *Queries) UpdateRunStatus(ctx context.Context, arg UpdateRunStatusParams) (Run, error) {
	row := q.db.QueryRow(ctx, updateRunStatus, arg.ToStatus, arg.ID, arg.FromStatus)
	var i Run
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.WorkspaceID,
		&i.ChallengePackVersionID,
		&i.ChallengeInputSetID,
		&i.CreatedByUserID,
		&i.Name,
		&i.Status,
		&i.ExecutionMode,
		&i.TemporalWorkflowID,
		&i.TemporalRunID,
		&i.ExecutionPlan,
		&i.QueuedAt,
		&i.StartedAt,
		&i.FinishedAt,
		&i.CancelledAt,
		&i.FailedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
