// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: runs.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countRunsByWorkspaceID = `-- name: CountRunsByWorkspaceID :one
SELECT count(*)
FROM runs
WHERE workspace_id = $1
`

type CountRunsByWorkspaceIDParams struct {
	WorkspaceID uuid.UUID
}

func (q *Queries) CountRunsByWorkspaceID(ctx context.Context, arg CountRunsByWorkspaceIDParams) (int64, error) {
	row := q.db.QueryRow(ctx, countRunsByWorkspaceID, arg.WorkspaceID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createRun = `-- name: CreateRun :one
INSERT INTO runs (
    organization_id,
    workspace_id,
    challenge_pack_version_id,
    challenge_input_set_id,
    official_pack_mode,
    created_by_user_id,
    name,
    status,
    execution_mode,
    temporal_workflow_id,
    temporal_run_id,
    execution_plan,
    queued_at,
    started_at,
    finished_at,
    cancelled_at,
    failed_at
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9,
    $10,
    $11,
    $12,
    $13,
    $14,
    $15,
    $16,
    $17
)
RETURNING id, organization_id, workspace_id, challenge_pack_version_id, challenge_input_set_id, created_by_user_id, name, status, execution_mode, temporal_workflow_id, temporal_run_id, execution_plan, queued_at, started_at, finished_at, cancelled_at, failed_at, created_at, updated_at, official_pack_mode
`

type CreateRunParams struct {
	OrganizationID         uuid.UUID
	WorkspaceID            uuid.UUID
	ChallengePackVersionID uuid.UUID
	ChallengeInputSetID    *uuid.UUID
	OfficialPackMode       string
	CreatedByUserID        *uuid.UUID
	Name                   string
	Status                 string
	ExecutionMode          string
	TemporalWorkflowID     *string
	TemporalRunID          *string
	ExecutionPlan          []byte
	QueuedAt               pgtype.Timestamptz
	StartedAt              pgtype.Timestamptz
	FinishedAt             pgtype.Timestamptz
	CancelledAt            pgtype.Timestamptz
	FailedAt               pgtype.Timestamptz
}

func (q *Queries) CreateRun(ctx context.Context, arg CreateRunParams) (Run, error) {
	row := q.db.QueryRow(ctx, createRun,
		arg.OrganizationID,
		arg.WorkspaceID,
		arg.ChallengePackVersionID,
		arg.ChallengeInputSetID,
		arg.OfficialPackMode,
		arg.CreatedByUserID,
		arg.Name,
		arg.Status,
		arg.ExecutionMode,
		arg.TemporalWorkflowID,
		arg.TemporalRunID,
		arg.ExecutionPlan,
		arg.QueuedAt,
		arg.StartedAt,
		arg.FinishedAt,
		arg.CancelledAt,
		arg.FailedAt,
	)
	var i Run
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.WorkspaceID,
		&i.ChallengePackVersionID,
		&i.ChallengeInputSetID,
		&i.CreatedByUserID,
		&i.Name,
		&i.Status,
		&i.ExecutionMode,
		&i.TemporalWorkflowID,
		&i.TemporalRunID,
		&i.ExecutionPlan,
		&i.QueuedAt,
		&i.StartedAt,
		&i.FinishedAt,
		&i.CancelledAt,
		&i.FailedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.OfficialPackMode,
	)
	return i, err
}

const createRunCaseSelection = `-- name: CreateRunCaseSelection :one
INSERT INTO run_case_selections (
    run_id,
    challenge_identity_id,
    selection_origin,
    regression_case_id,
    selection_rank
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5
)
RETURNING id, run_id, challenge_identity_id, selection_origin, regression_case_id, selection_rank, created_at
`

type CreateRunCaseSelectionParams struct {
	RunID               uuid.UUID
	ChallengeIdentityID uuid.UUID
	SelectionOrigin     string
	RegressionCaseID    *uuid.UUID
	SelectionRank       int32
}

func (q *Queries) CreateRunCaseSelection(ctx context.Context, arg CreateRunCaseSelectionParams) (RunCaseSelection, error) {
	row := q.db.QueryRow(ctx, createRunCaseSelection,
		arg.RunID,
		arg.ChallengeIdentityID,
		arg.SelectionOrigin,
		arg.RegressionCaseID,
		arg.SelectionRank,
	)
	var i RunCaseSelection
	err := row.Scan(
		&i.ID,
		&i.RunID,
		&i.ChallengeIdentityID,
		&i.SelectionOrigin,
		&i.RegressionCaseID,
		&i.SelectionRank,
		&i.CreatedAt,
	)
	return i, err
}

const getRunByID = `-- name: GetRunByID :one
SELECT id, organization_id, workspace_id, challenge_pack_version_id, challenge_input_set_id, created_by_user_id, name, status, execution_mode, temporal_workflow_id, temporal_run_id, execution_plan, queued_at, started_at, finished_at, cancelled_at, failed_at, created_at, updated_at, official_pack_mode
FROM runs
WHERE id = $1
LIMIT 1
`

type GetRunByIDParams struct {
	ID uuid.UUID
}

func (q *Queries) GetRunByID(ctx context.Context, arg GetRunByIDParams) (Run, error) {
	row := q.db.QueryRow(ctx, getRunByID, arg.ID)
	var i Run
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.WorkspaceID,
		&i.ChallengePackVersionID,
		&i.ChallengeInputSetID,
		&i.CreatedByUserID,
		&i.Name,
		&i.Status,
		&i.ExecutionMode,
		&i.TemporalWorkflowID,
		&i.TemporalRunID,
		&i.ExecutionPlan,
		&i.QueuedAt,
		&i.StartedAt,
		&i.FinishedAt,
		&i.CancelledAt,
		&i.FailedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.OfficialPackMode,
	)
	return i, err
}

const insertRunStatusHistory = `-- name: InsertRunStatusHistory :one
INSERT INTO run_status_history (
    run_id,
    from_status,
    to_status,
    reason,
    changed_by_user_id
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5
)
RETURNING id, run_id, from_status, to_status, reason, changed_by_user_id, changed_at
`

type InsertRunStatusHistoryParams struct {
	RunID           uuid.UUID
	FromStatus      *string
	ToStatus        string
	Reason          *string
	ChangedByUserID *uuid.UUID
}

func (q *Queries) InsertRunStatusHistory(ctx context.Context, arg InsertRunStatusHistoryParams) (RunStatusHistory, error) {
	row := q.db.QueryRow(ctx, insertRunStatusHistory,
		arg.RunID,
		arg.FromStatus,
		arg.ToStatus,
		arg.Reason,
		arg.ChangedByUserID,
	)
	var i RunStatusHistory
	err := row.Scan(
		&i.ID,
		&i.RunID,
		&i.FromStatus,
		&i.ToStatus,
		&i.Reason,
		&i.ChangedByUserID,
		&i.ChangedAt,
	)
	return i, err
}

const listRunCaseSelectionsByRunID = `-- name: ListRunCaseSelectionsByRunID :many
SELECT id, run_id, challenge_identity_id, selection_origin, regression_case_id, selection_rank, created_at
FROM run_case_selections
WHERE run_id = $1
ORDER BY selection_rank ASC, created_at ASC, challenge_identity_id ASC
`

type ListRunCaseSelectionsByRunIDParams struct {
	RunID uuid.UUID
}

func (q *Queries) ListRunCaseSelectionsByRunID(ctx context.Context, arg ListRunCaseSelectionsByRunIDParams) ([]RunCaseSelection, error) {
	rows, err := q.db.Query(ctx, listRunCaseSelectionsByRunID, arg.RunID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RunCaseSelection
	for rows.Next() {
		var i RunCaseSelection
		if err := rows.Scan(
			&i.ID,
			&i.RunID,
			&i.ChallengeIdentityID,
			&i.SelectionOrigin,
			&i.RegressionCaseID,
			&i.SelectionRank,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRunRegressionCoverageCasesByRunID = `-- name: ListRunRegressionCoverageCasesByRunID :many
WITH winning_run_agent AS (
    SELECT winning_run_agent_id
    FROM run_scorecards
    WHERE run_scorecards.run_id = $1
    ORDER BY created_at DESC
    LIMIT 1
),
selected_regression_cases AS (
    SELECT DISTINCT ON (rcs.regression_case_id)
        rcs.regression_case_id,
        c.title AS regression_case_title,
        s.id AS suite_id,
        s.name AS suite_name
    FROM run_case_selections AS rcs
    LEFT JOIN workspace_regression_cases AS c
      ON c.id = rcs.regression_case_id
    LEFT JOIN workspace_regression_suites AS s
      ON s.id = c.suite_id
    WHERE rcs.run_id = $1
      AND rcs.regression_case_id IS NOT NULL
    ORDER BY rcs.regression_case_id, rcs.selection_rank ASC, rcs.created_at ASC
),
winning_case_outcomes AS (
    SELECT
        jr.regression_case_id,
        CASE
            WHEN bool_or(jr.verdict = 'fail') THEN 'fail'
            WHEN bool_or(jr.verdict = 'pass') THEN 'pass'
            ELSE 'pending'
        END AS outcome
    FROM judge_results AS jr
    JOIN winning_run_agent AS wra
      ON jr.run_agent_id = wra.winning_run_agent_id
    WHERE jr.regression_case_id IS NOT NULL
    GROUP BY jr.regression_case_id
)
SELECT
    src.regression_case_id,
    src.regression_case_title,
    src.suite_id,
    src.suite_name,
    COALESCE(wco.outcome, 'pending') AS outcome
FROM selected_regression_cases AS src
LEFT JOIN winning_case_outcomes AS wco
  ON wco.regression_case_id = src.regression_case_id
ORDER BY src.suite_name ASC NULLS LAST, src.regression_case_title ASC, src.regression_case_id ASC
`

type ListRunRegressionCoverageCasesByRunIDParams struct {
	RunID uuid.UUID
}

type ListRunRegressionCoverageCasesByRunIDRow struct {
	RegressionCaseID    *uuid.UUID
	RegressionCaseTitle *string
	SuiteID             *uuid.UUID
	SuiteName           *string
	Outcome             string
}

func (q *Queries) ListRunRegressionCoverageCasesByRunID(ctx context.Context, arg ListRunRegressionCoverageCasesByRunIDParams) ([]ListRunRegressionCoverageCasesByRunIDRow, error) {
	rows, err := q.db.Query(ctx, listRunRegressionCoverageCasesByRunID, arg.RunID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRunRegressionCoverageCasesByRunIDRow
	for rows.Next() {
		var i ListRunRegressionCoverageCasesByRunIDRow
		if err := rows.Scan(
			&i.RegressionCaseID,
			&i.RegressionCaseTitle,
			&i.SuiteID,
			&i.SuiteName,
			&i.Outcome,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRunStatusHistoryByRunID = `-- name: ListRunStatusHistoryByRunID :many
SELECT id, run_id, from_status, to_status, reason, changed_by_user_id, changed_at
FROM run_status_history
WHERE run_id = $1
ORDER BY changed_at ASC, id ASC
`

type ListRunStatusHistoryByRunIDParams struct {
	RunID uuid.UUID
}

func (q *Queries) ListRunStatusHistoryByRunID(ctx context.Context, arg ListRunStatusHistoryByRunIDParams) ([]RunStatusHistory, error) {
	rows, err := q.db.Query(ctx, listRunStatusHistoryByRunID, arg.RunID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RunStatusHistory
	for rows.Next() {
		var i RunStatusHistory
		if err := rows.Scan(
			&i.ID,
			&i.RunID,
			&i.FromStatus,
			&i.ToStatus,
			&i.Reason,
			&i.ChangedByUserID,
			&i.ChangedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRunsByWorkspaceID = `-- name: ListRunsByWorkspaceID :many
SELECT id, organization_id, workspace_id, challenge_pack_version_id, challenge_input_set_id, created_by_user_id, name, status, execution_mode, temporal_workflow_id, temporal_run_id, execution_plan, queued_at, started_at, finished_at, cancelled_at, failed_at, created_at, updated_at, official_pack_mode
FROM runs
WHERE workspace_id = $1
ORDER BY created_at DESC
LIMIT $3 OFFSET $2
`

type ListRunsByWorkspaceIDParams struct {
	WorkspaceID  uuid.UUID
	ResultOffset int32
	ResultLimit  int32
}

func (q *Queries) ListRunsByWorkspaceID(ctx context.Context, arg ListRunsByWorkspaceIDParams) ([]Run, error) {
	rows, err := q.db.Query(ctx, listRunsByWorkspaceID, arg.WorkspaceID, arg.ResultOffset, arg.ResultLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Run
	for rows.Next() {
		var i Run
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.WorkspaceID,
			&i.ChallengePackVersionID,
			&i.ChallengeInputSetID,
			&i.CreatedByUserID,
			&i.Name,
			&i.Status,
			&i.ExecutionMode,
			&i.TemporalWorkflowID,
			&i.TemporalRunID,
			&i.ExecutionPlan,
			&i.QueuedAt,
			&i.StartedAt,
			&i.FinishedAt,
			&i.CancelledAt,
			&i.FailedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.OfficialPackMode,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setRunTemporalIDs = `-- name: SetRunTemporalIDs :one
UPDATE runs
SET temporal_workflow_id = $1,
    temporal_run_id = $2
WHERE id = $3
  AND temporal_workflow_id IS NULL
  AND temporal_run_id IS NULL
RETURNING id, organization_id, workspace_id, challenge_pack_version_id, challenge_input_set_id, created_by_user_id, name, status, execution_mode, temporal_workflow_id, temporal_run_id, execution_plan, queued_at, started_at, finished_at, cancelled_at, failed_at, created_at, updated_at, official_pack_mode
`

type SetRunTemporalIDsParams struct {
	TemporalWorkflowID *string
	TemporalRunID      *string
	ID                 uuid.UUID
}

func (q *Queries) SetRunTemporalIDs(ctx context.Context, arg SetRunTemporalIDsParams) (Run, error) {
	row := q.db.QueryRow(ctx, setRunTemporalIDs, arg.TemporalWorkflowID, arg.TemporalRunID, arg.ID)
	var i Run
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.WorkspaceID,
		&i.ChallengePackVersionID,
		&i.ChallengeInputSetID,
		&i.CreatedByUserID,
		&i.Name,
		&i.Status,
		&i.ExecutionMode,
		&i.TemporalWorkflowID,
		&i.TemporalRunID,
		&i.ExecutionPlan,
		&i.QueuedAt,
		&i.StartedAt,
		&i.FinishedAt,
		&i.CancelledAt,
		&i.FailedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.OfficialPackMode,
	)
	return i, err
}

const updateRunStatus = `-- name: UpdateRunStatus :one
UPDATE runs
SET status = $1,
    queued_at = CASE
        WHEN $1::text = 'queued' AND queued_at IS NULL THEN now()
        ELSE queued_at
    END,
    started_at = CASE
        WHEN $1::text = 'provisioning' AND started_at IS NULL THEN now()
        ELSE started_at
    END,
    finished_at = CASE
        WHEN $1::text IN ('completed', 'failed', 'cancelled') AND finished_at IS NULL THEN now()
        ELSE finished_at
    END,
    cancelled_at = CASE
        WHEN $1::text = 'cancelled' AND cancelled_at IS NULL THEN now()
        ELSE cancelled_at
    END,
    failed_at = CASE
        WHEN $1::text = 'failed' AND failed_at IS NULL THEN now()
        ELSE failed_at
    END
WHERE id = $2
  AND status = $3
RETURNING id, organization_id, workspace_id, challenge_pack_version_id, challenge_input_set_id, created_by_user_id, name, status, execution_mode, temporal_workflow_id, temporal_run_id, execution_plan, queued_at, started_at, finished_at, cancelled_at, failed_at, created_at, updated_at, official_pack_mode
`

type UpdateRunStatusParams struct {
	ToStatus   string
	ID         uuid.UUID
	FromStatus string
}

func (q *Queries) UpdateRunStatus(ctx context.Context, arg UpdateRunStatusParams) (Run, error) {
	row := q.db.QueryRow(ctx, updateRunStatus, arg.ToStatus, arg.ID, arg.FromStatus)
	var i Run
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.WorkspaceID,
		&i.ChallengePackVersionID,
		&i.ChallengeInputSetID,
		&i.CreatedByUserID,
		&i.Name,
		&i.Status,
		&i.ExecutionMode,
		&i.TemporalWorkflowID,
		&i.TemporalRunID,
		&i.ExecutionPlan,
		&i.QueuedAt,
		&i.StartedAt,
		&i.FinishedAt,
		&i.CancelledAt,
		&i.FailedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.OfficialPackMode,
	)
	return i, err
}
