// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: worker_execution_context.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const getRunAgentExecutionContextByID = `-- name: GetRunAgentExecutionContextByID :one
SELECT
    ra.id AS run_agent_id,
    ra.organization_id AS run_agent_organization_id,
    ra.workspace_id AS run_agent_workspace_id,
    ra.run_id AS run_agent_run_id,
    ra.agent_deployment_id AS run_agent_agent_deployment_id,
    ra.agent_deployment_snapshot_id AS run_agent_agent_deployment_snapshot_id,
    ra.lane_index AS run_agent_lane_index,
    ra.label AS run_agent_label,
    ra.status AS run_agent_status,
    ra.queued_at AS run_agent_queued_at,
    ra.started_at AS run_agent_started_at,
    ra.finished_at AS run_agent_finished_at,
    ra.failure_reason AS run_agent_failure_reason,
    ra.created_at AS run_agent_created_at,
    ra.updated_at AS run_agent_updated_at,

    r.id AS run_id,
    r.organization_id AS run_organization_id,
    r.workspace_id AS run_workspace_id,
    r.challenge_pack_version_id AS run_challenge_pack_version_id,
    r.challenge_input_set_id AS run_challenge_input_set_id,
    r.official_pack_mode AS run_official_pack_mode,
    r.created_by_user_id AS run_created_by_user_id,
    r.name AS run_name,
    r.status AS run_status,
    r.execution_mode AS run_execution_mode,
    r.temporal_workflow_id AS run_temporal_workflow_id,
    r.temporal_run_id AS run_temporal_run_id,
    r.execution_plan AS run_execution_plan,
    r.queued_at AS run_queued_at,
    r.started_at AS run_started_at,
    r.finished_at AS run_finished_at,
    r.cancelled_at AS run_cancelled_at,
    r.failed_at AS run_failed_at,
    r.created_at AS run_created_at,
    r.updated_at AS run_updated_at,

    cpv.id AS challenge_pack_version_id,
    cpv.challenge_pack_id AS challenge_pack_id,
    cpv.version_number AS challenge_pack_version_number,
    cpv.manifest_checksum AS challenge_pack_manifest_checksum,
    cpv.manifest AS challenge_pack_manifest,
    challenge_definitions.challenge_definitions::jsonb AS challenge_pack_challenges,

    cis.id AS challenge_input_set_id,
    cis.challenge_pack_version_id AS challenge_input_set_challenge_pack_version_id,
    cis.input_key AS challenge_input_set_input_key,
    cis.name AS challenge_input_set_name,
    cis.description AS challenge_input_set_description,
    cis.input_checksum AS challenge_input_set_input_checksum,
    challenge_input_items.challenge_input_items::jsonb AS challenge_input_set_items,

    ads.id AS snapshot_id,
    ads.agent_deployment_id AS snapshot_agent_deployment_id,
    ads.agent_build_id AS snapshot_agent_build_id,
    ads.source_agent_build_version_id AS snapshot_source_agent_build_version_id,
    ads.source_runtime_profile_id AS snapshot_source_runtime_profile_id,
    ads.source_provider_account_id AS snapshot_source_provider_account_id,
    ads.source_model_alias_id AS snapshot_source_model_alias_id,
    ads.deployment_type AS snapshot_deployment_type,
    ads.endpoint_url AS snapshot_endpoint_url,
    ads.snapshot_hash AS snapshot_hash,
    ads.snapshot_config AS snapshot_config,
    ads.source_agent_spec AS snapshot_source_agent_spec,

    rp.id AS runtime_profile_id,
    rp.name AS runtime_profile_name,
    rp.slug AS runtime_profile_slug,
    rp.execution_target AS runtime_profile_execution_target,
    rp.trace_mode AS runtime_profile_trace_mode,
    rp.max_iterations AS runtime_profile_max_iterations,
    rp.max_tool_calls AS runtime_profile_max_tool_calls,
    rp.step_timeout_seconds AS runtime_profile_step_timeout_seconds,
    rp.run_timeout_seconds AS runtime_profile_run_timeout_seconds,
    rp.profile_config AS runtime_profile_profile_config,

    pa.id AS provider_account_id,
    pa.workspace_id AS provider_account_workspace_id,
    pa.provider_key AS provider_account_provider_key,
    pa.name AS provider_account_name,
    pa.credential_reference AS provider_account_credential_reference,
    pa.limits_config AS provider_account_limits_config,

    ma.id AS model_alias_id,
    ma.workspace_id AS model_alias_workspace_id,
    ma.provider_account_id AS model_alias_provider_account_id,
    ma.model_catalog_entry_id AS model_alias_model_catalog_entry_id,
    ma.alias_key AS model_alias_alias_key,
    ma.display_name AS model_alias_display_name,

    mce.id AS model_catalog_entry_id,
    mce.provider_key AS model_catalog_provider_key,
    mce.provider_model_id AS model_catalog_provider_model_id,
    mce.display_name AS model_catalog_display_name,
    mce.model_family AS model_catalog_model_family,
    mce.modality AS model_catalog_modality,
    mce.metadata AS model_catalog_metadata,
    mce.input_cost_per_million_tokens AS model_catalog_input_cost_per_million_tokens,
    mce.output_cost_per_million_tokens AS model_catalog_output_cost_per_million_tokens
FROM run_agents AS ra
JOIN runs AS r
  ON r.id = ra.run_id
 AND r.organization_id = ra.organization_id
 AND r.workspace_id = ra.workspace_id
JOIN challenge_pack_versions AS cpv
  ON cpv.id = r.challenge_pack_version_id
LEFT JOIN LATERAL (
  SELECT count(*) AS selection_count
  FROM run_case_selections
  WHERE run_id = r.id
) AS run_selection_counts
  ON TRUE
LEFT JOIN LATERAL (
  SELECT COALESCE(
    jsonb_agg(
      jsonb_build_object(
        'id', cpvc.id,
        'challenge_identity_id', cpvc.challenge_identity_id,
        'challenge_key', ci.challenge_key,
        'execution_order', cpvc.execution_order,
        'title', cpvc.title_snapshot,
        'category', cpvc.category_snapshot,
        'difficulty', cpvc.difficulty_snapshot,
        'definition', cpvc.challenge_definition
      )
      ORDER BY cpvc.execution_order
    ),
    '[]'::jsonb
  ) AS challenge_definitions
  FROM challenge_pack_version_challenges AS cpvc
  JOIN challenge_identities AS ci
    ON ci.id = cpvc.challenge_identity_id
   AND ci.challenge_pack_id = cpv.challenge_pack_id
  WHERE cpvc.challenge_pack_version_id = cpv.id
    AND (
      run_selection_counts.selection_count = 0 OR
      EXISTS (
        SELECT 1
        FROM run_case_selections AS rcs
        WHERE rcs.run_id = r.id
          AND rcs.challenge_identity_id = cpvc.challenge_identity_id
      )
    )
) AS challenge_definitions
  ON TRUE
LEFT JOIN challenge_input_sets AS cis
  ON cis.id = r.challenge_input_set_id
 AND cis.challenge_pack_version_id = r.challenge_pack_version_id
LEFT JOIN LATERAL (
  SELECT COALESCE(
    jsonb_agg(
      jsonb_build_object(
        'id', cii.id,
        'challenge_identity_id', cii.challenge_identity_id,
        'challenge_key', ci.challenge_key,
        'item_key', cii.item_key,
        'payload', cii.payload,
        'regression_case_id', primary_regression_case.regression_case_id
      )
      ORDER BY cpvc.execution_order, cii.item_key
    ),
    '[]'::jsonb
  ) AS challenge_input_items
  FROM challenge_input_items AS cii
  JOIN challenge_pack_version_challenges AS cpvc
    ON cpvc.challenge_pack_version_id = cii.challenge_pack_version_id
   AND cpvc.challenge_identity_id = cii.challenge_identity_id
  JOIN challenge_identities AS ci
    ON ci.id = cii.challenge_identity_id
   AND ci.challenge_pack_id = cpv.challenge_pack_id
  LEFT JOIN LATERAL (
    SELECT rcs.regression_case_id
    FROM run_case_selections AS rcs
    WHERE rcs.run_id = r.id
      AND rcs.challenge_identity_id = cii.challenge_identity_id
      AND rcs.regression_case_id IS NOT NULL
    ORDER BY rcs.selection_rank ASC, rcs.regression_case_id ASC
    LIMIT 1
  ) AS primary_regression_case
    ON TRUE
  WHERE cii.challenge_input_set_id = cis.id
    AND (
      run_selection_counts.selection_count = 0 OR
      EXISTS (
        SELECT 1
        FROM run_case_selections AS rcs
        WHERE rcs.run_id = r.id
          AND rcs.challenge_identity_id = cii.challenge_identity_id
      )
    )
) AS challenge_input_items
  ON TRUE
JOIN agent_deployment_snapshots AS ads
  ON ads.id = ra.agent_deployment_snapshot_id
 AND ads.agent_deployment_id = ra.agent_deployment_id
 AND ads.organization_id = ra.organization_id
 AND ads.workspace_id = ra.workspace_id
JOIN runtime_profiles AS rp
  ON rp.id = ads.source_runtime_profile_id
 AND rp.organization_id = ads.organization_id
LEFT JOIN provider_accounts AS pa
  ON pa.id = ads.source_provider_account_id
 AND pa.organization_id = ads.organization_id
LEFT JOIN model_aliases AS ma
  ON ma.id = ads.source_model_alias_id
 AND ma.organization_id = ads.organization_id
LEFT JOIN model_catalog_entries AS mce
  ON mce.id = ma.model_catalog_entry_id
WHERE ra.id = $1
LIMIT 1
`

type GetRunAgentExecutionContextByIDParams struct {
	ID uuid.UUID
}

type GetRunAgentExecutionContextByIDRow struct {
	RunAgentID                              uuid.UUID
	RunAgentOrganizationID                  uuid.UUID
	RunAgentWorkspaceID                     uuid.UUID
	RunAgentRunID                           uuid.UUID
	RunAgentAgentDeploymentID               uuid.UUID
	RunAgentAgentDeploymentSnapshotID       uuid.UUID
	RunAgentLaneIndex                       int32
	RunAgentLabel                           string
	RunAgentStatus                          string
	RunAgentQueuedAt                        pgtype.Timestamptz
	RunAgentStartedAt                       pgtype.Timestamptz
	RunAgentFinishedAt                      pgtype.Timestamptz
	RunAgentFailureReason                   *string
	RunAgentCreatedAt                       pgtype.Timestamptz
	RunAgentUpdatedAt                       pgtype.Timestamptz
	RunID                                   uuid.UUID
	RunOrganizationID                       uuid.UUID
	RunWorkspaceID                          uuid.UUID
	RunChallengePackVersionID               uuid.UUID
	RunChallengeInputSetID                  *uuid.UUID
	RunOfficialPackMode                     string
	RunCreatedByUserID                      *uuid.UUID
	RunName                                 string
	RunStatus                               string
	RunExecutionMode                        string
	RunTemporalWorkflowID                   *string
	RunTemporalRunID                        *string
	RunExecutionPlan                        []byte
	RunQueuedAt                             pgtype.Timestamptz
	RunStartedAt                            pgtype.Timestamptz
	RunFinishedAt                           pgtype.Timestamptz
	RunCancelledAt                          pgtype.Timestamptz
	RunFailedAt                             pgtype.Timestamptz
	RunCreatedAt                            pgtype.Timestamptz
	RunUpdatedAt                            pgtype.Timestamptz
	ChallengePackVersionID                  uuid.UUID
	ChallengePackID                         uuid.UUID
	ChallengePackVersionNumber              int32
	ChallengePackManifestChecksum           string
	ChallengePackManifest                   []byte
	ChallengePackChallenges                 []byte
	ChallengeInputSetID                     *uuid.UUID
	ChallengeInputSetChallengePackVersionID *uuid.UUID
	ChallengeInputSetInputKey               *string
	ChallengeInputSetName                   *string
	ChallengeInputSetDescription            *string
	ChallengeInputSetInputChecksum          *string
	ChallengeInputSetItems                  []byte
	SnapshotID                              uuid.UUID
	SnapshotAgentDeploymentID               uuid.UUID
	SnapshotAgentBuildID                    uuid.UUID
	SnapshotSourceAgentBuildVersionID       uuid.UUID
	SnapshotSourceRuntimeProfileID          uuid.UUID
	SnapshotSourceProviderAccountID         *uuid.UUID
	SnapshotSourceModelAliasID              *uuid.UUID
	SnapshotDeploymentType                  string
	SnapshotEndpointUrl                     *string
	SnapshotHash                            string
	SnapshotConfig                          []byte
	SnapshotSourceAgentSpec                 []byte
	RuntimeProfileID                        uuid.UUID
	RuntimeProfileName                      string
	RuntimeProfileSlug                      string
	RuntimeProfileExecutionTarget           string
	RuntimeProfileTraceMode                 string
	RuntimeProfileMaxIterations             int32
	RuntimeProfileMaxToolCalls              int32
	RuntimeProfileStepTimeoutSeconds        int32
	RuntimeProfileRunTimeoutSeconds         int32
	RuntimeProfileProfileConfig             []byte
	ProviderAccountID                       *uuid.UUID
	ProviderAccountWorkspaceID              *uuid.UUID
	ProviderAccountProviderKey              *string
	ProviderAccountName                     *string
	ProviderAccountCredentialReference      *string
	ProviderAccountLimitsConfig             []byte
	ModelAliasID                            *uuid.UUID
	ModelAliasWorkspaceID                   *uuid.UUID
	ModelAliasProviderAccountID             *uuid.UUID
	ModelAliasModelCatalogEntryID           *uuid.UUID
	ModelAliasAliasKey                      *string
	ModelAliasDisplayName                   *string
	ModelCatalogEntryID                     *uuid.UUID
	ModelCatalogProviderKey                 *string
	ModelCatalogProviderModelID             *string
	ModelCatalogDisplayName                 *string
	ModelCatalogModelFamily                 *string
	ModelCatalogModality                    *string
	ModelCatalogMetadata                    []byte
	ModelCatalogInputCostPerMillionTokens   pgtype.Numeric
	ModelCatalogOutputCostPerMillionTokens  pgtype.Numeric
}

func (q *Queries) GetRunAgentExecutionContextByID(ctx context.Context, arg GetRunAgentExecutionContextByIDParams) (GetRunAgentExecutionContextByIDRow, error) {
	row := q.db.QueryRow(ctx, getRunAgentExecutionContextByID, arg.ID)
	var i GetRunAgentExecutionContextByIDRow
	err := row.Scan(
		&i.RunAgentID,
		&i.RunAgentOrganizationID,
		&i.RunAgentWorkspaceID,
		&i.RunAgentRunID,
		&i.RunAgentAgentDeploymentID,
		&i.RunAgentAgentDeploymentSnapshotID,
		&i.RunAgentLaneIndex,
		&i.RunAgentLabel,
		&i.RunAgentStatus,
		&i.RunAgentQueuedAt,
		&i.RunAgentStartedAt,
		&i.RunAgentFinishedAt,
		&i.RunAgentFailureReason,
		&i.RunAgentCreatedAt,
		&i.RunAgentUpdatedAt,
		&i.RunID,
		&i.RunOrganizationID,
		&i.RunWorkspaceID,
		&i.RunChallengePackVersionID,
		&i.RunChallengeInputSetID,
		&i.RunOfficialPackMode,
		&i.RunCreatedByUserID,
		&i.RunName,
		&i.RunStatus,
		&i.RunExecutionMode,
		&i.RunTemporalWorkflowID,
		&i.RunTemporalRunID,
		&i.RunExecutionPlan,
		&i.RunQueuedAt,
		&i.RunStartedAt,
		&i.RunFinishedAt,
		&i.RunCancelledAt,
		&i.RunFailedAt,
		&i.RunCreatedAt,
		&i.RunUpdatedAt,
		&i.ChallengePackVersionID,
		&i.ChallengePackID,
		&i.ChallengePackVersionNumber,
		&i.ChallengePackManifestChecksum,
		&i.ChallengePackManifest,
		&i.ChallengePackChallenges,
		&i.ChallengeInputSetID,
		&i.ChallengeInputSetChallengePackVersionID,
		&i.ChallengeInputSetInputKey,
		&i.ChallengeInputSetName,
		&i.ChallengeInputSetDescription,
		&i.ChallengeInputSetInputChecksum,
		&i.ChallengeInputSetItems,
		&i.SnapshotID,
		&i.SnapshotAgentDeploymentID,
		&i.SnapshotAgentBuildID,
		&i.SnapshotSourceAgentBuildVersionID,
		&i.SnapshotSourceRuntimeProfileID,
		&i.SnapshotSourceProviderAccountID,
		&i.SnapshotSourceModelAliasID,
		&i.SnapshotDeploymentType,
		&i.SnapshotEndpointUrl,
		&i.SnapshotHash,
		&i.SnapshotConfig,
		&i.SnapshotSourceAgentSpec,
		&i.RuntimeProfileID,
		&i.RuntimeProfileName,
		&i.RuntimeProfileSlug,
		&i.RuntimeProfileExecutionTarget,
		&i.RuntimeProfileTraceMode,
		&i.RuntimeProfileMaxIterations,
		&i.RuntimeProfileMaxToolCalls,
		&i.RuntimeProfileStepTimeoutSeconds,
		&i.RuntimeProfileRunTimeoutSeconds,
		&i.RuntimeProfileProfileConfig,
		&i.ProviderAccountID,
		&i.ProviderAccountWorkspaceID,
		&i.ProviderAccountProviderKey,
		&i.ProviderAccountName,
		&i.ProviderAccountCredentialReference,
		&i.ProviderAccountLimitsConfig,
		&i.ModelAliasID,
		&i.ModelAliasWorkspaceID,
		&i.ModelAliasProviderAccountID,
		&i.ModelAliasModelCatalogEntryID,
		&i.ModelAliasAliasKey,
		&i.ModelAliasDisplayName,
		&i.ModelCatalogEntryID,
		&i.ModelCatalogProviderKey,
		&i.ModelCatalogProviderModelID,
		&i.ModelCatalogDisplayName,
		&i.ModelCatalogModelFamily,
		&i.ModelCatalogModality,
		&i.ModelCatalogMetadata,
		&i.ModelCatalogInputCostPerMillionTokens,
		&i.ModelCatalogOutputCostPerMillionTokens,
	)
	return i, err
}
