version: 2
updates:
  - package-ecosystem: gomod
    directory: /backend
    schedule:
      interval: weekly
    groups:
      backend:
        patterns: ["*"]

  - package-ecosystem: gomod
    directory: /cli
    schedule:
      interval: weekly
    groups:
      cli:
        patterns: ["*"]

  - package-ecosystem: npm
    directory: /web
    schedule:
      interval: weekly
    groups:
      web:
        patterns: ["*"]

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    groups:
      actions:
        patterns: ["*"]
