import type { ChangelogPullRequest } from "./changelog";

export const CHANGELOG_PULL_REQUESTS: Record<string, ChangelogPullRequest[]> = {
  "2026-04-15": [
    { number: 413, title: "[codex] fix workspace auth hydration after login" },
    { number: 412, title: "fix(web): redirect workspace shell auth failures" },
    { number: 411, title: "fix(auth): recover device login email from workos userinfo" },
    { number: 410, title: "[codex] make workspace navigation instant" },
    { number: 409, title: "fix(auth): show user identity after cli login" },
    { number: 408, title: "feat: race-context — live peer-standings injection (Phase 2 UI)" },
    { number: 405, title: "feat(cli): default released binaries to https://api.agentclash.dev" },
    { number: 404, title: "(fix): cli release please scope" },
    { number: 403, title: "feat: race-context — live peer-standings injection (Phase 1 backend + API + CLI)" },
    { number: 401, title: "chore(cli): remove winget release channel" },
    { number: 398, title: "Revert \"feat(web): first-run onboarding for workspaces\" (#392)" },
    { number: 396, title: "[codex] Browser capability substrate" },
    { number: 393, title: "feat: full screen YAML editor for eval packs" },
    { number: 392, title: "feat(web): first-run onboarding for workspaces" },
    { number: 391, title: "feat(web): SEO preview tree at /v2 with 22 marketing pages" },
    { number: 389, title: "feat(web): 3D hero icon with WebGL shaders" },
    { number: 387, title: "refactor(docs): update documentation UI to match clean dark theme" },
    { number: 386, title: "[codex] Build public docs foundation" },
    { number: 385, title: "feat(web): add race mode toggle for live run view" },
    { number: 384, title: "[codex] Fix live arena SSE and add commentary booth" },
    { number: 383, title: "feat(web): live arena view for active runs" },
    { number: 377, title: "feat(cli): add interactive run creation picker" },
    { number: 373, title: "[codex] Complete issue #149 eval session UI" },
    { number: 371, title: "[codex] Implement repeated-eval pass@k and comparison semantics" },
    { number: 370, title: "[codex] Add eval session aggregation persistence" },
    { number: 369, title: "Add eval-session workflow fan-out orchestration" },
    { number: 368, title: "feat(eval-sessions): add repeated-eval inspection reads and verification matrix" },
    { number: 366, title: "Add eval session creation endpoint and transactional run plumbing" },
    { number: 364, title: "[codex] Add eval session persistence for repeated eval runs" },
    { number: 357, title: "Add guided build authoring UX for non-expert users" },
    { number: 356, title: "Add phase 1 ranking insights UI and API" },
    { number: 353, title: "feat(cli): harden CLI and add npm distribution channel" },
    { number: 344, title: "feat(web): frontend compare/gate with regressions (#327)" },
    { number: 343, title: "Add regression rule evaluation to release gates" },
    { number: 340, title: "Tighten regression workflow gaps before H and I" },
    { number: 339, title: "feat: support regression suite selection in runs" },
    { number: 338, title: "Regression workflow: add failure promotion modal" },
    { number: 337, title: "feat(web): regression suites frontend (closes #323)" },
    { number: 335, title: "fix(release): use supported GoReleaser publisher tokens" },
    { number: 334, title: "feat: add regression failure promotion endpoint" },
    { number: 333, title: "fix(release): use plain v tags for Release Please" },
    { number: 332, title: "feat(failures): Run → Failures page (closes #320)" },
    { number: 329, title: "Add failure review read model and run failures API" },
    { number: 328, title: "Add regression suite and case CRUD backend" },
    { number: 316, title: "Add xAI provider support via OpenAI-compatible adapter" },
    { number: 313, title: "Make CLI install and release flow accessible" },
    { number: 312, title: "fix(scoring): point final_output source at real producer, fix JSON-schema integer rejection" },
    { number: 311, title: "Add live CLI E2E smoke suite" },
    { number: 310, title: "feat(scorecard): link validators and metrics to originating run event" },
    { number: 309, title: "Fix CLI silently swallowing command errors" },
    { number: 308, title: "[codex] Expose validator evidence on scorecards" },
    { number: 307, title: "Fix CLI browser auth flow" },
    { number: 306, title: "[codex] Add token_f1 scoring validator" },
    { number: 305, title: "feat(scoring): add BLEU / ROUGE / chrF validators" },
    { number: 304, title: "Expose dimension weights and contribution in scorecard response" },
    { number: 303, title: "feat(scoring): add behavioral analysis scorecards" },
    { number: 298, title: "Support n-wise judges and hosted structured trace replay" },
    { number: 293, title: "feat(scoring): LLM judge spec surface + persistence (phases 1-2)" },
    { number: 291, title: "fix(api): auto-select input set on run creation" },
    { number: 290, title: "fix(auth): restore secure CLI login with web verification" },
  ],
  "2026-04-25": [
    { number: 579, title: "fix(billing): stringify Dodo metadata values" },
    { number: 578, title: "[codex] fix billing Dodo error bodies" },
    { number: 576, title: "fix(billing): hardcode Dodo checkout quantity to 1" },
    { number: 574, title: "fix(ci): preserve cwd for action source fallback" },
    { number: 573, title: "fix(ci): harden action CLI resolution" },
    { number: 572, title: "Finish AgentClash CI setup profiles and conflict handling" },
    { number: 571, title: "Create CI setup pull requests from the workspace UI" },
    { number: 570, title: "fix: unblock Claude harness pull requests" },
    { number: 569, title: "Build CI setup UI generator" },
    { number: 567, title: "fix: use reachable app URL in AgentClash PR comments" },
    { number: 566, title: "feat: link AgentClash PR comments to app views" },
    { number: 564, title: "feat: add AgentClash CI PR comments" },
    { number: 563, title: "fix: accept CI default branch metadata" },
    { number: 561, title: "feat(web): surface CI curation metadata" },
    { number: 559, title: "feat(cli): preserve ci curation links" },
    { number: 557, title: "feat(cli): add ci failure taxonomy metadata" },
    { number: 555, title: "fix(releasegate): distinguish invalid scorecards" },
    { number: 553, title: "feat(scoring): surface evaluator validity" },
    { number: 552, title: "fix(cli): render json errors" },
    { number: 551, title: "fix(cli): stream json follow run creation" },
    { number: 550, title: "fix(eval-packs): allow reused evaluation spec names" },
    { number: 549, title: "feat(regressions): surface remediation hints" },
    { number: 548, title: "fix(regressions): batch suite case counts" },
    { number: 547, title: "feat(regressions): add proposed case queue" },
    { number: 546, title: "feat(ci): auto-detect GitHub labels" },
    { number: 545, title: "feat(failures): classify dependency resolution regressions" },
    { number: 544, title: "feat(regression): expose proposed validation runs in web" },
    { number: 543, title: "feat(regression): validate proposed cases explicitly" },
    { number: 542, title: "feat(regression): capture production failures" },
    { number: 541, title: "feat(ci): surface failure taxonomy" },
    { number: 540, title: "docs: expand CI release gate skill" },
    { number: 539, title: "feat(regression): surface maintenance status" },
    { number: 538, title: "docs: add regression flywheel skill" },
    { number: 537, title: "feat(ci): surface failure cluster trends" },
    { number: 536, title: "docs: add scorecard reader skill" },
    { number: 535, title: "docs: add eval runner skill" },
    { number: 534, title: "feat(regression): surface validation signal" },
    { number: 533, title: "docs: add eval pack validation publish skill" },
    { number: 532, title: "docs: expand eval pack llm judges skill" },
    { number: 531, title: "feat(regression): surface failure provenance" },
    { number: 530, title: "docs: expand eval pack scoring validators skill" },
    { number: 529, title: "feat(ci): filter failures by cluster key" },
    { number: 528, title: "docs: expand eval pack artifacts skill" },
    { number: 527, title: "feat(web): surface failure cluster rollups" },
    { number: 526, title: "Skills: eval pack tools and sandbox" },
    { number: 524, title: "Add Claude Agent Harness runner" },
    { number: 522, title: "Skills: eval pack input sets" },
    { number: 518, title: "docs(ci): refresh CI release gate skill" },
    { number: 517, title: "feat(ci): add reusable GitHub Actions gate" },
    { number: 516, title: "feat(ci): propose regression candidates from failing gates" },
    { number: 515, title: "feat(ci): publish gate summaries and artifacts" },
    { number: 514, title: "feat(ci): attach GitHub metadata to CI runs" },
    { number: 513, title: "feat(ci): run manifest gates from the CLI" },
    { number: 512, title: "feat: complete Dodo billing integration" },
    { number: 511, title: "feat(ci): validate manifest resource IDs against API" },
    { number: 510, title: "feat(ci): define baseline resolution flow" },
    { number: 509, title: "docs(ci): add real agent workload recipes" },
    { number: 507, title: "feat(ci): add manifest should-run precheck" },
    { number: 495, title: "fix: materialize artifact-backed pack assets in native sandbox" },
    { number: 494, title: "fix(evalpack): reject mixed-challenge input sets" },
    { number: 493, title: "fix(scoring): support run tool call count collector" },
    { number: 492, title: "fix(api): include eval pack slug in list response" },
    { number: 486, title: "feat(cli): add --repetitions flag to eval start" },
    { number: 485, title: "Skills: eval pack YAML authoring" },
    { number: 484, title: "Docs: expand eval pack planner skill" },
    { number: 483, title: "Internal: run blind AgentClash harnesses for skill changes" },
    { number: 482, title: "feat(cli): add AgentClash CI manifest contract" },
    { number: 481, title: "Skills: agent deployment setup" },
    { number: 480, title: "Skills: agent build author" },
    { number: 479, title: "feat(docs): expand runtime resources skill" },
    { number: 478, title: "feat(docs): expand CLI setup skill" },
    { number: 477, title: "[codex] Let GitHub harnesses open draft PRs" },
    { number: 476, title: "feat: add GitHub App repo picker foundation" },
    { number: 474, title: "Fix Agent Harness diff capture and validator workdirs" },
    { number: 473, title: "feat(e2b): add Codex fullstack template build" },
    { number: 472, title: "fix(agent-harnesses): allow long E2B process streams" },
    { number: 471, title: "fix(agent-harnesses): prevent Codex execution activity timeout" },
    { number: 470, title: "fix: harden Codex Agent Harness execution on E2B" },
    { number: 469, title: "fix: simplify Agent Harness creation" },
    { number: 464, title: "[codex] Complete agent harness executions" },
    { number: 461, title: "feat: add Agent Harnesses for Codex on E2B" },
    { number: 460, title: "Docs: eval pack depth, typography, and non-Mermaid diagrams" },
    { number: 459, title: "feat(docs): add skill catalog contract" },
    { number: 439, title: "[codex] Add frontend billing UX" },
    { number: 438, title: "[codex] Add copyable AgentClash skills catalog" },
    { number: 435, title: "feat(cli): expose regression and artifact surfaces" },
    { number: 434, title: "[codex] Implement billing entitlements and Dodo gates" },
    { number: 431, title: "Replace failures-evals lens with particle flywheel animation" },
    { number: 429, title: "[codex] Fix same-run agent scorecard comparison" },
    { number: 428, title: "[codex] Fix CLI auth identity label source" },
    { number: 422, title: "[codex] Refactor playground comparison workspace" },
    { number: 420, title: "[codex] Restore semantic lucide icons" },
    { number: 419, title: "[codex] Replace web icons with Nourico vectors" },
    { number: 418, title: "feat(web): clash streak login shader with cursor + gyro reactivity" },
    { number: 417, title: "[codex] Brand login as AgentClash while preserving WorkOS AuthKit" },
    { number: 415, title: "fix(web): redirect /workspaces/{id} in middleware to avoid React #310" },
    { number: 414, title: "[codex] Add workflow-first CLI eval commands" },
  ],
  "2026-05-05": [
    { number: 814, title: "Add CLI validation for voice artifact manifests" },
    { number: 812, title: "Add generic voice artifact manifest schema" },
    { number: 810, title: "test: guard embedded voice schema drift" },
    { number: 807, title: "feat: add voice report schema preflight CLI" },
    { number: 805, title: "feat: add voice report JSON schemas" },
    { number: 803, title: "docs: add generic voice artifact contracts" },
    { number: 801, title: "feat: use generic provider log metrics" },
    { number: 800, title: "feat: support generic voice report types" },
    { number: 799, title: "fix: cross-check video sync summary counts" },
    { number: 798, title: "feat: ingest voice video sync reports" },
    { number: 797, title: "feat: ingest voice live continuity reports" },
    { number: 795, title: "feat: ingest voice source separation reports" },
    { number: 790, title: "[codex] score voice media preservation metrics" },
    { number: 788, title: "feat(voice): add voice eval UI affordances" },
    { number: 787, title: "[Voice evals 16] Add support-agent end-to-end smoke test" },
    { number: 786, title: "[Voice evals 15] Add production-call import and redaction contract" },
    { number: 785, title: "[Voice evals 14] Add live-call adapter interface with fake transport" },
    { number: 783, title: "[Voice evals 13] Add CLI/API mode selection for voice evals" },
    { number: 782, title: "feat(voice-evals): add voice compare gate policy" },
    { number: 781, title: "feat(voice-evals): add voice replay projection" },
    { number: 780, title: "feat(voice-evals): add deterministic voice scorecards" },
    { number: 779, title: "feat(voice-evals): add deterministic voice validators and metrics" },
    { number: 778, title: "feat(voice-evals): add text-sim execution mode" },
    { number: 777, title: "feat(voice-evals): add fake voice deployment harness" },
    { number: 776, title: "feat(voice-evals): add scripted user simulator" },
    { number: 775, title: "feat(voice-evals): define artifact manifest" },
    { number: 774, title: "feat(voice-evals): add canonical voice events" },
    { number: 773, title: "test(voice-evals): add golden fixture adapters" },
    { number: 772, title: "feat(voice-evals): add voice pack validation" },
    { number: 771, title: "feat(voice-evals): add multimodal trace contract" },
    { number: 751, title: "feat: add agent build version templates" },
    { number: 750, title: "feat(cli): add run replay and compare commands" },
    { number: 749, title: "feat: add embeddable scorecard shares" },
    { number: 748, title: "test: harden public run share snapshots" },
    { number: 747, title: "feat: add workspace public pack opt-in" },
    { number: 746, title: "feat: surface model alias pricing drift" },
    { number: 745, title: "feat: add postcondition validator" },
    { number: 744, title: "test: tighten doctor pack lineup assertion" },
    { number: 743, title: "fix: address doctor pack review feedback" },
    { number: 742, title: "feat: add pack readiness doctor checks" },
    { number: 741, title: "feat: add provider account smoke test" },
    { number: 740, title: "feat: add model alias create flags" },
    { number: 739, title: "feat: add tool-call assertion validator" },
    { number: 738, title: "feat: export markdown run transcripts" },
    { number: 737, title: "feat: filter streamed run events" },
    { number: 736, title: "feat: add cost-per-correct scorecard metric" },
    { number: 735, title: "fix: preserve Gemini thought signatures" },
    { number: 734, title: "feat: add race series aggregate reports" },
    { number: 733, title: "feat: add race series creation" },
    { number: 731, title: "feat: add eval pack deployment lineups" },
    { number: 730, title: "feat: add seeded run creation" },
    { number: 729, title: "feat: add run max-iteration overrides" },
    { number: 728, title: "feat: export run events as JSONL" },
    { number: 727, title: "feat: surface scorecard total cost" },
    { number: 726, title: "feat: add workspace quota visibility" },
    { number: 724, title: "feat: add run cancellation" },
    { number: 723, title: "fix: log orphan reaper run ids" },
    { number: 722, title: "fix: reap orphaned queued runs" },
    { number: 664, title: "Add rich SEO schema and discovery guardrails" },
    { number: 663, title: "Enrich docs main entity schema" },
    { number: 662, title: "Enrich blog main entity schema" },
    { number: 661, title: "Add blog article schema image" },
    { number: 660, title: "Cover robots crawler policy" },
    { number: 659, title: "Cover sitemap discovery routes" },
    { number: 658, title: "Add docs social image alt metadata" },
    { number: 657, title: "Keep page Open Graph locale explicit" },
    { number: 656, title: "Add secondary page social metadata" },
    { number: 655, title: "Add blog index social metadata" },
    { number: 654, title: "Add platform social metadata" },
    { number: 653, title: "Add blog social image metadata" },
    { number: 652, title: "Add docs social metadata" },
    { number: 651, title: "Add docs structured data" },
    { number: 650, title: "Add blog post breadcrumb structured data" },
    { number: 649, title: "Add blog index structured data" },
    { number: 648, title: "Add RSS autodiscovery metadata" },
    { number: 647, title: "Add blog RSS feed" },
    { number: 646, title: "Include blog posts in llms discovery files" },
    { number: 645, title: "Add AI agent evaluation blog post" },
    { number: 644, title: "Add platform page structured data" },
    { number: 643, title: "Add platform pages to docs search index" },
    { number: 642, title: "List platform pages in llms discovery files" },
    { number: 641, title: "Add AI agent regression testing page" },
    { number: 640, title: "Add AI agent evaluation platform page" },
    { number: 639, title: "Improve npm discovery metadata" },
    { number: 638, title: "Clarify homepage AI agent evaluation copy" },
    { number: 637, title: "Noindex markdown docs exports" },
    { number: 636, title: "Add public page SEO metadata" },
    { number: 635, title: "Improve homepage SEO metadata signals" },
    { number: 634, title: "Remove hidden v2 marketing routes" },
    { number: 630, title: "CLI: expose full Agent Harness workflow" },
    { number: 629, title: "feat(cli): add workflow phase 1 commands" },
    { number: 628, title: "Agent Harnesses: classify failures and curate prior runs" },
    { number: 627, title: "Agent Harnesses: add suite rankings and pass@k" },
    { number: 626, title: "feat: add harness execution controls" },
    { number: 625, title: "feat: add agent harness task suites" },
    { number: 624, title: "feat: add harness privacy controls" },
    { number: 623, title: "fix: log invite accept denial reasons" },
    { number: 622, title: "feat: persist harness scorecards" },
    { number: 621, title: "feat: add agent harness bootstrap setup stage" },
    { number: 620, title: "fix: accept invite tokens when auth email is unavailable" },
    { number: 617, title: "fix: repair invite acceptance flow" },
    { number: 616, title: "feat(agent-harnesses): chat-first harness workbench" },
    { number: 607, title: "fix(cli): compact prompt eval results tables" },
    { number: 605, title: "fix(cli): polish prompt eval results table" },
    { number: 603, title: "docs: design prompt-eval failure promotion" },
    { number: 602, title: "feat(cli): add safe Promptfoo import subset" },
    { number: 601, title: "feat(action): add prompt-eval CI mode" },
    { number: 600, title: "feat(cli): add prompt-eval follow and results" },
    { number: 599, title: "feat(cli): compile and launch prompt-eval runs" },
    { number: 598, title: "feat(cli): add prompt-eval remote preflight" },
    { number: 596, title: "feat(cli): add prompt-eval config validation" },
    { number: 580, title: "fix: add copyable member invite links" },
  ],
  "2026-05-15": [
    { number: 856, title: "feat: add opencode PR review bot with intelligent model selection" },
    { number: 855, title: "fix(multi-turn): preserve submit tool history and human-input UI" },
    { number: 853, title: "feat(runevents): multi-turn run events + transcript model (#842)" },
    { number: 852, title: "feat(evalpack): user_simulator manifest schema + validation (#841)" },
    { number: 851, title: "feat(evalpack): per-case {{placeholder}} templating for test_command (#840)" },
    { number: 838, title: "feat(replay): IDE-level syntax highlighting and rich text rendering in trace output" },
    { number: 832, title: "feat(security): runtime-stress harness — real Vault SDK + function calling (#815)" },
    { number: 831, title: "docs(security): comprehensive security-eval findings + methodology (#815)" },
    { number: 830, title: "fix(packs): anchor forbidden_output patterns to compliance-context (#815)" },
    { number: 829, title: "fix(stress): Anthropic empty-content refusal → synthetic refusal marker (#815)" },
    { number: 827, title: "feat(packs): hashicorp-vault-boundary.yaml — Vault-framed canary pack (#815)" },
    { number: 826, title: "feat(packs): infisical-boundary.yaml — does naming the vault hold the line? (#815)" },
    { number: 825, title: "feat(stress): Anthropic Messages API provider + frontier-model leak data (#815)" },
    { number: 824, title: "feat(stress): --no-system-guard surfaces real leaks (gpt-4o-mini 100% leak at 15 iter) (#815)" },
    { number: 823, title: "test(stress): prove scorer fires per-incident-kind under stub-LLM leak injection (#815)" },
    { number: 822, title: "fix(packs): broaden refusal-patterns after real stress-run calibration (#815)" },
    { number: 820, title: "feat(cli): security stress-run subcommand (PR 5/10 — #815)" },
    { number: 819, title: "feat(examples): prompt-injection-classic canonical pack (PR 4/10 — #815)" },
    { number: 818, title: "feat(examples): canonical secret-hygiene-env security pack (PR 3/10 — #815)" },
    { number: 817, title: "feat(securityscore): pure scorer for SecurityPolicy (PR 2/10 — #815)" },
    { number: 816, title: "feat(evalpack): SecurityPolicy schema for security-family packs (PR 1/10 — #815)" },
  ],
  "2026-05-25": [
    { number: 911, title: "feat(web): dataset UI epic — full API/CLI parity in workspace UI" },
    { number: 910, title: "fix: return 400 for generation provider mismatch" },
    { number: 909, title: "fix: dataset QA follow-ups (nil tags, counts, provider match)" },
    { number: 908, title: "fix: allow non-manual dataset example sources in production" },
    { number: 906, title: "feat: Self-Instruct synthetic dataset generation (#892)" },
    { number: 904, title: "feat: dataset CI follow-up — regression sync, JUnit, web tab" },
    { number: 903, title: "fix(web): sync package-lock.json with @vercel/speed-insights" },
    { number: 902, title: "feat(web): expand SEO + AEO discoverability (compare pages, AI-crawler rules, structured data)" },
    { number: 901, title: "feat(datasets): baselines and CI gate verdict (#891)" },
    { number: 899, title: "feat(datasets): production trace ingest and candidate promotion (#890)" },
    { number: 898, title: "feat(datasets): run evals from pinned dataset versions" },
    { number: 897, title: "feat(analytics): PostHog usage tracking (backend, CLI, web)" },
    { number: 895, title: "feat(datasets): add dataset import/export interop" },
    { number: 893, title: "feat: add datasets foundation" },
    { number: 884, title: "fix(web): keep docs header \"Get Started\" button from overflowing" },
    { number: 883, title: "feat(try-cli): Kimi + Qwen demos via their own CLIs; opencode on Zen" },
    { number: 882, title: "feat(try-cli): free-trial gateway + signed-in BYO tier for AI demos" },
    { number: 881, title: "feat(try-cli): AI coding agent demos, prebaked E2B template, redesigned UI" },
    { number: 880, title: "feat(try-cli): Interactive terminal demos (AgentClash primitive)" },
    { number: 878, title: "feat: add Vibe Eval draft persistence" },
    { number: 877, title: "docs: add Vibe Eval Phase 0 inventory" },
    { number: 867, title: "feat(web): multi-turn transcript + PDF export on scorecard" },
    { number: 866, title: "feat(web): export multi-turn transcript to PDF" },
    { number: 865, title: "feat(web): multi-turn conversation transcript on replay page" },
    { number: 864, title: "feat(api): multi-turn conversation transcript endpoint" },
    { number: 863, title: "fix(multi-turn): surface turn events + let llm phases pin a model" },
    { number: 862, title: "fix(engine): give multi_turn LLM simulator the secret-injected ctx" },
    { number: 859, title: "feat: OpenAI Responses API execution mode" },
    { number: 525, title: "Add Hermes Agent Harness runner" },
    { number: 523, title: "Add OpenClaw Agent Harness runner" },
  ],
  "2026-06-02": [
    { number: 931, title: "feat(cli): add agentclash skills export for offline install (#922)" },
    { number: 930, title: "chore(cli): regenerate skills snapshot for P3 (#922)" },
    { number: 929, title: "feat(skills): P3 security evaluation and workspace admin skills (#922)" },
    { number: 928, title: "feat(cli): integration install for all six agent hosts" },
    { number: 926, title: "feat(cli): sync embedded skills snapshot to 23 P1 skills" },
    { number: 925, title: "feat(skills): add P1 portable agent skills (harness, multi-turn, dataset, prompt-eval)" },
    { number: 924, title: "feat(cli): sync embedded skills snapshot for P0 skills" },
    { number: 923, title: "feat(agent-skills): P0 workflow skills (hub, quickstart, compare-and-triage)" },
    { number: 920, title: "docs(skills): gh-skill publish bundle generator + install docs" },
    { number: 919, title: "feat(cli): `agentclash integration <claude|codex> {install,doctor}`" },
    { number: 918, title: "feat(cli): make `completion` validate its shell argument" },
    { number: 917, title: "feat(cli): add `agentclash schema` machine-readable command tree" },
    { number: 916, title: "feat(web): IndexNow ping + Search Console/Bing verification" },
    { number: 915, title: "feat(web): add image entries to the sitemap" },
  ],
};
