"use client";

// Wraps the Framer-exported "Expanded Cards" component
// (web/src/framer/expanded-card.jsx, generated by `npx unframer`) and feeds
// it our use-case copy. The component accepts both the clean prop names
// (cardNTitle / cardNParagraph) and Framer's opaque IDs; we use the clean
// names because they're typed via JSDoc.

import ExpandedCardFramerComponent from "@/framer/expanded-card";
import { ClashMark } from "./clash-mark";

export type ExpandedCard = {
  title: string;
  paragraph: string;
};

export function ExpandedCardsBlock({ cards }: { cards: ExpandedCard[] }) {
  // The Framer component is hard-wired to 5 cards. Pad with empty strings
  // if the caller gives fewer; never index past 5.
  const c = (i: number) => cards[i] ?? { title: "", paragraph: "" };

  return (
    <div className="mx-auto w-full max-w-[1280px]">
      {/* Accordion sits left, brand line fills the right gutter. The Framer
          accordion has a fixed ~800px max-width, so the rest of the row is
          empty whitespace by default — this gives it something to say. */}
      <div className="flex flex-col items-center gap-12 sm:flex-row sm:items-center sm:justify-between sm:gap-10">
        <ExpandedCardFramerComponent.Responsive
          card1Title={c(0).title}
          card1Paragraph={c(0).paragraph}
          card2Title={c(1).title}
          card2Paragraph={c(1).paragraph}
          card3Title={c(2).title}
          card3Paragraph={c(2).paragraph}
          card4Title={c(3).title}
          card4Paragraph={c(3).paragraph}
          card5Title={c(4).title}
          card5Paragraph={c(4).paragraph}
        />

        <div className="flex max-w-[22ch] flex-col items-start gap-5 sm:max-w-[24ch]">
          <ClashMark className="size-10 opacity-90" />
          <p className="font-[family-name:var(--font-display)] text-[clamp(1.5rem,2.4vw,2rem)] leading-[1.1] tracking-[-0.02em] text-white">
            …and many more.
          </p>
          <p className="text-sm leading-[1.55] text-white/55">
            Whatever agent you ship — debug it on AgentClash.
          </p>
        </div>
      </div>
    </div>
  );
}
