"use client";

// Wraps the Framer-exported "Expanded Cards" component
// (web/src/framer/expanded-card.jsx, generated by `npx unframer`) and feeds
// it our use-case copy. The component accepts both the clean prop names
// (cardNTitle / cardNParagraph) and Framer's opaque IDs; we use the clean
// names because they're typed via JSDoc.

import ExpandedCardFramerComponent from "@/framer/expanded-card";

export type ExpandedCard = {
  title: string;
  paragraph: string;
};

export function ExpandedCardsBlock({ cards }: { cards: ExpandedCard[] }) {
  // The Framer component is hard-wired to 5 cards. Pad with empty strings
  // if the caller gives fewer; never index past 5.
  const c = (i: number) => cards[i] ?? { title: "", paragraph: "" };

  return (
    <div className="mx-auto w-full max-w-[1280px]">
      <ExpandedCardFramerComponent.Responsive
        card1Title={c(0).title}
        card1Paragraph={c(0).paragraph}
        card2Title={c(1).title}
        card2Paragraph={c(1).paragraph}
        card3Title={c(2).title}
        card3Paragraph={c(2).paragraph}
        card4Title={c(3).title}
        card4Paragraph={c(3).paragraph}
        card5Title={c(4).title}
        card5Paragraph={c(4).paragraph}
      />
    </div>
  );
}
