listen_addresses = 'localhost'
port = 5432
max_connections = 100

shared_buffers = 128MB
work_mem = 4MB

log_destination = 'stderr'
logging_collector = on
log_statement = 'all'

hba_file = '/etc/postgresql/pg_hba.conf'
