// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project 56c0de29b7dae5ae "Expanded Cards (copy)", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * variant?: 'Desktop 1' | 'Desktop 2' | 'Desktop 3' | 'Desktop 4' | 'Desktop 5' | 'Mobile 1' | 'Mobile 2' | 'Mobile 3' | 'Mobile 4' | 'Mobile 5' // Variant
 * card1BG?: {src: string, srcSet?: string, alt?: string} // Card 1 BG
 * card1Title?: string // Card 1 Title
 * card1Paragraph?: string // Card 1 Paragraph
 * card1Icon?: any // Card 1 Icon
 * card2BG?: {src: string, srcSet?: string, alt?: string} // Card 2 BG
 * card2Title?: string // Card 2 Title
 * card2Paragraph?: string // Card 2 Paragraph
 * card2Icon?: any // Card 2 Icon
 * card3BG?: {src: string, srcSet?: string, alt?: string} // Card 3 BG
 * card3Title?: string // Card 3 Title
 * card3Paragraph?: string // Card 3 Paragraph
 * card3Icon?: any // Card 3 Icon
 * card4BG?: {src: string, srcSet?: string, alt?: string} // Card 4 BG
 * card4Title?: string // Card 4 Title
 * card4Paragraph?: string // Card 4 Paragraph
 * card4Icon?: any // Card 4 Icon
 * card5BG?: {src: string, srcSet?: string, alt?: string} // Card 5 BG
 * card5Title?: string // Card 5 Title
 * card5Paragraph?: string // Card 5 Paragraph
 * card5Icon?: any // Card 5 Icon
}} Props

 */
import { routes, stdin_default } from "./chunks/chunk-WDXJCQ5O.js";

// Patch: swap each card's photographic BG for an animated FluidShader and
// each card's stock shield for a per-task-family lucide icon, both keyed
// off the card number (SalXds4M0). Re-running `npx unframer` will
// overwrite this file — re-apply: (1) these imports + maps, (2) the
// FluidShader render in place of <Image> inside Background, (3) the
// CARD_ICONS render in place of <Instance Component={Myka4MPLk}>.
import { FluidShader } from "@/components/marketing/fluid-shader";
import { CARD_ICONS } from "@/components/marketing/card-icons";
const FLUID_THEMES_BY_CARD = {
	"01": "darkSlate", // Coding
	"02": "darkAmber", // Research
	"03": "darkCrimson", // SRE
	"04": "darkViolet", // Multi-step ops
	"05": "darkEmerald", // Codebase Q&A
};

// virtual:expanded-card
import { Fragment as Fragment3 } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/69WHwjdMVOLUQnMjHhoO/v3JefY8lFtAbwhelmCDc/M_0XXlsvG.js
import { jsx as _jsx2, jsxs as _jsxs2 } from "react/jsx-runtime";
import {
	addFonts as addFonts2,
	addPropertyControls as addPropertyControls2,
	ComponentViewportProvider,
	ControlType as ControlType2,
	cx as cx2,
	getFonts,
	SmartComponentScopedContainer,
	useActiveVariantCallback as useActiveVariantCallback2,
	useComponentViewport as useComponentViewport2,
	useLocaleInfo as useLocaleInfo2,
	useVariantState as useVariantState2,
	withCSS as withCSS2,
} from "unframer";
import {
	LayoutGroup as LayoutGroup2,
	motion as motion2,
	MotionConfigContext as MotionConfigContext2,
} from "unframer";
import * as React2 from "react";
import { useRef as useRef2 } from "react";

// /:https://framerusercontent.com/modules/xZ5pFcOxyue0Ujit8pQL/Wh8Geo5Qmap5lmYeJuTL/eBAVAzu3r.js
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import {
	addFonts,
	addPropertyControls,
	ControlType,
	cx,
	getLoadingLazyAtYPosition,
	Image,
	Instance,
	RichText,
	useActiveVariantCallback,
	useComponentViewport,
	useLocaleInfo,
	useVariantState,
	withCSS,
} from "unframer";
import { LayoutGroup, motion, MotionConfigContext } from "unframer";
import * as React from "react";
import { useRef } from "react";
var cycleOrder = ["ly5K6dYAL", "N8Q2LPD4z", "l4kNLZSMb", "M4jMDboVd"];
var serializationHash = "framer-o1VIl";
var variantClassNames = {
	l4kNLZSMb: "framer-v-180q2td",
	ly5K6dYAL: "framer-v-f36akv",
	M4jMDboVd: "framer-v-bfjs1o",
	N8Q2LPD4z: "framer-v-5mcdky",
};
function addPropertyOverrides(overrides, ...variants) {
	const nextOverrides = {};
	variants?.forEach(
		(variant) => variant && Object.assign(nextOverrides, overrides[variant]),
	);
	return nextOverrides;
}
var transition1 = {
	damping: 30,
	delay: 0,
	mass: 1,
	stiffness: 160,
	type: "spring",
};
var toResponsiveImage = (value) => {
	if (
		typeof value === "object" &&
		value !== null &&
		typeof value.src === "string"
	) {
		return value;
	}
	return typeof value === "string"
		? {
				src: value,
			}
		: void 0;
};
var Transition = ({ value, children }) => {
	const config = React.useContext(MotionConfigContext);
	const transition = value ?? config.transition;
	const contextValue = React.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider value={contextValue}>
			{children}
		</MotionConfigContext.Provider>
	);
};
var Variants = motion.create(React.Fragment);
var humanReadableVariantMap = {
	"Desktop Default": "N8Q2LPD4z",
	"Desktop Opened": "ly5K6dYAL",
	"Mobile Default": "M4jMDboVd",
	"Mobile opened": "l4kNLZSMb",
};
var getProps = ({
	bG,
	click,
	height,
	hover,
	icon,
	id,
	number,
	paragraph,
	title,
	width,
	...props
}) => {
	return {
		...props,
		iEWo2giux:
			paragraph ??
			props.iEWo2giux ??
			"Today\u2019s demo is another snippet for an expanding flex cards in accordion style.",
		Myka4MPLk: icon ?? props.Myka4MPLk ?? stdin_default,
		qRiSJSdCR: bG ??
			props.qRiSJSdCR ?? {
				alt: "",
				pixelHeight: 2400,
				pixelWidth: 1808,
				src: "https://framerusercontent.com/images/jsoYuvRP6FOxNSujX1KSiZEvOpc.png?scale-down-to=512",
				srcSet:
					"https://framerusercontent.com/images/jsoYuvRP6FOxNSujX1KSiZEvOpc.png?scale-down-to=1024 771w,https://framerusercontent.com/images/jsoYuvRP6FOxNSujX1KSiZEvOpc.png?scale-down-to=2048 1542w,https://framerusercontent.com/images/jsoYuvRP6FOxNSujX1KSiZEvOpc.png 1808w",
			},
		S8ey59QcC: click ?? props.S8ey59QcC,
		SalXds4M0: number ?? props.SalXds4M0 ?? "01",
		variant:
			humanReadableVariantMap[props.variant] ?? props.variant ?? "ly5K6dYAL",
		VndmGA4XE: title ?? props.VndmGA4XE ?? "Expanding Cards",
		zyLBavdS6: hover ?? props.zyLBavdS6,
	};
};
var createLayoutDependency = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const fallbackRef = useRef(null);
	const refBinding = ref ?? fallbackRef;
	const defaultLayoutId = React.useId();
	const { activeLocale, setLocale } = useLocaleInfo();
	const componentViewport = useComponentViewport();
	const {
		style,
		className,
		layoutId,
		variant,
		zyLBavdS6,
		qRiSJSdCR,
		S8ey59QcC,
		SalXds4M0,
		iEWo2giux,
		VndmGA4XE,
		Myka4MPLk,
		...restProps
	} = getProps(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState({
		cycleOrder,
		defaultVariant: "ly5K6dYAL",
		ref: refBinding,
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const { activeVariantCallback, delay } =
		useActiveVariantCallback(baseVariant);
	const onTapy7dnty = activeVariantCallback(async (...args) => {
		setGestureState({
			isPressed: false,
		});
		if (S8ey59QcC) {
			const res = await S8ey59QcC(...args);
			if (res === false) return false;
		}
	});
	const onMouseEnter1k75mhf = activeVariantCallback(async (...args) => {
		setGestureState({
			isHovered: true,
		});
		if (zyLBavdS6) {
			const res = await zyLBavdS6(...args);
			if (res === false) return false;
		}
	});
	const sharedStyleClassNames = [];
	const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
	const isDisplayed = () => {
		if (baseVariant === "M4jMDboVd") return false;
		return true;
	};
	const isDisplayed1 = () => {
		if (baseVariant === "N8Q2LPD4z") return false;
		return true;
	};
	return (
		<LayoutGroup id={layoutId ?? defaultLayoutId}>
			<Variants animate={variants} initial={false}>
				<Transition value={transition1}>
					<motion.div
						{...restProps}
						{...gestureHandlers}
						className={cx(
							scopingClassNames,
							"framer-f36akv",
							className,
							classNames,
						)}
						data-framer-name={"Desktop Opened"}
						data-highlight={true}
						layoutDependency={layoutDependency}
						layoutId={"ly5K6dYAL"}
						onMouseEnter={onMouseEnter1k75mhf}
						onTap={onTapy7dnty}
						ref={refBinding}
						style={{
							...style,
						}}
						{...addPropertyOverrides(
							{
								l4kNLZSMb: {
									"data-framer-name": "Mobile opened",
								},
								M4jMDboVd: {
									"data-framer-name": "Mobile Default",
								},
								N8Q2LPD4z: {
									"data-framer-name": "Desktop Default",
								},
							},
							baseVariant,
							gestureVariant,
						)}
					>
						<motion.div
							className={"framer-18lcyur"}
							data-framer-name={"Background"}
							layoutDependency={layoutDependency}
							layoutId={"AEFLPhv2D"}
							style={{
								borderBottomLeftRadius: 10,
								borderBottomRightRadius: 10,
								borderTopLeftRadius: 10,
								borderTopRightRadius: 10,
							}}
						>
							{/* Patched: was <Image background={qRiSJSdCR}/>, now an animated
							    FluidShader picked by card number. See FLUID_THEMES_BY_CARD
							    above. */}
							<motion.div
								className={"framer-oia2f5"}
								data-framer-name={"Image"}
								layoutDependency={layoutDependency}
								layoutId={"vDHqqnEOa"}
								style={{
									borderBottomLeftRadius: 10,
									borderBottomRightRadius: 10,
									borderTopLeftRadius: 10,
									borderTopRightRadius: 10,
									overflow: "hidden",
								}}
							>
								<FluidShader
									theme={FLUID_THEMES_BY_CARD[SalXds4M0] ?? "blue"}
								/>
							</motion.div>
							<motion.div
								className={"framer-1qokm0z"}
								data-framer-name={"Overlay"}
								layoutDependency={layoutDependency}
								layoutId={"d0Mcbg_0p"}
								style={{
									backgroundColor: "rgb(0, 0, 0)",
									opacity: 0.5,
								}}
								variants={{
									M4jMDboVd: {
										opacity: 0.8,
									},
									N8Q2LPD4z: {
										opacity: 0.8,
									},
								}}
							/>
						</motion.div>
						<motion.div
							className={"framer-1y118y9"}
							data-framer-name={"Content wrapper"}
							layoutDependency={layoutDependency}
							layoutId={"CVb63EpcY"}
						>
							<motion.div
								className={"framer-xgb03n"}
								data-framer-name={"Number"}
								layoutDependency={layoutDependency}
								layoutId={"ezXJ1cccX"}
							>
								<RichText
									__fromCanvasComponent={true}
									className={"framer-n40b6v"}
									fonts={["Inter-SemiBold"]}
									layoutDependency={layoutDependency}
									layoutId={"mbk_eFcNd"}
									style={{
										"--extracted-r6o4lv": "rgb(255, 255, 255)",
										"--framer-link-text-color": "rgb(0, 153, 255)",
										"--framer-link-text-decoration": "underline",
									}}
									text={SalXds4M0}
									verticalAlignment={"top"}
									withExternalLayout={true}
								>
									<React.Fragment>
										<motion.p
											style={{
												"--font-selector": "SW50ZXItU2VtaUJvbGQ=",
												"--framer-font-family":
													'"Inter", "Inter Placeholder", sans-serif',
												"--framer-font-size": "14px",
												"--framer-font-weight": "600",
												"--framer-text-alignment": "left",
												"--framer-text-color":
													"var(--extracted-r6o4lv, rgb(255, 255, 255))",
											}}
										>
											{"01"}
										</motion.p>
									</React.Fragment>
								</RichText>
							</motion.div>
							{isDisplayed() && (
								<motion.div
									className={"framer-1gpkcqn"}
									data-framer-name={"Buttom"}
									layoutDependency={layoutDependency}
									layoutId={"I11I3kHyo"}
								>
									<motion.div
										className={"framer-19mq03d"}
										data-framer-name={"Content"}
										layoutDependency={layoutDependency}
										layoutId={"xulmpbjPA"}
										style={{
											opacity: 1,
										}}
										variants={{
											l4kNLZSMb: {
												opacity: 1,
											},
											N8Q2LPD4z: {
												opacity: 0,
											},
										}}
									>
										<RichText
											__fromCanvasComponent={true}
											className={"framer-qhips9"}
											fonts={["Inter"]}
											layoutDependency={layoutDependency}
											layoutId={"q6g3P6g40"}
											style={{
												"--extracted-r6o4lv": "rgb(255, 255, 255)",
												"--framer-link-text-color": "rgb(0, 153, 255)",
												"--framer-link-text-decoration": "underline",
											}}
											text={iEWo2giux}
											verticalAlignment={"top"}
											withExternalLayout={true}
										>
											<React.Fragment>
												<motion.p
													style={{
														"--framer-font-size": "14px",
														"--framer-line-height": "1.6em",
														"--framer-text-alignment": "left",
														"--framer-text-color":
															"var(--extracted-r6o4lv, rgb(255, 255, 255))",
													}}
												>
													{
														"Today\u2019s demo is another snippet for an expanding flex cards in accordion style."
													}
												</motion.p>
											</React.Fragment>
										</RichText>
									</motion.div>
									<motion.div
										className={"framer-1mbyo0s"}
										data-framer-name={"Title"}
										layoutDependency={layoutDependency}
										layoutId={"TGs0JIuam"}
									>
										{/* Patched: was Framer's stock shield via
										    <Instance Component={Myka4MPLk}/>. Now a per-card
										    lucide glyph indexed by SalXds4M0. */}
										{(() => {
											const Icon = CARD_ICONS[SalXds4M0] ?? CARD_ICONS["01"];
											return (
												<Icon
													className={"framer-14t09ok"}
													strokeWidth={1.6}
													style={{ width: 20, height: 20, color: "rgb(255, 255, 255)" }}
												/>
											);
										})()}
										{isDisplayed1() && (
											<RichText
												__fromCanvasComponent={true}
												className={"framer-gsykpm"}
												fonts={["Inter-SemiBold"]}
												layoutDependency={layoutDependency}
												layoutId={"bWtIzJKvy"}
												style={{
													"--extracted-r6o4lv": "rgb(255, 255, 255)",
													"--framer-link-text-color": "rgb(0, 153, 255)",
													"--framer-link-text-decoration": "underline",
												}}
												text={VndmGA4XE}
												verticalAlignment={"top"}
												withExternalLayout={true}
											>
												<React.Fragment>
													<motion.p
														style={{
															"--font-selector": "SW50ZXItU2VtaUJvbGQ=",
															"--framer-font-family":
																'"Inter", "Inter Placeholder", sans-serif',
															"--framer-font-size": "14px",
															"--framer-font-weight": "600",
															"--framer-text-color":
																"var(--extracted-r6o4lv, rgb(255, 255, 255))",
														}}
													>
														{"Expanding Cards"}
													</motion.p>
												</React.Fragment>
											</RichText>
										)}
									</motion.div>
								</motion.div>
							)}
						</motion.div>
					</motion.div>
				</Transition>
			</Variants>
		</LayoutGroup>
	);
});
var css = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-o1VIl.framer-ea4tx3, .framer-o1VIl .framer-ea4tx3 { display: block; }",
	".framer-o1VIl.framer-f36akv { align-content: flex-end; align-items: flex-end; cursor: pointer; display: flex; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: 400px; justify-content: center; overflow: hidden; padding: 12px; position: relative; width: 368px; }",
	".framer-o1VIl .framer-18lcyur { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: 100%; justify-content: center; left: 0px; overflow: hidden; padding: 0px; position: absolute; top: calc(50.00000000000002% - 100% / 2); width: 100%; will-change: var(--framer-will-change-override, transform); }",
	".framer-o1VIl .framer-oia2f5 { flex: none; height: 100%; position: relative; width: 400px; z-index: 1; }",
	".framer-o1VIl .framer-1qokm0z { flex: none; height: 100%; left: calc(50.00000000000002% - 100% / 2); overflow: hidden; position: absolute; top: calc(50.00000000000002% - 100% / 2); width: 100%; z-index: 1; }",
	".framer-o1VIl .framer-1y118y9 { align-content: center; align-items: center; display: flex; flex: 1 0 0px; flex-direction: column; flex-wrap: nowrap; height: 100%; justify-content: space-between; overflow: hidden; padding: 0px; position: relative; width: 1px; z-index: 2; }",
	".framer-o1VIl .framer-xgb03n { align-content: flex-start; align-items: flex-start; display: flex; flex: 1 0 0px; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: 1px; justify-content: flex-start; overflow: visible; padding: 0px; position: relative; width: 100%; }",
	".framer-o1VIl .framer-n40b6v { flex: none; height: auto; position: relative; white-space: pre; width: auto; }",
	".framer-o1VIl .framer-1gpkcqn { align-content: flex-start; align-items: flex-start; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: center; overflow: visible; padding: 0px; position: relative; width: 100%; }",
	".framer-o1VIl .framer-19mq03d, .framer-o1VIl .framer-1mbyo0s { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: flex-start; overflow: visible; padding: 0px; position: relative; width: 100%; }",
	".framer-o1VIl .framer-qhips9, .framer-o1VIl .framer-gsykpm { flex: 1 0 0px; height: auto; position: relative; white-space: pre-wrap; width: 1px; word-break: break-word; word-wrap: break-word; }",
	".framer-o1VIl .framer-14t09ok { flex: none; height: var(--framer-aspect-ratio-supported, 20px); position: relative; width: 20px; }",
	".framer-o1VIl.framer-v-5mcdky.framer-f36akv { width: 60px; }",
	".framer-o1VIl.framer-v-5mcdky .framer-xgb03n, .framer-o1VIl.framer-v-5mcdky .framer-1mbyo0s { justify-content: center; }",
	".framer-o1VIl.framer-v-5mcdky .framer-19mq03d { min-width: 320px; }",
	".framer-o1VIl.framer-v-180q2td.framer-f36akv { width: 358px; }",
	".framer-o1VIl.framer-v-180q2td .framer-oia2f5, .framer-o1VIl.framer-v-bfjs1o .framer-oia2f5 { flex: 1 0 0px; height: 420px; width: 1px; }",
	".framer-o1VIl.framer-v-bfjs1o.framer-f36akv { height: 42px; width: 358px; }",
	".framer-o1VIl.framer-v-bfjs1o .framer-xgb03n { align-content: center; align-items: center; }",
];
var FramereBAVAzu3r = withCSS(Component, css, "framer-o1VIl");
var stdin_default2 = FramereBAVAzu3r;
FramereBAVAzu3r.displayName = "Image";
FramereBAVAzu3r.defaultProps = {
	height: 400,
	width: 368,
};
addPropertyControls(FramereBAVAzu3r, {
	variant: {
		options: ["ly5K6dYAL", "N8Q2LPD4z", "l4kNLZSMb", "M4jMDboVd"],
		optionTitles: [
			"Desktop Opened",
			"Desktop Default",
			"Mobile opened",
			"Mobile Default",
		],
		title: "Variant",
		type: ControlType.Enum,
	},
	zyLBavdS6: {
		title: "Hover",
		type: ControlType.EventHandler,
	},
	qRiSJSdCR: {
		__defaultAssetReference:
			"data:framer/asset-reference,jsoYuvRP6FOxNSujX1KSiZEvOpc.png?originalFilename=Surreal+Glass+Forms.png&preferredSize=auto",
		__vekterDefault: {
			alt: "",
			assetReference:
				"data:framer/asset-reference,jsoYuvRP6FOxNSujX1KSiZEvOpc.png?originalFilename=Surreal+Glass+Forms.png&preferredSize=auto",
		},
		title: "BG",
		type: ControlType.ResponsiveImage,
	},
	S8ey59QcC: {
		title: "Click",
		type: ControlType.EventHandler,
	},
	SalXds4M0: {
		defaultValue: "01",
		displayTextArea: false,
		title: "Number",
		type: ControlType.String,
	},
	iEWo2giux: {
		defaultValue:
			"Today\u2019s demo is another snippet for an expanding flex cards in accordion style.",
		displayTextArea: false,
		title: "Paragraph",
		type: ControlType.String,
	},
	VndmGA4XE: {
		defaultValue: "Expanding Cards",
		displayTextArea: false,
		title: "Title",
		type: ControlType.String,
	},
	Myka4MPLk: {
		defaultValue: {
			identifier:
				"module:S27Rn2XV0IhQFkUG0aQO/FBYhOPmZ4cgfEXv6wOEU/mNoisM7ar.js:default",
			moduleId: "S27Rn2XV0IhQFkUG0aQO",
		},
		setModuleId: "omX0gWFPqDwhaiWwf6ab",
		title: "Icon",
		type: ControlType.VectorSetItem,
	},
});
addFonts(
	FramereBAVAzu3r,
	[
		{
			explicitInter: true,
			fonts: [
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
					url: "https://framerusercontent.com/assets/hyOgCu0Xnghbimh0pE8QTvtt2AU.woff2",
					weight: "600",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
					url: "https://framerusercontent.com/assets/NeGmSOXrPBfEFIy5YZeHq17LEDA.woff2",
					weight: "600",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+1F00-1FFF",
					url: "https://framerusercontent.com/assets/oYaAX5himiTPYuN8vLWnqBbfD2s.woff2",
					weight: "600",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+0370-03FF",
					url: "https://framerusercontent.com/assets/lEJLP4R0yuCaMCjSXYHtJw72M.woff2",
					weight: "600",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
					url: "https://framerusercontent.com/assets/cRJyLNuTJR5jbyKzGi33wU9cqIQ.woff2",
					weight: "600",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2074, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
					url: "https://framerusercontent.com/assets/1ZFS7N918ojhhd0nQWdj3jz4w.woff2",
					weight: "600",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
					url: "https://framerusercontent.com/assets/A0Wcc7NgXMjUuFdquHDrIZpzZw0.woff2",
					weight: "600",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
					url: "https://framerusercontent.com/assets/5vvr9Vy74if2I6bQbJvbw7SY1pQ.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
					url: "https://framerusercontent.com/assets/EOr0mi4hNtlgWNn9if640EZzXCo.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+1F00-1FFF",
					url: "https://framerusercontent.com/assets/Y9k9QrlZAqio88Klkmbd8VoMQc.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+0370-03FF",
					url: "https://framerusercontent.com/assets/OYrD2tBIBPvoJXiIHnLoOXnY9M.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
					url: "https://framerusercontent.com/assets/JeYwfuaPfZHQhEG8U5gtPDZ7WQ.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2074, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
					url: "https://framerusercontent.com/assets/vQyevYAyHtARFwPqUzQGpnDs.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
					url: "https://framerusercontent.com/assets/b6Y37FthZeALduNqHicBT6FutY.woff2",
					weight: "400",
				},
			],
		},
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// /:https://framerusercontent.com/modules/69WHwjdMVOLUQnMjHhoO/v3JefY8lFtAbwhelmCDc/M_0XXlsvG.js
var ImageFonts = getFonts(stdin_default2);
var cycleOrder2 = [
	"eY8CEsifj",
	"xy9RgHFiZ",
	"uXb_dVsYg",
	"xV0WwalK2",
	"N0kgPlv3I",
	"bjur6M13y",
	"i2fEWTYw3",
	"Y5V5Jzvsb",
	"KQ_Til4kh",
	"RZsAD5UoD",
];
var serializationHash2 = "framer-COFEE";
var variantClassNames2 = {
	bjur6M13y: "framer-v-jz7iat",
	eY8CEsifj: "framer-v-16o466l",
	i2fEWTYw3: "framer-v-1lbfjyi",
	KQ_Til4kh: "framer-v-qgsjjz",
	N0kgPlv3I: "framer-v-11jcr3s",
	RZsAD5UoD: "framer-v-zfd7ek",
	uXb_dVsYg: "framer-v-152n8qt",
	xV0WwalK2: "framer-v-5mjckg",
	xy9RgHFiZ: "framer-v-1vseqq6",
	Y5V5Jzvsb: "framer-v-10zasxx",
};
function addPropertyOverrides2(overrides, ...variants) {
	const nextOverrides = {};
	variants?.forEach(
		(variant) => variant && Object.assign(nextOverrides, overrides[variant]),
	);
	return nextOverrides;
}
var transition12 = {
	damping: 30,
	delay: 0,
	mass: 1,
	stiffness: 160,
	type: "spring",
};
var toResponsiveImage2 = (value) => {
	if (
		typeof value === "object" &&
		value !== null &&
		typeof value.src === "string"
	) {
		return value;
	}
	return typeof value === "string"
		? {
				src: value,
			}
		: void 0;
};
var Transition2 = ({ value, children }) => {
	const config = React2.useContext(MotionConfigContext2);
	const transition = value ?? config.transition;
	const contextValue = React2.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext2.Provider value={contextValue}>
			{children}
		</MotionConfigContext2.Provider>
	);
};
var Variants2 = motion2.create(React2.Fragment);
var humanReadableVariantMap2 = {
	"Desktop 1": "eY8CEsifj",
	"Desktop 2": "xy9RgHFiZ",
	"Desktop 3": "uXb_dVsYg",
	"Desktop 4": "xV0WwalK2",
	"Desktop 5": "N0kgPlv3I",
	"Mobile 1": "bjur6M13y",
	"Mobile 2": "i2fEWTYw3",
	"Mobile 3": "Y5V5Jzvsb",
	"Mobile 4": "KQ_Til4kh",
	"Mobile 5": "RZsAD5UoD",
};
var getProps2 = ({
	card1BG,
	card1Icon,
	card1Paragraph,
	card1Title,
	card2BG,
	card2Icon,
	card2Paragraph,
	card2Title,
	card3BG,
	card3Icon,
	card3Paragraph,
	card3Title,
	card4BG,
	card4Icon,
	card4Paragraph,
	card4Title,
	card5BG,
	card5Icon,
	card5Paragraph,
	card5Title,
	height,
	id,
	width,
	...props
}) => {
	return {
		...props,
		cJCVT2e9U: card3Title ?? props.cJCVT2e9U ?? "Expanding Cards",
		ClpQ4Io2a:
			card3Paragraph ??
			props.ClpQ4Io2a ??
			"Today\u2019s demo is another snippet for an expanding flex cards in accordion style.",
		dus5Mp6Wz: card1BG ??
			props.dus5Mp6Wz ?? {
				pixelHeight: 2400,
				pixelWidth: 1808,
				src: "https://framerusercontent.com/images/jsoYuvRP6FOxNSujX1KSiZEvOpc.png?scale-down-to=1024",
				srcSet:
					"https://framerusercontent.com/images/jsoYuvRP6FOxNSujX1KSiZEvOpc.png?scale-down-to=1024 771w,https://framerusercontent.com/images/jsoYuvRP6FOxNSujX1KSiZEvOpc.png?scale-down-to=2048 1542w,https://framerusercontent.com/images/jsoYuvRP6FOxNSujX1KSiZEvOpc.png 1808w",
			},
		eJc6PTKkJ: card2BG ??
			props.eJc6PTKkJ ?? {
				pixelHeight: 2400,
				pixelWidth: 1808,
				src: "https://framerusercontent.com/images/jsoYuvRP6FOxNSujX1KSiZEvOpc.png?scale-down-to=1024",
				srcSet:
					"https://framerusercontent.com/images/jsoYuvRP6FOxNSujX1KSiZEvOpc.png?scale-down-to=1024 771w,https://framerusercontent.com/images/jsoYuvRP6FOxNSujX1KSiZEvOpc.png?scale-down-to=2048 1542w,https://framerusercontent.com/images/jsoYuvRP6FOxNSujX1KSiZEvOpc.png 1808w",
			},
		FuT_FhTRX: card2Icon ?? props.FuT_FhTRX ?? stdin_default,
		GLCQwQpPX:
			card5Paragraph ??
			props.GLCQwQpPX ??
			"Today\u2019s demo is another snippet for an expanding flex cards in accordion style.",
		hKdFhNkIt: card4BG ??
			props.hKdFhNkIt ?? {
				pixelHeight: 2400,
				pixelWidth: 1808,
				src: "https://framerusercontent.com/images/jsoYuvRP6FOxNSujX1KSiZEvOpc.png?scale-down-to=1024",
				srcSet:
					"https://framerusercontent.com/images/jsoYuvRP6FOxNSujX1KSiZEvOpc.png?scale-down-to=1024 771w,https://framerusercontent.com/images/jsoYuvRP6FOxNSujX1KSiZEvOpc.png?scale-down-to=2048 1542w,https://framerusercontent.com/images/jsoYuvRP6FOxNSujX1KSiZEvOpc.png 1808w",
			},
		hl3u2jSex: card1Title ?? props.hl3u2jSex ?? "Expanding Cards",
		Ibibb8Jt4: card2Title ?? props.Ibibb8Jt4 ?? "Expanding Cards",
		JmijCUJ3x: card5Title ?? props.JmijCUJ3x ?? "Expanding Cards",
		kcydKql0g: card4Icon ?? props.kcydKql0g ?? stdin_default,
		ktxDHoxyu:
			card4Paragraph ??
			props.ktxDHoxyu ??
			"Today\u2019s demo is another snippet for an expanding flex cards in accordion style.",
		mZf1Qz4KK:
			card1Paragraph ??
			props.mZf1Qz4KK ??
			"Today\u2019s demo is another snippet for an expanding flex cards in accordion style.",
		nk2LdNAij: card4Title ?? props.nk2LdNAij ?? "Expanding Cards",
		QB08i4WHX:
			card2Paragraph ??
			props.QB08i4WHX ??
			"Today\u2019s demo is another snippet for an expanding flex cards in accordion style.",
		uwt0Mza21: card5Icon ?? props.uwt0Mza21 ?? stdin_default,
		variant:
			humanReadableVariantMap2[props.variant] ?? props.variant ?? "eY8CEsifj",
		VTQOG_1lE: card3BG ??
			props.VTQOG_1lE ?? {
				pixelHeight: 2400,
				pixelWidth: 1808,
				src: "https://framerusercontent.com/images/jsoYuvRP6FOxNSujX1KSiZEvOpc.png?scale-down-to=1024",
				srcSet:
					"https://framerusercontent.com/images/jsoYuvRP6FOxNSujX1KSiZEvOpc.png?scale-down-to=1024 771w,https://framerusercontent.com/images/jsoYuvRP6FOxNSujX1KSiZEvOpc.png?scale-down-to=2048 1542w,https://framerusercontent.com/images/jsoYuvRP6FOxNSujX1KSiZEvOpc.png 1808w",
			},
		Xc48bWctO: card3Icon ?? props.Xc48bWctO ?? stdin_default,
		ymLV5IcYd: card1Icon ?? props.ymLV5IcYd ?? stdin_default,
		ZkFD0MQ_a: card5BG ??
			props.ZkFD0MQ_a ?? {
				pixelHeight: 2400,
				pixelWidth: 1808,
				src: "https://framerusercontent.com/images/jsoYuvRP6FOxNSujX1KSiZEvOpc.png?scale-down-to=1024",
				srcSet:
					"https://framerusercontent.com/images/jsoYuvRP6FOxNSujX1KSiZEvOpc.png?scale-down-to=1024 771w,https://framerusercontent.com/images/jsoYuvRP6FOxNSujX1KSiZEvOpc.png?scale-down-to=2048 1542w,https://framerusercontent.com/images/jsoYuvRP6FOxNSujX1KSiZEvOpc.png 1808w",
			},
	};
};
var createLayoutDependency2 = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component2 = /* @__PURE__ */ React2.forwardRef(function (props, ref) {
	const fallbackRef = useRef2(null);
	const refBinding = ref ?? fallbackRef;
	const defaultLayoutId = React2.useId();
	const { activeLocale, setLocale } = useLocaleInfo2();
	const componentViewport = useComponentViewport2();
	const {
		style,
		className,
		layoutId,
		variant,
		dus5Mp6Wz,
		hl3u2jSex,
		mZf1Qz4KK,
		ymLV5IcYd,
		eJc6PTKkJ,
		Ibibb8Jt4,
		QB08i4WHX,
		FuT_FhTRX,
		VTQOG_1lE,
		cJCVT2e9U,
		ClpQ4Io2a,
		Xc48bWctO,
		hKdFhNkIt,
		nk2LdNAij,
		ktxDHoxyu,
		kcydKql0g,
		ZkFD0MQ_a,
		JmijCUJ3x,
		GLCQwQpPX,
		uwt0Mza21,
		...restProps
	} = getProps2(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState2({
		cycleOrder: cycleOrder2,
		defaultVariant: "eY8CEsifj",
		ref: refBinding,
		variant,
		variantClassNames: variantClassNames2,
	});
	const layoutDependency = createLayoutDependency2(props, variants);
	const { activeVariantCallback, delay } =
		useActiveVariantCallback2(baseVariant);
	const zyLBavdS61dnelv1 = activeVariantCallback(async (...args) => {
		setVariant("eY8CEsifj");
	});
	const S8ey59QcC1qk1a4s = activeVariantCallback(async (...args) => {
		setVariant("bjur6M13y");
	});
	const zyLBavdS6gifuvx = activeVariantCallback(async (...args) => {
		setVariant("xy9RgHFiZ");
	});
	const S8ey59QcC1ypvpge = activeVariantCallback(async (...args) => {
		setVariant("i2fEWTYw3");
	});
	const zyLBavdS61cdvf1y = activeVariantCallback(async (...args) => {
		setVariant("uXb_dVsYg");
	});
	const S8ey59QcC1mzt59j = activeVariantCallback(async (...args) => {
		setVariant("Y5V5Jzvsb");
	});
	const zyLBavdS67buc7y = activeVariantCallback(async (...args) => {
		setVariant("xV0WwalK2");
	});
	const S8ey59QcC1207mur = activeVariantCallback(async (...args) => {
		setVariant("KQ_Til4kh");
	});
	const zyLBavdS61tzhvyk = activeVariantCallback(async (...args) => {
		setVariant("N0kgPlv3I");
	});
	const S8ey59QcC18mwy6t = activeVariantCallback(async (...args) => {
		setVariant("RZsAD5UoD");
	});
	const sharedStyleClassNames = [];
	const scopingClassNames = cx2(serializationHash2, ...sharedStyleClassNames);
	return (
		<LayoutGroup2 id={layoutId ?? defaultLayoutId}>
			<Variants2 animate={variants} initial={false}>
				<Transition2 value={transition12}>
					<motion2.div
						{...restProps}
						{...gestureHandlers}
						className={cx2(
							scopingClassNames,
							"framer-16o466l",
							className,
							classNames,
						)}
						data-framer-name={"Desktop 1"}
						layoutDependency={layoutDependency}
						layoutId={"eY8CEsifj"}
						ref={refBinding}
						style={{
							...style,
						}}
						{...addPropertyOverrides2(
							{
								bjur6M13y: {
									"data-framer-name": "Mobile 1",
								},
								i2fEWTYw3: {
									"data-framer-name": "Mobile 2",
								},
								KQ_Til4kh: {
									"data-framer-name": "Mobile 4",
								},
								N0kgPlv3I: {
									"data-framer-name": "Desktop 5",
								},
								RZsAD5UoD: {
									"data-framer-name": "Mobile 5",
								},
								uXb_dVsYg: {
									"data-framer-name": "Desktop 3",
								},
								xV0WwalK2: {
									"data-framer-name": "Desktop 4",
								},
								xy9RgHFiZ: {
									"data-framer-name": "Desktop 2",
								},
								Y5V5Jzvsb: {
									"data-framer-name": "Mobile 3",
								},
							},
							baseVariant,
							gestureVariant,
						)}
					>
						<ComponentViewportProvider
							height={((componentViewport?.height || 400) - 0) * 1}
							width={`max(${componentViewport?.width || "100vw"} * 0.6 - 40px, 1px)`}
							y={
								(componentViewport?.y || 0) +
								(0 +
									((componentViewport?.height || 400) -
										0 -
										((componentViewport?.height || 400) - 0) * 1) /
										2)
							}
							{...addPropertyOverrides2(
								{
									bjur6M13y: {
										height: 400,
										width: componentViewport?.width || "100vw",
										y:
											(componentViewport?.y || 0) +
											0 +
											(((componentViewport?.height || 608) - 0 - 2040) / 2 +
												0 +
												0),
									},
									i2fEWTYw3: {
										height: 400,
										width: componentViewport?.width || "100vw",
										y:
											(componentViewport?.y || 0) +
											0 +
											(((componentViewport?.height || 608) - 0 - 2040) / 2 +
												0 +
												0),
									},
									KQ_Til4kh: {
										height: 400,
										width: componentViewport?.width || "100vw",
										y:
											(componentViewport?.y || 0) +
											0 +
											(((componentViewport?.height || 608) - 0 - 2040) / 2 +
												0 +
												0),
									},
									N0kgPlv3I: {
										width: `calc(${componentViewport?.width || "100vw"} / 10)`,
									},
									RZsAD5UoD: {
										height: 400,
										width: componentViewport?.width || "100vw",
										y:
											(componentViewport?.y || 0) +
											0 +
											(((componentViewport?.height || 608) - 0 - 2040) / 2 +
												0 +
												0),
									},
									uXb_dVsYg: {
										width: `calc(${componentViewport?.width || "100vw"} / 10)`,
									},
									xV0WwalK2: {
										width: `calc(${componentViewport?.width || "100vw"} / 10)`,
									},
									xy9RgHFiZ: {
										width: `calc(${componentViewport?.width || "100vw"} / 10)`,
									},
									Y5V5Jzvsb: {
										height: 400,
										width: componentViewport?.width || "100vw",
										y:
											(componentViewport?.y || 0) +
											0 +
											(((componentViewport?.height || 608) - 0 - 2040) / 2 +
												0 +
												0),
									},
								},
								baseVariant,
								gestureVariant,
							)}
						>
							<SmartComponentScopedContainer
								className={"framer-1surpun-container"}
								layoutDependency={layoutDependency}
								layoutId={"CuMUPOX2Y-container"}
								nodeId={"CuMUPOX2Y"}
								rendersWithMotion={true}
								scopeId={"M_0XXlsvG"}
							>
								{_jsx2(stdin_default2, {
									height: "100%",
									id: "CuMUPOX2Y",
									iEWo2giux: mZf1Qz4KK,
									layoutId: "CuMUPOX2Y",
									Myka4MPLk: ymLV5IcYd,
									qRiSJSdCR: toResponsiveImage2(dus5Mp6Wz),
									SalXds4M0: "01",
									style: {
										height: "100%",
										width: "100%",
									},
									variant: "ly5K6dYAL",
									VndmGA4XE: hl3u2jSex,
									width: "100%",
									zyLBavdS6: zyLBavdS61dnelv1,
									...addPropertyOverrides2(
										{
											bjur6M13y: {
												S8ey59QcC: S8ey59QcC1qk1a4s,
												style: {
													width: "100%",
												},
												variant: "l4kNLZSMb",
												zyLBavdS6: void 0,
											},
											i2fEWTYw3: {
												S8ey59QcC: S8ey59QcC1qk1a4s,
												style: {
													width: "100%",
												},
												variant: "M4jMDboVd",
												zyLBavdS6: void 0,
											},
											KQ_Til4kh: {
												S8ey59QcC: S8ey59QcC1qk1a4s,
												style: {
													width: "100%",
												},
												variant: "M4jMDboVd",
												zyLBavdS6: void 0,
											},
											N0kgPlv3I: {
												variant: "N8Q2LPD4z",
											},
											RZsAD5UoD: {
												S8ey59QcC: S8ey59QcC1qk1a4s,
												style: {
													width: "100%",
												},
												variant: "M4jMDboVd",
												zyLBavdS6: void 0,
											},
											uXb_dVsYg: {
												variant: "N8Q2LPD4z",
											},
											xV0WwalK2: {
												variant: "N8Q2LPD4z",
											},
											xy9RgHFiZ: {
												variant: "N8Q2LPD4z",
											},
											Y5V5Jzvsb: {
												S8ey59QcC: S8ey59QcC1qk1a4s,
												style: {
													width: "100%",
												},
												variant: "M4jMDboVd",
												zyLBavdS6: void 0,
											},
										},
										baseVariant,
										gestureVariant,
									),
								})}
							</SmartComponentScopedContainer>
						</ComponentViewportProvider>
						<ComponentViewportProvider
							height={((componentViewport?.height || 400) - 0) * 1}
							width={`calc(${componentViewport?.width || "100vw"} / 10)`}
							y={
								(componentViewport?.y || 0) +
								(0 +
									((componentViewport?.height || 400) -
										0 -
										((componentViewport?.height || 400) - 0) * 1) /
										2)
							}
							{...addPropertyOverrides2(
								{
									bjur6M13y: {
										height: 400,
										width: componentViewport?.width || "100vw",
										y:
											(componentViewport?.y || 0) +
											0 +
											(((componentViewport?.height || 608) - 0 - 2040) / 2 +
												400 +
												10),
									},
									i2fEWTYw3: {
										height: 400,
										width: componentViewport?.width || "100vw",
										y:
											(componentViewport?.y || 0) +
											0 +
											(((componentViewport?.height || 608) - 0 - 2040) / 2 +
												400 +
												10),
									},
									KQ_Til4kh: {
										height: 400,
										width: componentViewport?.width || "100vw",
										y:
											(componentViewport?.y || 0) +
											0 +
											(((componentViewport?.height || 608) - 0 - 2040) / 2 +
												400 +
												10),
									},
									RZsAD5UoD: {
										height: 400,
										width: componentViewport?.width || "100vw",
										y:
											(componentViewport?.y || 0) +
											0 +
											(((componentViewport?.height || 608) - 0 - 2040) / 2 +
												400 +
												10),
									},
									xy9RgHFiZ: {
										width: `max(${componentViewport?.width || "100vw"} * 0.6 - 40px, 1px)`,
									},
									Y5V5Jzvsb: {
										height: 400,
										width: componentViewport?.width || "100vw",
										y:
											(componentViewport?.y || 0) +
											0 +
											(((componentViewport?.height || 608) - 0 - 2040) / 2 +
												400 +
												10),
									},
								},
								baseVariant,
								gestureVariant,
							)}
						>
							<SmartComponentScopedContainer
								className={"framer-1iqp84l-container"}
								layoutDependency={layoutDependency}
								layoutId={"OCydvELN9-container"}
								nodeId={"OCydvELN9"}
								rendersWithMotion={true}
								scopeId={"M_0XXlsvG"}
							>
								{_jsx2(stdin_default2, {
									height: "100%",
									id: "OCydvELN9",
									iEWo2giux: QB08i4WHX,
									layoutId: "OCydvELN9",
									Myka4MPLk: FuT_FhTRX,
									qRiSJSdCR: toResponsiveImage2(eJc6PTKkJ),
									SalXds4M0: "02",
									style: {
										height: "100%",
										width: "100%",
									},
									variant: "N8Q2LPD4z",
									VndmGA4XE: Ibibb8Jt4,
									width: "100%",
									zyLBavdS6: zyLBavdS6gifuvx,
									...addPropertyOverrides2(
										{
											bjur6M13y: {
												S8ey59QcC: S8ey59QcC1ypvpge,
												style: {
													width: "100%",
												},
												variant: "M4jMDboVd",
												zyLBavdS6: void 0,
											},
											i2fEWTYw3: {
												S8ey59QcC: S8ey59QcC1ypvpge,
												style: {
													width: "100%",
												},
												variant: "l4kNLZSMb",
												zyLBavdS6: void 0,
											},
											KQ_Til4kh: {
												S8ey59QcC: S8ey59QcC1ypvpge,
												style: {
													width: "100%",
												},
												variant: "M4jMDboVd",
												zyLBavdS6: void 0,
											},
											RZsAD5UoD: {
												S8ey59QcC: S8ey59QcC1ypvpge,
												style: {
													width: "100%",
												},
												variant: "M4jMDboVd",
												zyLBavdS6: void 0,
											},
											xy9RgHFiZ: {
												variant: "ly5K6dYAL",
											},
											Y5V5Jzvsb: {
												S8ey59QcC: S8ey59QcC1ypvpge,
												style: {
													width: "100%",
												},
												variant: "M4jMDboVd",
												zyLBavdS6: void 0,
											},
										},
										baseVariant,
										gestureVariant,
									),
								})}
							</SmartComponentScopedContainer>
						</ComponentViewportProvider>
						<ComponentViewportProvider
							height={((componentViewport?.height || 400) - 0) * 1}
							width={`calc(${componentViewport?.width || "100vw"} / 10)`}
							y={
								(componentViewport?.y || 0) +
								(0 +
									((componentViewport?.height || 400) -
										0 -
										((componentViewport?.height || 400) - 0) * 1) /
										2)
							}
							{...addPropertyOverrides2(
								{
									bjur6M13y: {
										height: 400,
										width: componentViewport?.width || "100vw",
										y:
											(componentViewport?.y || 0) +
											0 +
											(((componentViewport?.height || 608) - 0 - 2040) / 2 +
												800 +
												20),
									},
									i2fEWTYw3: {
										height: 400,
										width: componentViewport?.width || "100vw",
										y:
											(componentViewport?.y || 0) +
											0 +
											(((componentViewport?.height || 608) - 0 - 2040) / 2 +
												800 +
												20),
									},
									KQ_Til4kh: {
										height: 400,
										width: componentViewport?.width || "100vw",
										y:
											(componentViewport?.y || 0) +
											0 +
											(((componentViewport?.height || 608) - 0 - 2040) / 2 +
												800 +
												20),
									},
									RZsAD5UoD: {
										height: 400,
										width: componentViewport?.width || "100vw",
										y:
											(componentViewport?.y || 0) +
											0 +
											(((componentViewport?.height || 608) - 0 - 2040) / 2 +
												800 +
												20),
									},
									uXb_dVsYg: {
										width: `max(${componentViewport?.width || "100vw"} * 0.6 - 40px, 1px)`,
									},
									Y5V5Jzvsb: {
										height: 400,
										width: componentViewport?.width || "100vw",
										y:
											(componentViewport?.y || 0) +
											0 +
											(((componentViewport?.height || 608) - 0 - 2040) / 2 +
												800 +
												20),
									},
								},
								baseVariant,
								gestureVariant,
							)}
						>
							<SmartComponentScopedContainer
								className={"framer-1xogf5p-container"}
								layoutDependency={layoutDependency}
								layoutId={"i6Nx_cYjH-container"}
								nodeId={"i6Nx_cYjH"}
								rendersWithMotion={true}
								scopeId={"M_0XXlsvG"}
							>
								{_jsx2(stdin_default2, {
									height: "100%",
									id: "i6Nx_cYjH",
									iEWo2giux: ClpQ4Io2a,
									layoutId: "i6Nx_cYjH",
									Myka4MPLk: Xc48bWctO,
									qRiSJSdCR: toResponsiveImage2(VTQOG_1lE),
									SalXds4M0: "03",
									style: {
										height: "100%",
										width: "100%",
									},
									variant: "N8Q2LPD4z",
									VndmGA4XE: cJCVT2e9U,
									width: "100%",
									zyLBavdS6: zyLBavdS61cdvf1y,
									...addPropertyOverrides2(
										{
											bjur6M13y: {
												S8ey59QcC: S8ey59QcC1mzt59j,
												style: {
													width: "100%",
												},
												variant: "M4jMDboVd",
												zyLBavdS6: void 0,
											},
											i2fEWTYw3: {
												S8ey59QcC: S8ey59QcC1mzt59j,
												style: {
													width: "100%",
												},
												variant: "M4jMDboVd",
												zyLBavdS6: void 0,
											},
											KQ_Til4kh: {
												S8ey59QcC: S8ey59QcC1mzt59j,
												style: {
													width: "100%",
												},
												variant: "M4jMDboVd",
												zyLBavdS6: void 0,
											},
											RZsAD5UoD: {
												S8ey59QcC: S8ey59QcC1mzt59j,
												style: {
													width: "100%",
												},
												variant: "M4jMDboVd",
												zyLBavdS6: void 0,
											},
											uXb_dVsYg: {
												variant: "ly5K6dYAL",
											},
											Y5V5Jzvsb: {
												S8ey59QcC: S8ey59QcC1mzt59j,
												style: {
													width: "100%",
												},
												variant: "l4kNLZSMb",
												zyLBavdS6: void 0,
											},
										},
										baseVariant,
										gestureVariant,
									),
								})}
							</SmartComponentScopedContainer>
						</ComponentViewportProvider>
						<ComponentViewportProvider
							height={((componentViewport?.height || 400) - 0) * 1}
							width={`calc(${componentViewport?.width || "100vw"} / 10)`}
							y={
								(componentViewport?.y || 0) +
								(0 +
									((componentViewport?.height || 400) -
										0 -
										((componentViewport?.height || 400) - 0) * 1) /
										2)
							}
							{...addPropertyOverrides2(
								{
									bjur6M13y: {
										height: 400,
										width: componentViewport?.width || "100vw",
										y:
											(componentViewport?.y || 0) +
											0 +
											(((componentViewport?.height || 608) - 0 - 2040) / 2 +
												1200 +
												30),
									},
									i2fEWTYw3: {
										height: 400,
										width: componentViewport?.width || "100vw",
										y:
											(componentViewport?.y || 0) +
											0 +
											(((componentViewport?.height || 608) - 0 - 2040) / 2 +
												1200 +
												30),
									},
									KQ_Til4kh: {
										height: 400,
										width: componentViewport?.width || "100vw",
										y:
											(componentViewport?.y || 0) +
											0 +
											(((componentViewport?.height || 608) - 0 - 2040) / 2 +
												1200 +
												30),
									},
									RZsAD5UoD: {
										height: 400,
										width: componentViewport?.width || "100vw",
										y:
											(componentViewport?.y || 0) +
											0 +
											(((componentViewport?.height || 608) - 0 - 2040) / 2 +
												1200 +
												30),
									},
									xV0WwalK2: {
										width: `max(${componentViewport?.width || "100vw"} * 0.6 - 40px, 1px)`,
									},
									Y5V5Jzvsb: {
										height: 400,
										width: componentViewport?.width || "100vw",
										y:
											(componentViewport?.y || 0) +
											0 +
											(((componentViewport?.height || 608) - 0 - 2040) / 2 +
												1200 +
												30),
									},
								},
								baseVariant,
								gestureVariant,
							)}
						>
							<SmartComponentScopedContainer
								className={"framer-iez57u-container"}
								layoutDependency={layoutDependency}
								layoutId={"zjbSvPE3e-container"}
								nodeId={"zjbSvPE3e"}
								rendersWithMotion={true}
								scopeId={"M_0XXlsvG"}
							>
								{_jsx2(stdin_default2, {
									height: "100%",
									id: "zjbSvPE3e",
									iEWo2giux: ktxDHoxyu,
									layoutId: "zjbSvPE3e",
									Myka4MPLk: kcydKql0g,
									qRiSJSdCR: toResponsiveImage2(hKdFhNkIt),
									SalXds4M0: "04",
									style: {
										height: "100%",
										width: "100%",
									},
									variant: "N8Q2LPD4z",
									VndmGA4XE: nk2LdNAij,
									width: "100%",
									zyLBavdS6: zyLBavdS67buc7y,
									...addPropertyOverrides2(
										{
											bjur6M13y: {
												S8ey59QcC: S8ey59QcC1207mur,
												style: {
													width: "100%",
												},
												variant: "M4jMDboVd",
												zyLBavdS6: void 0,
											},
											i2fEWTYw3: {
												S8ey59QcC: S8ey59QcC1207mur,
												style: {
													width: "100%",
												},
												variant: "M4jMDboVd",
												zyLBavdS6: void 0,
											},
											KQ_Til4kh: {
												S8ey59QcC: S8ey59QcC1207mur,
												style: {
													width: "100%",
												},
												variant: "l4kNLZSMb",
												zyLBavdS6: void 0,
											},
											RZsAD5UoD: {
												S8ey59QcC: S8ey59QcC1207mur,
												style: {
													width: "100%",
												},
												variant: "M4jMDboVd",
												zyLBavdS6: void 0,
											},
											xV0WwalK2: {
												variant: "ly5K6dYAL",
											},
											Y5V5Jzvsb: {
												S8ey59QcC: S8ey59QcC1207mur,
												style: {
													width: "100%",
												},
												variant: "M4jMDboVd",
												zyLBavdS6: void 0,
											},
										},
										baseVariant,
										gestureVariant,
									),
								})}
							</SmartComponentScopedContainer>
						</ComponentViewportProvider>
						<ComponentViewportProvider
							height={((componentViewport?.height || 400) - 0) * 1}
							width={`calc(${componentViewport?.width || "100vw"} / 10)`}
							y={
								(componentViewport?.y || 0) +
								(0 +
									((componentViewport?.height || 400) -
										0 -
										((componentViewport?.height || 400) - 0) * 1) /
										2)
							}
							{...addPropertyOverrides2(
								{
									bjur6M13y: {
										height: 400,
										width: componentViewport?.width || "100vw",
										y:
											(componentViewport?.y || 0) +
											0 +
											(((componentViewport?.height || 608) - 0 - 2040) / 2 +
												1600 +
												40),
									},
									i2fEWTYw3: {
										height: 400,
										width: componentViewport?.width || "100vw",
										y:
											(componentViewport?.y || 0) +
											0 +
											(((componentViewport?.height || 608) - 0 - 2040) / 2 +
												1600 +
												40),
									},
									KQ_Til4kh: {
										height: 400,
										width: componentViewport?.width || "100vw",
										y:
											(componentViewport?.y || 0) +
											0 +
											(((componentViewport?.height || 608) - 0 - 2040) / 2 +
												1600 +
												40),
									},
									N0kgPlv3I: {
										width: `max(${componentViewport?.width || "100vw"} * 0.6 - 40px, 1px)`,
									},
									RZsAD5UoD: {
										height: 400,
										width: componentViewport?.width || "100vw",
										y:
											(componentViewport?.y || 0) +
											0 +
											(((componentViewport?.height || 608) - 0 - 2040) / 2 +
												1600 +
												40),
									},
									Y5V5Jzvsb: {
										height: 400,
										width: componentViewport?.width || "100vw",
										y:
											(componentViewport?.y || 0) +
											0 +
											(((componentViewport?.height || 608) - 0 - 2040) / 2 +
												1600 +
												40),
									},
								},
								baseVariant,
								gestureVariant,
							)}
						>
							<SmartComponentScopedContainer
								className={"framer-19k48wt-container"}
								layoutDependency={layoutDependency}
								layoutId={"alhSLVIRw-container"}
								nodeId={"alhSLVIRw"}
								rendersWithMotion={true}
								scopeId={"M_0XXlsvG"}
							>
								{_jsx2(stdin_default2, {
									height: "100%",
									id: "alhSLVIRw",
									iEWo2giux: GLCQwQpPX,
									layoutId: "alhSLVIRw",
									Myka4MPLk: uwt0Mza21,
									qRiSJSdCR: toResponsiveImage2(ZkFD0MQ_a),
									SalXds4M0: "05",
									style: {
										height: "100%",
										width: "100%",
									},
									variant: "N8Q2LPD4z",
									VndmGA4XE: JmijCUJ3x,
									width: "100%",
									zyLBavdS6: zyLBavdS61tzhvyk,
									...addPropertyOverrides2(
										{
											bjur6M13y: {
												S8ey59QcC: S8ey59QcC18mwy6t,
												style: {
													width: "100%",
												},
												variant: "M4jMDboVd",
												zyLBavdS6: void 0,
											},
											i2fEWTYw3: {
												S8ey59QcC: S8ey59QcC18mwy6t,
												style: {
													width: "100%",
												},
												variant: "M4jMDboVd",
												zyLBavdS6: void 0,
											},
											KQ_Til4kh: {
												S8ey59QcC: S8ey59QcC18mwy6t,
												style: {
													width: "100%",
												},
												variant: "M4jMDboVd",
												zyLBavdS6: void 0,
											},
											N0kgPlv3I: {
												variant: "ly5K6dYAL",
											},
											RZsAD5UoD: {
												S8ey59QcC: S8ey59QcC18mwy6t,
												style: {
													width: "100%",
												},
												variant: "l4kNLZSMb",
												zyLBavdS6: void 0,
											},
											Y5V5Jzvsb: {
												S8ey59QcC: S8ey59QcC18mwy6t,
												style: {
													width: "100%",
												},
												variant: "M4jMDboVd",
												zyLBavdS6: void 0,
											},
										},
										baseVariant,
										gestureVariant,
									),
								})}
							</SmartComponentScopedContainer>
						</ComponentViewportProvider>
					</motion2.div>
				</Transition2>
			</Variants2>
		</LayoutGroup2>
	);
});
var css2 = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-COFEE.framer-jyh8qv, .framer-COFEE .framer-jyh8qv { display: block; }",
	".framer-COFEE.framer-16o466l { align-content: center; align-items: center; display: flex; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: 400px; justify-content: center; max-width: 800px; overflow: hidden; padding: 0px; position: relative; width: 600px; }",
	".framer-COFEE .framer-1surpun-container { flex: 1 0 0px; height: 100%; position: relative; width: 1px; }",
	".framer-COFEE .framer-1iqp84l-container, .framer-COFEE .framer-1xogf5p-container, .framer-COFEE .framer-iez57u-container, .framer-COFEE .framer-19k48wt-container { flex: none; height: 100%; position: relative; width: 10%; }",
	".framer-COFEE.framer-v-1vseqq6 .framer-1surpun-container, .framer-COFEE.framer-v-152n8qt .framer-1surpun-container, .framer-COFEE.framer-v-5mjckg .framer-1surpun-container, .framer-COFEE.framer-v-11jcr3s .framer-1surpun-container { flex: none; width: 10%; }",
	".framer-COFEE.framer-v-1vseqq6 .framer-1iqp84l-container, .framer-COFEE.framer-v-152n8qt .framer-1xogf5p-container, .framer-COFEE.framer-v-5mjckg .framer-iez57u-container, .framer-COFEE.framer-v-11jcr3s .framer-19k48wt-container { flex: 1 0 0px; width: 1px; }",
	".framer-COFEE.framer-v-jz7iat.framer-16o466l, .framer-COFEE.framer-v-1lbfjyi.framer-16o466l, .framer-COFEE.framer-v-10zasxx.framer-16o466l, .framer-COFEE.framer-v-qgsjjz.framer-16o466l, .framer-COFEE.framer-v-zfd7ek.framer-16o466l { flex-direction: column; height: min-content; width: 358px; }",
	".framer-COFEE.framer-v-jz7iat .framer-1surpun-container, .framer-COFEE.framer-v-1lbfjyi .framer-1surpun-container, .framer-COFEE.framer-v-10zasxx .framer-1surpun-container, .framer-COFEE.framer-v-qgsjjz .framer-1surpun-container, .framer-COFEE.framer-v-zfd7ek .framer-1surpun-container { flex: none; height: auto; width: 100%; }",
	".framer-COFEE.framer-v-jz7iat .framer-1iqp84l-container, .framer-COFEE.framer-v-jz7iat .framer-1xogf5p-container, .framer-COFEE.framer-v-jz7iat .framer-iez57u-container, .framer-COFEE.framer-v-jz7iat .framer-19k48wt-container, .framer-COFEE.framer-v-1lbfjyi .framer-1iqp84l-container, .framer-COFEE.framer-v-1lbfjyi .framer-1xogf5p-container, .framer-COFEE.framer-v-1lbfjyi .framer-iez57u-container, .framer-COFEE.framer-v-1lbfjyi .framer-19k48wt-container, .framer-COFEE.framer-v-10zasxx .framer-1iqp84l-container, .framer-COFEE.framer-v-10zasxx .framer-1xogf5p-container, .framer-COFEE.framer-v-10zasxx .framer-iez57u-container, .framer-COFEE.framer-v-10zasxx .framer-19k48wt-container, .framer-COFEE.framer-v-qgsjjz .framer-1iqp84l-container, .framer-COFEE.framer-v-qgsjjz .framer-1xogf5p-container, .framer-COFEE.framer-v-qgsjjz .framer-iez57u-container, .framer-COFEE.framer-v-qgsjjz .framer-19k48wt-container, .framer-COFEE.framer-v-zfd7ek .framer-1iqp84l-container, .framer-COFEE.framer-v-zfd7ek .framer-1xogf5p-container, .framer-COFEE.framer-v-zfd7ek .framer-iez57u-container, .framer-COFEE.framer-v-zfd7ek .framer-19k48wt-container { height: auto; width: 100%; }",
];
var FramerM_0XXlsvG = withCSS2(Component2, css2, "framer-COFEE");
var stdin_default3 = FramerM_0XXlsvG;
FramerM_0XXlsvG.displayName = "Expanded Card";
FramerM_0XXlsvG.defaultProps = {
	height: 400,
	width: 600,
};
addPropertyControls2(FramerM_0XXlsvG, {
	variant: {
		options: [
			"eY8CEsifj",
			"xy9RgHFiZ",
			"uXb_dVsYg",
			"xV0WwalK2",
			"N0kgPlv3I",
			"bjur6M13y",
			"i2fEWTYw3",
			"Y5V5Jzvsb",
			"KQ_Til4kh",
			"RZsAD5UoD",
		],
		optionTitles: [
			"Desktop 1",
			"Desktop 2",
			"Desktop 3",
			"Desktop 4",
			"Desktop 5",
			"Mobile 1",
			"Mobile 2",
			"Mobile 3",
			"Mobile 4",
			"Mobile 5",
		],
		title: "Variant",
		type: ControlType2.Enum,
	},
	dus5Mp6Wz: {
		__defaultAssetReference:
			"data:framer/asset-reference,jsoYuvRP6FOxNSujX1KSiZEvOpc.png?originalFilename=Surreal+Glass+Forms.png&preferredSize=auto",
		title: "Card 1 BG",
		type: ControlType2.ResponsiveImage,
	},
	hl3u2jSex: {
		defaultValue: "Expanding Cards",
		displayTextArea: false,
		title: "Card 1 Title",
		type: ControlType2.String,
	},
	mZf1Qz4KK: {
		defaultValue:
			"Today\u2019s demo is another snippet for an expanding flex cards in accordion style.",
		displayTextArea: false,
		title: "Card 1 Paragraph",
		type: ControlType2.String,
	},
	ymLV5IcYd: {
		defaultValue: {
			identifier:
				"module:S27Rn2XV0IhQFkUG0aQO/FBYhOPmZ4cgfEXv6wOEU/mNoisM7ar.js:default",
			moduleId: "S27Rn2XV0IhQFkUG0aQO",
		},
		setModuleId: "omX0gWFPqDwhaiWwf6ab",
		title: "Card 1 Icon",
		type: ControlType2.VectorSetItem,
	},
	eJc6PTKkJ: {
		__defaultAssetReference:
			"data:framer/asset-reference,jsoYuvRP6FOxNSujX1KSiZEvOpc.png?originalFilename=Surreal+Glass+Forms.png&preferredSize=auto",
		title: "Card 2 BG",
		type: ControlType2.ResponsiveImage,
	},
	Ibibb8Jt4: {
		defaultValue: "Expanding Cards",
		displayTextArea: false,
		title: "Card 2 Title",
		type: ControlType2.String,
	},
	QB08i4WHX: {
		defaultValue:
			"Today\u2019s demo is another snippet for an expanding flex cards in accordion style.",
		displayTextArea: false,
		title: "Card 2 Paragraph",
		type: ControlType2.String,
	},
	FuT_FhTRX: {
		defaultValue: {
			identifier:
				"module:S27Rn2XV0IhQFkUG0aQO/FBYhOPmZ4cgfEXv6wOEU/mNoisM7ar.js:default",
			moduleId: "S27Rn2XV0IhQFkUG0aQO",
		},
		setModuleId: "omX0gWFPqDwhaiWwf6ab",
		title: "Card 2 Icon",
		type: ControlType2.VectorSetItem,
	},
	VTQOG_1lE: {
		__defaultAssetReference:
			"data:framer/asset-reference,jsoYuvRP6FOxNSujX1KSiZEvOpc.png?originalFilename=Surreal+Glass+Forms.png&preferredSize=auto",
		title: "Card 3 BG",
		type: ControlType2.ResponsiveImage,
	},
	cJCVT2e9U: {
		defaultValue: "Expanding Cards",
		displayTextArea: false,
		title: "Card 3 Title",
		type: ControlType2.String,
	},
	ClpQ4Io2a: {
		defaultValue:
			"Today\u2019s demo is another snippet for an expanding flex cards in accordion style.",
		displayTextArea: false,
		title: "Card 3 Paragraph",
		type: ControlType2.String,
	},
	Xc48bWctO: {
		defaultValue: {
			identifier:
				"module:S27Rn2XV0IhQFkUG0aQO/FBYhOPmZ4cgfEXv6wOEU/mNoisM7ar.js:default",
			moduleId: "S27Rn2XV0IhQFkUG0aQO",
		},
		setModuleId: "omX0gWFPqDwhaiWwf6ab",
		title: "Card 3 Icon",
		type: ControlType2.VectorSetItem,
	},
	hKdFhNkIt: {
		__defaultAssetReference:
			"data:framer/asset-reference,jsoYuvRP6FOxNSujX1KSiZEvOpc.png?originalFilename=Surreal+Glass+Forms.png&preferredSize=auto",
		title: "Card 4 BG",
		type: ControlType2.ResponsiveImage,
	},
	nk2LdNAij: {
		defaultValue: "Expanding Cards",
		displayTextArea: false,
		title: "Card 4 Title",
		type: ControlType2.String,
	},
	ktxDHoxyu: {
		defaultValue:
			"Today\u2019s demo is another snippet for an expanding flex cards in accordion style.",
		displayTextArea: false,
		title: "Card 4 Paragraph",
		type: ControlType2.String,
	},
	kcydKql0g: {
		defaultValue: {
			identifier:
				"module:S27Rn2XV0IhQFkUG0aQO/FBYhOPmZ4cgfEXv6wOEU/mNoisM7ar.js:default",
			moduleId: "S27Rn2XV0IhQFkUG0aQO",
		},
		setModuleId: "omX0gWFPqDwhaiWwf6ab",
		title: "Card 4 Icon",
		type: ControlType2.VectorSetItem,
	},
	ZkFD0MQ_a: {
		__defaultAssetReference:
			"data:framer/asset-reference,jsoYuvRP6FOxNSujX1KSiZEvOpc.png?originalFilename=Surreal+Glass+Forms.png&preferredSize=auto",
		title: "Card 5 BG",
		type: ControlType2.ResponsiveImage,
	},
	JmijCUJ3x: {
		defaultValue: "Expanding Cards",
		displayTextArea: false,
		title: "Card 5 Title",
		type: ControlType2.String,
	},
	GLCQwQpPX: {
		defaultValue:
			"Today\u2019s demo is another snippet for an expanding flex cards in accordion style.",
		displayTextArea: false,
		title: "Card 5 Paragraph",
		type: ControlType2.String,
	},
	uwt0Mza21: {
		defaultValue: {
			identifier:
				"module:S27Rn2XV0IhQFkUG0aQO/FBYhOPmZ4cgfEXv6wOEU/mNoisM7ar.js:default",
			moduleId: "S27Rn2XV0IhQFkUG0aQO",
		},
		setModuleId: "omX0gWFPqDwhaiWwf6ab",
		title: "Card 5 Icon",
		type: ControlType2.VectorSetItem,
	},
});
addFonts2(
	FramerM_0XXlsvG,
	[
		{
			explicitInter: true,
			fonts: [],
		},
		...ImageFonts,
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// virtual:expanded-card
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {
	base: "bjur6M13y",
	xl: "eY8CEsifj",
};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"56c0de29b7dae5ae27de2720faa3b28919873163620fb2b2e6f9ced4d99cff44"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default3, {
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders ExpandedCardFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"56c0de29b7dae5ae27de2720faa3b28919873163620fb2b2e6f9ced4d99cff44"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={stdin_default3}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default3);
var expanded_card_default = ComponentWithRoot;
export { expanded_card_default as default };
