// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project 56c0de29b7dae5ae "Expanded Cards (copy)", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * variant?: 'Desktop Opened' | 'Desktop Default' | 'Mobile opened' | 'Mobile Default' // Variant
 * hover?: Function // Hover
 * bG?: {src: string, srcSet?: string, alt?: string} // BG
 * click?: Function // Click
 * number?: string // Number
 * paragraph?: string // Paragraph
 * title?: string // Title
 * icon?: any // Icon
}} Props

 */
import { routes, stdin_default } from "./chunks/chunk-WDXJCQ5O.js";

// virtual:image
import { Fragment as Fragment2 } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/gary0tK61nxlMNAyLkPy/Hq1ftwejCMAlITE8e0Co/eBAVAzu3r.js
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import {
	addFonts,
	addPropertyControls,
	ControlType,
	cx,
	getLoadingLazyAtYPosition,
	Image,
	Instance,
	RichText,
	useActiveVariantCallback,
	useComponentViewport,
	useLocaleInfo,
	useVariantState,
	withCSS,
} from "unframer";
import { LayoutGroup, motion, MotionConfigContext } from "unframer";
import * as React from "react";
import { useRef } from "react";
var cycleOrder = ["ly5K6dYAL", "N8Q2LPD4z", "l4kNLZSMb", "M4jMDboVd"];
var serializationHash = "framer-o1VIl";
var variantClassNames = {
	l4kNLZSMb: "framer-v-180q2td",
	ly5K6dYAL: "framer-v-f36akv",
	M4jMDboVd: "framer-v-bfjs1o",
	N8Q2LPD4z: "framer-v-5mcdky",
};
function addPropertyOverrides(overrides, ...variants) {
	const nextOverrides = {};
	variants?.forEach(
		(variant) => variant && Object.assign(nextOverrides, overrides[variant]),
	);
	return nextOverrides;
}
var transition1 = {
	damping: 30,
	delay: 0,
	mass: 1,
	stiffness: 160,
	type: "spring",
};
var toResponsiveImage = (value) => {
	if (
		typeof value === "object" &&
		value !== null &&
		typeof value.src === "string"
	) {
		return value;
	}
	return typeof value === "string"
		? {
				src: value,
			}
		: void 0;
};
var Transition = ({ value, children }) => {
	const config = React.useContext(MotionConfigContext);
	const transition = value ?? config.transition;
	const contextValue = React.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider value={contextValue}>
			{children}
		</MotionConfigContext.Provider>
	);
};
var Variants = motion.create(React.Fragment);
var humanReadableVariantMap = {
	"Desktop Default": "N8Q2LPD4z",
	"Desktop Opened": "ly5K6dYAL",
	"Mobile Default": "M4jMDboVd",
	"Mobile opened": "l4kNLZSMb",
};
var getProps = ({
	bG,
	click,
	height,
	hover,
	icon,
	id,
	number,
	paragraph,
	title,
	width,
	...props
}) => {
	return {
		...props,
		iEWo2giux:
			paragraph ??
			props.iEWo2giux ??
			"Today\u2019s demo is another snippet for an expanding flex cards in accordion style.",
		Myka4MPLk: icon ?? props.Myka4MPLk ?? stdin_default,
		qRiSJSdCR: bG ??
			props.qRiSJSdCR ?? {
				alt: "",
				pixelHeight: 2400,
				pixelWidth: 1808,
				src: "https://framerusercontent.com/images/jsoYuvRP6FOxNSujX1KSiZEvOpc.png?scale-down-to=512",
				srcSet:
					"https://framerusercontent.com/images/jsoYuvRP6FOxNSujX1KSiZEvOpc.png?scale-down-to=1024 771w,https://framerusercontent.com/images/jsoYuvRP6FOxNSujX1KSiZEvOpc.png?scale-down-to=2048 1542w,https://framerusercontent.com/images/jsoYuvRP6FOxNSujX1KSiZEvOpc.png 1808w",
			},
		S8ey59QcC: click ?? props.S8ey59QcC,
		SalXds4M0: number ?? props.SalXds4M0 ?? "01",
		variant:
			humanReadableVariantMap[props.variant] ?? props.variant ?? "ly5K6dYAL",
		VndmGA4XE: title ?? props.VndmGA4XE ?? "Expanding Cards",
		zyLBavdS6: hover ?? props.zyLBavdS6,
	};
};
var createLayoutDependency = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const fallbackRef = useRef(null);
	const refBinding = ref ?? fallbackRef;
	const defaultLayoutId = React.useId();
	const { activeLocale, setLocale } = useLocaleInfo();
	const componentViewport = useComponentViewport();
	const {
		style,
		className,
		layoutId,
		variant,
		zyLBavdS6,
		qRiSJSdCR,
		S8ey59QcC,
		SalXds4M0,
		iEWo2giux,
		VndmGA4XE,
		Myka4MPLk,
		...restProps
	} = getProps(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState({
		cycleOrder,
		defaultVariant: "ly5K6dYAL",
		ref: refBinding,
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const { activeVariantCallback, delay } =
		useActiveVariantCallback(baseVariant);
	const onTapy7dnty = activeVariantCallback(async (...args) => {
		setGestureState({
			isPressed: false,
		});
		if (S8ey59QcC) {
			const res = await S8ey59QcC(...args);
			if (res === false) return false;
		}
	});
	const onMouseEnter1k75mhf = activeVariantCallback(async (...args) => {
		setGestureState({
			isHovered: true,
		});
		if (zyLBavdS6) {
			const res = await zyLBavdS6(...args);
			if (res === false) return false;
		}
	});
	const sharedStyleClassNames = [];
	const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
	const isDisplayed = () => {
		if (baseVariant === "M4jMDboVd") return false;
		return true;
	};
	const isDisplayed1 = () => {
		if (baseVariant === "N8Q2LPD4z") return false;
		return true;
	};
	return (
		<LayoutGroup id={layoutId ?? defaultLayoutId}>
			<Variants animate={variants} initial={false}>
				<Transition value={transition1}>
					<motion.div
						{...restProps}
						{...gestureHandlers}
						className={cx(
							scopingClassNames,
							"framer-f36akv",
							className,
							classNames,
						)}
						data-framer-name={"Desktop Opened"}
						data-highlight={true}
						layoutDependency={layoutDependency}
						layoutId={"ly5K6dYAL"}
						onMouseEnter={onMouseEnter1k75mhf}
						onTap={onTapy7dnty}
						ref={refBinding}
						style={{
							...style,
						}}
						{...addPropertyOverrides(
							{
								l4kNLZSMb: {
									"data-framer-name": "Mobile opened",
								},
								M4jMDboVd: {
									"data-framer-name": "Mobile Default",
								},
								N8Q2LPD4z: {
									"data-framer-name": "Desktop Default",
								},
							},
							baseVariant,
							gestureVariant,
						)}
					>
						<motion.div
							className={"framer-18lcyur"}
							data-framer-name={"Background"}
							layoutDependency={layoutDependency}
							layoutId={"AEFLPhv2D"}
							style={{
								borderBottomLeftRadius: 10,
								borderBottomRightRadius: 10,
								borderTopLeftRadius: 10,
								borderTopRightRadius: 10,
							}}
						>
							<Image
								background={{
									alt: "",
									fit: "fill",
									loading: getLoadingLazyAtYPosition(
										(componentViewport?.y || 0) +
											((componentViewport?.height || 400) * 0.5000000000000002 -
												((componentViewport?.height || 400) * 1) / 2) +
											(0 +
												((componentViewport?.height || 400) * 1 -
													0 -
													((componentViewport?.height || 400) * 1 - 0) * 1) /
													2),
									),
									pixelHeight: 2400,
									pixelWidth: 1808,
									sizes: "400px",
									...toResponsiveImage(qRiSJSdCR),
								}}
								className={"framer-oia2f5"}
								data-framer-name={"Image"}
								layoutDependency={layoutDependency}
								layoutId={"vDHqqnEOa"}
								style={{
									borderBottomLeftRadius: 10,
									borderBottomRightRadius: 10,
									borderTopLeftRadius: 10,
									borderTopRightRadius: 10,
								}}
								{...addPropertyOverrides(
									{
										l4kNLZSMb: {
											background: {
												alt: "",
												fit: "fill",
												loading: getLoadingLazyAtYPosition(
													(componentViewport?.y || 0) +
														((componentViewport?.height || 400) *
															0.5000000000000002 -
															((componentViewport?.height || 400) * 1) / 2) +
														(0 +
															((componentViewport?.height || 400) * 1 -
																0 -
																420) /
																2),
												),
												pixelHeight: 2400,
												pixelWidth: 1808,
												sizes: `max(${componentViewport?.width || "100vw"}, 1px)`,
												...toResponsiveImage(qRiSJSdCR),
											},
										},
										M4jMDboVd: {
											background: {
												alt: "",
												fit: "fill",
												loading: getLoadingLazyAtYPosition(
													(componentViewport?.y || 0) +
														((componentViewport?.height || 42) *
															0.5000000000000002 -
															((componentViewport?.height || 42) * 1) / 2) +
														(0 +
															((componentViewport?.height || 42) * 1 -
																0 -
																420) /
																2),
												),
												pixelHeight: 2400,
												pixelWidth: 1808,
												sizes: `max(${componentViewport?.width || "100vw"}, 1px)`,
												...toResponsiveImage(qRiSJSdCR),
											},
										},
									},
									baseVariant,
									gestureVariant,
								)}
							/>
							<motion.div
								className={"framer-1qokm0z"}
								data-framer-name={"Overlay"}
								layoutDependency={layoutDependency}
								layoutId={"d0Mcbg_0p"}
								style={{
									backgroundColor: "rgb(0, 0, 0)",
									opacity: 0.5,
								}}
								variants={{
									M4jMDboVd: {
										opacity: 0.8,
									},
									N8Q2LPD4z: {
										opacity: 0.8,
									},
								}}
							/>
						</motion.div>
						<motion.div
							className={"framer-1y118y9"}
							data-framer-name={"Content wrapper"}
							layoutDependency={layoutDependency}
							layoutId={"CVb63EpcY"}
						>
							<motion.div
								className={"framer-xgb03n"}
								data-framer-name={"Number"}
								layoutDependency={layoutDependency}
								layoutId={"ezXJ1cccX"}
							>
								<RichText
									__fromCanvasComponent={true}
									className={"framer-n40b6v"}
									fonts={["Inter-SemiBold"]}
									layoutDependency={layoutDependency}
									layoutId={"mbk_eFcNd"}
									style={{
										"--extracted-r6o4lv": "rgb(255, 255, 255)",
										"--framer-link-text-color": "rgb(0, 153, 255)",
										"--framer-link-text-decoration": "underline",
									}}
									text={SalXds4M0}
									verticalAlignment={"top"}
									withExternalLayout={true}
								>
									<React.Fragment>
										<motion.p
											style={{
												"--font-selector": "SW50ZXItU2VtaUJvbGQ=",
												"--framer-font-family":
													'"Inter", "Inter Placeholder", sans-serif',
												"--framer-font-size": "14px",
												"--framer-font-weight": "600",
												"--framer-text-alignment": "left",
												"--framer-text-color":
													"var(--extracted-r6o4lv, rgb(255, 255, 255))",
											}}
										>
											{"01"}
										</motion.p>
									</React.Fragment>
								</RichText>
							</motion.div>
							{isDisplayed() && (
								<motion.div
									className={"framer-1gpkcqn"}
									data-framer-name={"Buttom"}
									layoutDependency={layoutDependency}
									layoutId={"I11I3kHyo"}
								>
									<motion.div
										className={"framer-19mq03d"}
										data-framer-name={"Content"}
										layoutDependency={layoutDependency}
										layoutId={"xulmpbjPA"}
										style={{
											opacity: 1,
										}}
										variants={{
											l4kNLZSMb: {
												opacity: 1,
											},
											N8Q2LPD4z: {
												opacity: 0,
											},
										}}
									>
										<RichText
											__fromCanvasComponent={true}
											className={"framer-qhips9"}
											fonts={["Inter"]}
											layoutDependency={layoutDependency}
											layoutId={"q6g3P6g40"}
											style={{
												"--extracted-r6o4lv": "rgb(255, 255, 255)",
												"--framer-link-text-color": "rgb(0, 153, 255)",
												"--framer-link-text-decoration": "underline",
											}}
											text={iEWo2giux}
											verticalAlignment={"top"}
											withExternalLayout={true}
										>
											<React.Fragment>
												<motion.p
													style={{
														"--framer-font-size": "14px",
														"--framer-line-height": "1.6em",
														"--framer-text-alignment": "left",
														"--framer-text-color":
															"var(--extracted-r6o4lv, rgb(255, 255, 255))",
													}}
												>
													{
														"Today\u2019s demo is another snippet for an expanding flex cards in accordion style."
													}
												</motion.p>
											</React.Fragment>
										</RichText>
									</motion.div>
									<motion.div
										className={"framer-1mbyo0s"}
										data-framer-name={"Title"}
										layoutDependency={layoutDependency}
										layoutId={"TGs0JIuam"}
									>
										<Instance
											animated={true}
											className={"framer-14t09ok"}
											Component={Myka4MPLk}
											layoutDependency={layoutDependency}
											layoutId={"LLlvOYzXT"}
											style={{
												"--1m6trwb": 0,
												"--21h8s6": "rgb(255, 255, 255)",
												"--pgex8v": 1.5,
											}}
										/>
										{isDisplayed1() && (
											<RichText
												__fromCanvasComponent={true}
												className={"framer-gsykpm"}
												fonts={["Inter-SemiBold"]}
												layoutDependency={layoutDependency}
												layoutId={"bWtIzJKvy"}
												style={{
													"--extracted-r6o4lv": "rgb(255, 255, 255)",
													"--framer-link-text-color": "rgb(0, 153, 255)",
													"--framer-link-text-decoration": "underline",
												}}
												text={VndmGA4XE}
												verticalAlignment={"top"}
												withExternalLayout={true}
											>
												<React.Fragment>
													<motion.p
														style={{
															"--font-selector": "SW50ZXItU2VtaUJvbGQ=",
															"--framer-font-family":
																'"Inter", "Inter Placeholder", sans-serif',
															"--framer-font-size": "14px",
															"--framer-font-weight": "600",
															"--framer-text-color":
																"var(--extracted-r6o4lv, rgb(255, 255, 255))",
														}}
													>
														{"Expanding Cards"}
													</motion.p>
												</React.Fragment>
											</RichText>
										)}
									</motion.div>
								</motion.div>
							)}
						</motion.div>
					</motion.div>
				</Transition>
			</Variants>
		</LayoutGroup>
	);
});
var css = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-o1VIl.framer-ea4tx3, .framer-o1VIl .framer-ea4tx3 { display: block; }",
	".framer-o1VIl.framer-f36akv { align-content: flex-end; align-items: flex-end; cursor: pointer; display: flex; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: 400px; justify-content: center; overflow: hidden; padding: 12px; position: relative; width: 368px; }",
	".framer-o1VIl .framer-18lcyur { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: 100%; justify-content: center; left: 0px; overflow: hidden; padding: 0px; position: absolute; top: calc(50.00000000000002% - 100% / 2); width: 100%; will-change: var(--framer-will-change-override, transform); }",
	".framer-o1VIl .framer-oia2f5 { flex: none; height: 100%; position: relative; width: 400px; z-index: 1; }",
	".framer-o1VIl .framer-1qokm0z { flex: none; height: 100%; left: calc(50.00000000000002% - 100% / 2); overflow: hidden; position: absolute; top: calc(50.00000000000002% - 100% / 2); width: 100%; z-index: 1; }",
	".framer-o1VIl .framer-1y118y9 { align-content: center; align-items: center; display: flex; flex: 1 0 0px; flex-direction: column; flex-wrap: nowrap; height: 100%; justify-content: space-between; overflow: hidden; padding: 0px; position: relative; width: 1px; z-index: 2; }",
	".framer-o1VIl .framer-xgb03n { align-content: flex-start; align-items: flex-start; display: flex; flex: 1 0 0px; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: 1px; justify-content: flex-start; overflow: visible; padding: 0px; position: relative; width: 100%; }",
	".framer-o1VIl .framer-n40b6v { flex: none; height: auto; position: relative; white-space: pre; width: auto; }",
	".framer-o1VIl .framer-1gpkcqn { align-content: flex-start; align-items: flex-start; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: center; overflow: visible; padding: 0px; position: relative; width: 100%; }",
	".framer-o1VIl .framer-19mq03d, .framer-o1VIl .framer-1mbyo0s { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: flex-start; overflow: visible; padding: 0px; position: relative; width: 100%; }",
	".framer-o1VIl .framer-qhips9, .framer-o1VIl .framer-gsykpm { flex: 1 0 0px; height: auto; position: relative; white-space: pre-wrap; width: 1px; word-break: break-word; word-wrap: break-word; }",
	".framer-o1VIl .framer-14t09ok { flex: none; height: var(--framer-aspect-ratio-supported, 20px); position: relative; width: 20px; }",
	".framer-o1VIl.framer-v-5mcdky.framer-f36akv { width: 60px; }",
	".framer-o1VIl.framer-v-5mcdky .framer-xgb03n, .framer-o1VIl.framer-v-5mcdky .framer-1mbyo0s { justify-content: center; }",
	".framer-o1VIl.framer-v-5mcdky .framer-19mq03d { min-width: 320px; }",
	".framer-o1VIl.framer-v-180q2td.framer-f36akv { width: 358px; }",
	".framer-o1VIl.framer-v-180q2td .framer-oia2f5, .framer-o1VIl.framer-v-bfjs1o .framer-oia2f5 { flex: 1 0 0px; height: 420px; width: 1px; }",
	".framer-o1VIl.framer-v-bfjs1o.framer-f36akv { height: 42px; width: 358px; }",
	".framer-o1VIl.framer-v-bfjs1o .framer-xgb03n { align-content: center; align-items: center; }",
];
var FramereBAVAzu3r = withCSS(Component, css, "framer-o1VIl");
var stdin_default2 = FramereBAVAzu3r;
FramereBAVAzu3r.displayName = "Image";
FramereBAVAzu3r.defaultProps = {
	height: 400,
	width: 368,
};
addPropertyControls(FramereBAVAzu3r, {
	variant: {
		options: ["ly5K6dYAL", "N8Q2LPD4z", "l4kNLZSMb", "M4jMDboVd"],
		optionTitles: [
			"Desktop Opened",
			"Desktop Default",
			"Mobile opened",
			"Mobile Default",
		],
		title: "Variant",
		type: ControlType.Enum,
	},
	zyLBavdS6: {
		title: "Hover",
		type: ControlType.EventHandler,
	},
	qRiSJSdCR: {
		__defaultAssetReference:
			"data:framer/asset-reference,jsoYuvRP6FOxNSujX1KSiZEvOpc.png?originalFilename=Surreal+Glass+Forms.png&preferredSize=auto",
		__vekterDefault: {
			alt: "",
			assetReference:
				"data:framer/asset-reference,jsoYuvRP6FOxNSujX1KSiZEvOpc.png?originalFilename=Surreal+Glass+Forms.png&preferredSize=auto",
		},
		title: "BG",
		type: ControlType.ResponsiveImage,
	},
	S8ey59QcC: {
		title: "Click",
		type: ControlType.EventHandler,
	},
	SalXds4M0: {
		defaultValue: "01",
		displayTextArea: false,
		title: "Number",
		type: ControlType.String,
	},
	iEWo2giux: {
		defaultValue:
			"Today\u2019s demo is another snippet for an expanding flex cards in accordion style.",
		displayTextArea: false,
		title: "Paragraph",
		type: ControlType.String,
	},
	VndmGA4XE: {
		defaultValue: "Expanding Cards",
		displayTextArea: false,
		title: "Title",
		type: ControlType.String,
	},
	Myka4MPLk: {
		defaultValue: {
			identifier:
				"module:S27Rn2XV0IhQFkUG0aQO/FBYhOPmZ4cgfEXv6wOEU/mNoisM7ar.js:default",
			moduleId: "S27Rn2XV0IhQFkUG0aQO",
		},
		setModuleId: "omX0gWFPqDwhaiWwf6ab",
		title: "Icon",
		type: ControlType.VectorSetItem,
	},
});
addFonts(
	FramereBAVAzu3r,
	[
		{
			explicitInter: true,
			fonts: [
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
					url: "https://framerusercontent.com/assets/hyOgCu0Xnghbimh0pE8QTvtt2AU.woff2",
					weight: "600",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
					url: "https://framerusercontent.com/assets/NeGmSOXrPBfEFIy5YZeHq17LEDA.woff2",
					weight: "600",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+1F00-1FFF",
					url: "https://framerusercontent.com/assets/oYaAX5himiTPYuN8vLWnqBbfD2s.woff2",
					weight: "600",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+0370-03FF",
					url: "https://framerusercontent.com/assets/lEJLP4R0yuCaMCjSXYHtJw72M.woff2",
					weight: "600",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
					url: "https://framerusercontent.com/assets/cRJyLNuTJR5jbyKzGi33wU9cqIQ.woff2",
					weight: "600",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2074, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
					url: "https://framerusercontent.com/assets/1ZFS7N918ojhhd0nQWdj3jz4w.woff2",
					weight: "600",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
					url: "https://framerusercontent.com/assets/A0Wcc7NgXMjUuFdquHDrIZpzZw0.woff2",
					weight: "600",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
					url: "https://framerusercontent.com/assets/5vvr9Vy74if2I6bQbJvbw7SY1pQ.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
					url: "https://framerusercontent.com/assets/EOr0mi4hNtlgWNn9if640EZzXCo.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+1F00-1FFF",
					url: "https://framerusercontent.com/assets/Y9k9QrlZAqio88Klkmbd8VoMQc.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+0370-03FF",
					url: "https://framerusercontent.com/assets/OYrD2tBIBPvoJXiIHnLoOXnY9M.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
					url: "https://framerusercontent.com/assets/JeYwfuaPfZHQhEG8U5gtPDZ7WQ.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2074, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
					url: "https://framerusercontent.com/assets/vQyevYAyHtARFwPqUzQGpnDs.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
					url: "https://framerusercontent.com/assets/b6Y37FthZeALduNqHicBT6FutY.woff2",
					weight: "400",
				},
			],
		},
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// virtual:image
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {
	base: "M4jMDboVd",
};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"56c0de29b7dae5ae27de2720faa3b28919873163620fb2b2e6f9ced4d99cff44"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default2, {
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders ImageFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"56c0de29b7dae5ae27de2720faa3b28919873163620fb2b2e6f9ced4d99cff44"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={stdin_default2}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default2);
var image_default = ComponentWithRoot;
export { image_default as default };
