-- +goose Up
CREATE TABLE artifacts (
    id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    organization_id uuid NOT NULL REFERENCES organizations (id) ON DELETE CASCADE,
    workspace_id uuid NOT NULL,
    run_id uuid REFERENCES runs (id) ON DELETE CASCADE,
    run_agent_id uuid REFERENCES run_agents (id) ON DELETE CASCADE,
    artifact_type text NOT NULL,
    storage_bucket text NOT NULL,
    storage_key text NOT NULL,
    content_type text,
    size_bytes bigint CHECK (size_bytes IS NULL OR size_bytes >= 0),
    checksum_sha256 text,
    visibility text NOT NULL DEFAULT 'private' CHECK (visibility IN ('private', 'public')),
    retention_status text NOT NULL DEFAULT 'active' CHECK (retention_status IN ('active', 'scheduled_for_deletion', 'deleted')),
    metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    UNIQUE (storage_bucket, storage_key),
    FOREIGN KEY (workspace_id, organization_id) REFERENCES workspaces (id, organization_id) ON DELETE CASCADE,
    CHECK (run_agent_id IS NULL OR run_id IS NOT NULL)
);

ALTER TABLE artifacts
ADD CONSTRAINT artifacts_run_fk
FOREIGN KEY (run_id, organization_id, workspace_id) REFERENCES runs (id, organization_id, workspace_id) ON DELETE CASCADE;

ALTER TABLE artifacts
ADD CONSTRAINT artifacts_run_agent_fk
FOREIGN KEY (run_agent_id, run_id) REFERENCES run_agents (id, run_id) ON DELETE CASCADE;

CREATE TABLE run_events (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    run_id uuid NOT NULL REFERENCES runs (id) ON DELETE CASCADE,
    run_agent_id uuid NOT NULL,
    sequence_number bigint NOT NULL CHECK (sequence_number > 0),
    event_type text NOT NULL,
    actor_type text NOT NULL,
    occurred_at timestamptz NOT NULL,
    artifact_id uuid REFERENCES artifacts (id) ON DELETE SET NULL,
    payload jsonb NOT NULL DEFAULT '{}'::jsonb,
    UNIQUE (run_agent_id, sequence_number)
);

ALTER TABLE run_events
ADD CONSTRAINT run_events_run_agent_fk
FOREIGN KEY (run_agent_id, run_id) REFERENCES run_agents (id, run_id) ON DELETE CASCADE;

CREATE TABLE run_replays (
    id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    run_id uuid NOT NULL UNIQUE REFERENCES runs (id) ON DELETE CASCADE,
    artifact_id uuid REFERENCES artifacts (id) ON DELETE SET NULL,
    summary jsonb NOT NULL DEFAULT '{}'::jsonb,
    latest_sequence_number bigint,
    event_count bigint NOT NULL DEFAULT 0 CHECK (event_count >= 0),
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE run_agent_replays (
    id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    run_agent_id uuid NOT NULL UNIQUE REFERENCES run_agents (id) ON DELETE CASCADE,
    artifact_id uuid REFERENCES artifacts (id) ON DELETE SET NULL,
    summary jsonb NOT NULL DEFAULT '{}'::jsonb,
    latest_sequence_number bigint,
    event_count bigint NOT NULL DEFAULT 0 CHECK (event_count >= 0),
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE evaluation_specs (
    id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    challenge_pack_version_id uuid REFERENCES challenge_pack_versions (id) ON DELETE CASCADE,
    name text NOT NULL,
    version_number integer NOT NULL CHECK (version_number > 0),
    judge_mode text NOT NULL CHECK (judge_mode IN ('deterministic', 'llm_judge', 'hybrid')),
    definition jsonb NOT NULL DEFAULT '{}'::jsonb,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    UNIQUE (name, version_number)
);

CREATE TABLE judge_results (
    id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    run_agent_id uuid NOT NULL REFERENCES run_agents (id) ON DELETE CASCADE,
    evaluation_spec_id uuid NOT NULL REFERENCES evaluation_specs (id) ON DELETE CASCADE,
    challenge_identity_id uuid REFERENCES challenge_identities (id) ON DELETE SET NULL,
    judge_key text NOT NULL,
    verdict text,
    normalized_score numeric(7,4),
    raw_output jsonb NOT NULL DEFAULT '{}'::jsonb,
    created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE metric_results (
    id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    run_agent_id uuid NOT NULL REFERENCES run_agents (id) ON DELETE CASCADE,
    evaluation_spec_id uuid NOT NULL REFERENCES evaluation_specs (id) ON DELETE CASCADE,
    challenge_identity_id uuid REFERENCES challenge_identities (id) ON DELETE SET NULL,
    metric_key text NOT NULL,
    metric_type text NOT NULL CHECK (metric_type IN ('numeric', 'text', 'boolean')),
    numeric_value numeric(18,6),
    text_value text,
    boolean_value boolean,
    unit text,
    metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
    created_at timestamptz NOT NULL DEFAULT now(),
    CHECK (
        ((numeric_value IS NOT NULL)::integer +
         (text_value IS NOT NULL)::integer +
         (boolean_value IS NOT NULL)::integer) <= 1
    )
);

CREATE TABLE run_agent_scorecards (
    id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    run_agent_id uuid NOT NULL UNIQUE REFERENCES run_agents (id) ON DELETE CASCADE,
    evaluation_spec_id uuid NOT NULL REFERENCES evaluation_specs (id) ON DELETE RESTRICT,
    overall_score numeric(7,4),
    correctness_score numeric(7,4),
    reliability_score numeric(7,4),
    latency_score numeric(7,4),
    cost_score numeric(7,4),
    scorecard jsonb NOT NULL DEFAULT '{}'::jsonb,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE run_scorecards (
    id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    run_id uuid NOT NULL UNIQUE REFERENCES runs (id) ON DELETE CASCADE,
    evaluation_spec_id uuid NOT NULL REFERENCES evaluation_specs (id) ON DELETE RESTRICT,
    winning_run_agent_id uuid,
    scorecard jsonb NOT NULL DEFAULT '{}'::jsonb,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE run_scorecards
ADD CONSTRAINT run_scorecards_winner_fk
FOREIGN KEY (winning_run_agent_id, run_id) REFERENCES run_agents (id, run_id) ON DELETE RESTRICT;

CREATE INDEX run_events_run_id_idx ON run_events (run_id, occurred_at);
CREATE INDEX run_events_run_agent_id_idx ON run_events (run_agent_id, sequence_number);
CREATE INDEX judge_results_run_agent_id_idx ON judge_results (run_agent_id);
CREATE INDEX metric_results_run_agent_id_idx ON metric_results (run_agent_id);

CREATE TRIGGER artifacts_set_updated_at
BEFORE UPDATE ON artifacts
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();

CREATE TRIGGER run_replays_set_updated_at
BEFORE UPDATE ON run_replays
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();

CREATE TRIGGER run_agent_replays_set_updated_at
BEFORE UPDATE ON run_agent_replays
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();

CREATE TRIGGER evaluation_specs_set_updated_at
BEFORE UPDATE ON evaluation_specs
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();

CREATE TRIGGER run_agent_scorecards_set_updated_at
BEFORE UPDATE ON run_agent_scorecards
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();

CREATE TRIGGER run_scorecards_set_updated_at
BEFORE UPDATE ON run_scorecards
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();

-- +goose Down
DROP TRIGGER IF EXISTS run_scorecards_set_updated_at ON run_scorecards;
DROP TRIGGER IF EXISTS run_agent_scorecards_set_updated_at ON run_agent_scorecards;
DROP TRIGGER IF EXISTS evaluation_specs_set_updated_at ON evaluation_specs;
DROP TRIGGER IF EXISTS run_agent_replays_set_updated_at ON run_agent_replays;
DROP TRIGGER IF EXISTS run_replays_set_updated_at ON run_replays;
DROP TRIGGER IF EXISTS artifacts_set_updated_at ON artifacts;

DROP TABLE IF EXISTS run_scorecards;
DROP TABLE IF EXISTS run_agent_scorecards;
DROP TABLE IF EXISTS metric_results;
DROP TABLE IF EXISTS judge_results;
DROP TABLE IF EXISTS evaluation_specs;
DROP TABLE IF EXISTS run_agent_replays;
DROP TABLE IF EXISTS run_replays;
DROP TABLE IF EXISTS run_events;
DROP TABLE IF EXISTS artifacts;
