-- +goose Up
CREATE TABLE agent_harness_execution_status_history (
    id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    agent_harness_execution_id uuid NOT NULL REFERENCES agent_harness_executions (id) ON DELETE CASCADE,
    from_status text,
    to_status text NOT NULL CHECK (to_status IN (
        'queued',
        'provisioning',
        'running',
        'scoring',
        'completed',
        'failed',
        'cancelled'
    )),
    reason text,
    changed_by_user_id uuid REFERENCES users (id) ON DELETE SET NULL,
    changed_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE agent_harness_execution_events (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    agent_harness_execution_id uuid NOT NULL REFERENCES agent_harness_executions (id) ON DELETE CASCADE,
    sequence_number bigint NOT NULL CHECK (sequence_number > 0),
    event_type text NOT NULL,
    actor_type text NOT NULL,
    occurred_at timestamptz NOT NULL DEFAULT now(),
    artifact_id uuid REFERENCES artifacts (id) ON DELETE SET NULL,
    payload jsonb NOT NULL DEFAULT '{}'::jsonb,
    UNIQUE (agent_harness_execution_id, sequence_number)
);

CREATE INDEX agent_harness_execution_status_history_execution_idx
ON agent_harness_execution_status_history (agent_harness_execution_id, changed_at ASC, id ASC);

CREATE INDEX agent_harness_execution_events_execution_idx
ON agent_harness_execution_events (agent_harness_execution_id, sequence_number ASC);

-- +goose Down
DROP INDEX IF EXISTS agent_harness_execution_events_execution_idx;
DROP INDEX IF EXISTS agent_harness_execution_status_history_execution_idx;
DROP TABLE IF EXISTS agent_harness_execution_events;
DROP TABLE IF EXISTS agent_harness_execution_status_history;
