-- +goose Up
CREATE TABLE agent_tryout_events (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    agent_tryout_id uuid NOT NULL REFERENCES agent_tryouts (id) ON DELETE CASCADE,
    sequence_number bigint NOT NULL CHECK (sequence_number > 0),
    event_type text NOT NULL,
    actor_type text NOT NULL DEFAULT 'worker',
    occurred_at timestamptz NOT NULL DEFAULT now(),
    payload jsonb NOT NULL DEFAULT '{}'::jsonb,
    UNIQUE (agent_tryout_id, sequence_number)
);

CREATE INDEX agent_tryout_events_tryout_id_idx
ON agent_tryout_events (agent_tryout_id, id);

-- +goose Down
DROP INDEX IF EXISTS agent_tryout_events_tryout_id_idx;
DROP TABLE IF EXISTS agent_tryout_events;
