-- +goose Up
CREATE TABLE agent_tryout_turns (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    agent_tryout_id uuid NOT NULL REFERENCES agent_tryouts (id) ON DELETE CASCADE,
    turn_index integer NOT NULL CHECK (turn_index >= 0),
    role text NOT NULL DEFAULT 'user',
    message text NOT NULL DEFAULT '',
    status text NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'processing', 'done')),
    created_at timestamptz NOT NULL DEFAULT now(),
    processed_at timestamptz,
    UNIQUE (agent_tryout_id, turn_index)
);

-- Partial index so the session activity can cheaply claim the next pending turn.
CREATE INDEX agent_tryout_turns_pending_idx
ON agent_tryout_turns (agent_tryout_id, id)
WHERE status = 'pending';

-- +goose Down
DROP INDEX IF EXISTS agent_tryout_turns_pending_idx;
DROP TABLE IF EXISTS agent_tryout_turns;
