package vibe

import (
	"fmt"
	"github.com/google/uuid"
	"testing"
)

func TestRetainedAuthoringWireIdentity(t *testing.T) {
	// Fingerprints captured from the pre-cleanup PR head (5a0237b0), not regenerated by this implementation.
	golden := map[string]string{"15/routing": "22344c843cd68f24f0fdb957a460f7582a8d2cd9163be7a95b22556f2a54752b",
		"15/authoring": "00f978f4ae8c5f9494db586592bfdc8e944e7ad9b0a0b77b9c765f6f1869e030",
		"18/routing":   "17de26fb2362d2b29e67e5f972231b4c1a37295fc121a7d9db690923aeb0e775",
		"18/authoring": "00f978f4ae8c5f9494db586592bfdc8e944e7ad9b0a0b77b9c765f6f1869e030",
		"20/routing":   "582211b6c56334a8ea109364a26a10976da23fa9f6311f9af81c89a9ad06b04e",
		"20/authoring": "85fbf3356b50227e3252f1e53cf041e14db813a64c948e48470ecf71c1ce9322"}
	id := uuid.MustParse("00000000-0000-4000-8000-000000000001")
	for _, version := range []int{15, 18, 20} {
		state := newConversationState(id)
		p := Plan{AuthoringVersion: version, Submission: Submission{ClientID: id, Content: "My agent echoes supplied text. Prepare three checks.", Kind: "message", Models: DefaultModels()}, Document: Document{FormatVersion: 1}, Conversation: &ConversationContext{CurrentRequest: originalBlock(id, "My agent echoes supplied text. Prepare three checks."), Sources: []SourceBlock{originalBlock(id, "My agent echoes supplied text. Prepare three checks.")}, State: state, StateBaseHash: Hash(raw(state)), SourceVersion: SourcePolicyVersion, ContractVersion: "vibe-v15", RequiredCount: 3}}
		if version != 15 {
			p.Document.Evaluation = &EvaluationContext{Door: "build"}
			p.Conversation.ContractVersion = "vibe-v18"
		}
		if version == 20 {
			p.Conversation.ContractVersion = "vibe-v20"
		}
		for _, stage := range []conversationTask{taskRoute, taskAuthor} {
			hash := Hash(raw(taskMessages(p, stage, "prepare_tests", nil)))
			if want := golden[fmt.Sprintf("%d/%s", version, stage)]; hash != want {
				t.Fatalf("retained provider request changed: %d/%s got %s want %s", version, stage, hash, want)
			}
		}
	}
}
